#!/usr/bin/env python3
"""
build_deck.py — Generate and compile the Beamer presentation
  "End-only + Mylar-wrapped EJ-204 bar: optical simulation study"

Usage:
  python build_deck.py [--data-dir PATH] [--out-dir PATH] [--skip-analysis] [--no-compile]

All numerical values in main.tex come from deck_values.json (no hardcoding).
The LaTeX template uses @PLACEHOLDER@ markers to avoid Python f-string / LaTeX
brace conflicts.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import pathlib
import shutil
import subprocess
import sys

HERE = pathlib.Path(__file__).parent


# ── helpers ───────────────────────────────────────────────────────────────────

def _run_analysis(data_dir: pathlib.Path, out_dir: pathlib.Path) -> None:
    script = HERE / "analysis_endonly_mylar.py"
    if not script.exists():
        sys.exit(f"ERROR: analysis_endonly_mylar.py not found at {script}")
    print("Running analysis...")
    subprocess.run([sys.executable, str(script),
                    "--data-dir", str(data_dir),
                    "--out-dir", str(out_dir)], check=True)


def _load_values(out_dir: pathlib.Path) -> dict:
    p = out_dir / "deck_values.json"
    if not p.exists():
        sys.exit("ERROR: deck_values.json not found. Run without --skip-analysis first.")
    with open(p) as f:
        return json.load(f)


def _fmt(v, decimals: int = 1, unit: str = "") -> str:
    if v is None or (isinstance(v, float) and not math.isfinite(v)):
        return r"\texttt{n/a}"
    s = f"{float(v):.{decimals}f}"
    return s + (r"\," + unit if unit else "")


def _fmt_int(v) -> str:
    if v is None:
        return r"\texttt{n/a}"
    return f"{int(v):,}"


def _sub(template: str, subs: dict[str, str]) -> str:
    for key, val in subs.items():
        template = template.replace(f"@{key}@", val)
    return template


def _read_tex(out_dir: pathlib.Path, tab_key: str, tab_map: dict) -> str:
    rel = tab_map.get(tab_key, f"tables/{tab_key}")
    p = out_dir / (rel + ".tex")
    return p.read_text() if p.exists() else f"% {tab_key} not found\n"


def _pmfmt(val, err, decimals: int = 1) -> str:
    """Format value±error as LaTeX math string (no outer $)."""
    if val is None or err is None:
        return r"\texttt{n/a}"
    if not (math.isfinite(float(val)) and math.isfinite(float(err))):
        return r"\texttt{n/a}"
    return f"{float(val):.{decimals}f}\\pm{float(err):.{decimals}f}"


# ── LaTeX template ────────────────────────────────────────────────────────────

_TEMPLATE = r"""% auto-generated by build_deck.py — do not edit by hand
% All numerical values sourced from deck_values.json
\documentclass[aspectratio=169,10pt]{beamer}

\usetheme{default}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage{amsmath}
\usepackage{xcolor}
\usepackage{siunitx}

\definecolor{shipblue}{RGB}{20,74,130}
\definecolor{warnorange}{RGB}{210,105,30}
\definecolor{okgreen}{RGB}{0,128,0}
\setbeamercolor{structure}{fg=shipblue}
\setbeamercolor{alerted text}{fg=warnorange}
\setbeamertemplate{navigation symbols}{}
\setbeamertemplate{footline}[frame number]

% ── macros sourced from deck_values.json ──────────────────────────────────────
\newcommand{\BarLen}{@BAR_LEN@}
\newcommand{\NEv}{@N_EV@}
\newcommand{\NPos}{@N_POS@}
% Material properties (Eljen EJ-204 datasheet Aug 2023 + Materials.cc)
\newcommand{\LamBulk}{@LAM_BULK@}
\newcommand{\ScintYield}{@SCINT_Y@\,$\gamma$/MeV}
\newcommand{\PeakEm}{@PEAK_EM@}
\newcommand{\RefrIdx}{@REFR_IDX@}
\newcommand{\DensityGcc}{@DENSITY@}
\newcommand{\TauRise}{@TAU_R@\,ns}
\newcommand{\TauDecay}{@TAU_D@\,ns}
% Mylar
\newcommand{\MylarR}{@MYLAR_R@}
\newcommand{\MylarSL}{@MYLAR_SL@}
\newcommand{\MylarSA}{@MYLAR_SA@}
% SiPM
\newcommand{\PDEpeak}{@PDE_PCT@\%}
\newcommand{\SiPMModel}{@SIPM_MODEL@}
\newcommand{\SiPMModelPDE}{@SIPM_MODEL_PDE@}
% Attenuation fit results
\newcommand{\LamSingleL}{\ensuremath{@LAM_SINGLE_L@}\,cm}
\newcommand{\LamSingleR}{\ensuremath{@LAM_SINGLE_R@}\,cm}
\newcommand{\ChiSingleL}{@CHI_SINGLE_L@}
\newcommand{\LamPromptL}{\ensuremath{@LAM_PROMPT_L@}\,cm}
\newcommand{\CFloorL}{\ensuremath{@C_FLOOR_L@}\,PE}
\newcommand{\ChiExpoffL}{@CHI_EXPOFF_L@}
\newcommand{\LamTailL}{\ensuremath{@LAM_TAIL_L@}\,cm}
\newcommand{\LamTailR}{\ensuremath{@LAM_TAIL_R@}\,cm}
\newcommand{\ChiTailL}{@CHI_TAIL_L@}
\newcommand{\DTail}{@D_TAIL@}
\newcommand{\NzeroSingleL}{@N0_SINGLE_L@}
\newcommand{\ActualNearL}{@NPE_NEAR_L@}
% EndTop comparison
\newcommand{\EndtopR}{@ENDTOP_R@}
\newcommand{\LamTailET}{\ensuremath{@LAM_TAIL_ET_L@}\,cm}
\newcommand{\NPETailMylar}{@NPE_TAIL_MYLAR@}
\newcommand{\NPETailET}{@NPE_TAIL_ET@}
% sigma_t
\newcommand{\SigmaAtMsixnine}{$@SG_M690@$\,ps}
\newcommand{\SigmaAtMfour}{$@SG_M400@$\,ps}
\newcommand{\SigmaAtZero}{$@SG_0@$\,ps}
\newcommand{\SigmaAtFour}{$@SG_P400@$\,ps}
\newcommand{\SigmaAtSixnine}{$@SG_P690@$\,ps}
\newcommand{\VeffFPT}{@V_FPT@\,mm/ns}
\newcommand{\VeffSUMfour}{@V_SUM4@\,mm/ns}
\newcommand{\VeffTfifty}{@V_T50@\,mm/ns}
% Photon budget
\newcommand{\BudgetEsc}{@PCT_ESC@\%}
\newcommand{\BudgetSiPM}{@PCT_SIPM@\%}
\newcommand{\BudgetDet}{@PCT_DET@\%}
% NPE at key positions
\newcommand{\NpeLeftZero}{@NPE_L_X0@}
\newcommand{\NpeRightZero}{@NPE_R_X0@}
\newcommand{\NpeLeftNear}{@NPE_L_690@}
\newcommand{\NpeRightNear}{@NPE_R_690@}

\title[End-only + Mylar EJ-204]{%
  End-only + Mylar-wrapped EJ-204 bar:\\
  Optical simulation study}
\subtitle{Geant4 11.4.0 / SSLG4-OPSim}
\author{R.\ R\'ios (ULS)}
\institute{SHiP Collaboration Meeting}
\date{2026-06-14}

\begin{document}

% ─── FRAME 1: Title ───────────────────────────────────────────────────────────
\begin{frame}
  \titlepage
\end{frame}

% ─── FRAME 2: Motivation & scope ─────────────────────────────────────────────
\begin{frame}{Motivation \& scope}
  \begin{columns}[T]
    \column{0.55\textwidth}
    \begin{itemize}
      \item \textbf{Deliberate simplification:} readout \emph{only} at the
            two ends ($\pm X$ faces); all other faces wrapped in Mylar.
      \item \textbf{Goals:}
        \begin{itemize}
          \item Isolate end-readout contribution.
          \item Characterize multi-component attenuation with Mylar.
          \item Benchmark the SUM4 timing estimator on a clean geometry.
        \end{itemize}
      \item \NPos\ beam positions ($x=-690\ldots+690$\,mm),
            \NEv\ $\mu^-$ events per position.
    \end{itemize}
    \column{0.43\textwidth}
    \begin{block}{This study}
      \textbf{End-only + Mylar} = extreme limit.
      Photons either exit to an end SiPM or are absorbed by Mylar
      after multiple reflections.
    \end{block}
    \begin{alertblock}{\small No TB counterpart}
      \small This configuration has \alert{no direct test-beam counterpart}
      (April-2026 TB used top readout + Tyvek).
    \end{alertblock}
    \begin{alertblock}{\small Electronic jitter not included}
      \small SPTR $\oplus$ FastIC jitter are post-processing steps,
      not folded into $\sigma_t$ shown here.
    \end{alertblock}
  \end{columns}
\end{frame}

% ─── FRAME 3: Geometry & simulation setup ─────────────────────────────────────
\begin{frame}{Geometry \& simulation setup}
  \begin{columns}[T]
    \column{0.55\textwidth}
    \begin{itemize}
      \item \textbf{Bar:} EJ-204 (OPSC-101),
            $\BarLen \times 60 \times 10$\,mm$^3$.
      \item \textbf{Longitudinal axis:} $X$ ($-700$ to $+700$\,mm).
      \item \textbf{End-left SiPMs} (IDs 0--7): $-X$ face.
            \textbf{End-right SiPMs} (IDs 8--15): $+X$ face.
      \item \textbf{Wrapping:} Mylar on $\pm Y$ and $\pm Z$ faces;
            $R=\MylarR$, specular lobe $=\MylarSL$,
            $\sigma_\alpha=\MylarSA^\circ$.
      \item \textbf{Readout:} SUM4 leading-edge at 4\,PE;
            groups $\{0\text{--}3\}/\{4\text{--}7\}$ (left),
            $\{8\text{--}11\}/\{12\text{--}15\}$ (right).
      \item \textbf{Estimator:}
            $\sigma_\mathrm{single} = \sigma_{LR}/\sqrt{2}$.
      \item \textbf{Beam:} $\mu^-$, 1\,GeV, normal incidence.
    \end{itemize}
    \column{0.43\textwidth}
    \begin{block}{Key parameters}
      \small
      \begin{tabular}{ll}
        \toprule
        Scint.~yield  & \ScintYield \\
        Emission peak & \PeakEm\,nm \\
        Bulk $\lambda$ & \LamBulk\,cm \\
        $n$           & \RefrIdx \\
        $\tau_r / \tau_d$ & \TauRise/\TauDecay \\
        Mylar $R$     & \MylarR \\
        \bottomrule
      \end{tabular}
    \end{block}
  \end{columns}
\end{frame}

% ─── FRAME 4: Photon count vs position ───────────────────────────────────────
\begin{frame}{Photon yield at ends vs.\ beam position}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_npe_vs_x.png}
    \column{0.33\textwidth}
    \begin{block}{Characteristic values}
      \small
      Near left end ($x=-690$\,mm):\\
      Left $\approx \NpeLeftNear$\,PE\\
      Right $\approx \NpeRightNear$\,PE
      \medskip

      Center ($x=0$):\\
      $\langle N^\mathrm{L}_\mathrm{pe}\rangle = \NpeLeftZero$\,PE\\
      $\langle N^\mathrm{R}_\mathrm{pe}\rangle = \NpeRightZero$\,PE
    \end{block}
    \begin{alertblock}{\small Observation}
      \small Log-scale reveals two regimes:
      prompt near-end region (steep)
      and recirculated floor ($\sim\NpeLeftZero$\,PE at center).
      Mylar recirculates but also absorbs.
    \end{alertblock}
  \end{columns}
\end{frame}

% ─── FRAME 5: Bulk vs effective attenuation ──────────────────────────────────
\begin{frame}{Two attenuation lengths: datasheet vs.\ system measurement}
  \begin{columns}[T]
    \column{0.50\textwidth}
    \begin{block}{$\lambda_\mathrm{bulk}$ = \LamBulk\,cm (datasheet)}
      \small
      \textbf{Material property.} Loaded as \texttt{ABSLENGTH} in
      \texttt{Materials.cc:99}.
      Probability of straight-line absorption in the plastic.
      \textbf{Knows nothing} about bar geometry or reflectors.
    \end{block}
    \begin{exampleblock}{$\lambda_\mathrm{eff}$ (what we fit)}
      \small
      \textbf{System observable}: slope of NPE vs.\ distance at end.
      Combines bulk absorption \emph{and} geometry \emph{and} reflection losses.
      Always $\lambda_\mathrm{eff} < \lambda_\mathrm{bulk}$.
      \textbf{These two quantities are not directly comparable.}
    \end{exampleblock}
    \column{0.48\textwidth}
    \begin{alertblock}{Why a single exponential fails}
      \small
      Three numbers that should agree if $N_0 e^{-d/\lambda}$ held:
      \begin{enumerate}
        \item Two-point ($d$=10\,mm $\to$ 700\,mm): $\lambda\approx19$\,cm
        \item Single-exp fit: $\lambda\approx\LamSingleL$, $N_0=\NzeroSingleL$\,PE
        \item Actual NPE at $d\approx0$: \ActualNearL\,PE
      \end{enumerate}
      Items (2) and (3) disagree by $\approx3.6\times$.
      $\chi^2/\mathrm{ndf} = \ChiSingleL$ confirms the model is wrong.
      \medskip

      \textbf{Physical reason:} the NPE profile has two components ---
      prompt (short-range) and recirculated floor (Mylar-sustained).
    \end{alertblock}
  \end{columns}
\end{frame}

% ─── FRAME 6: Attenuation curve (exp+offset fit) ─────────────────────────────
\begin{frame}{Attenuation: two-component fit and tail $\lambda$}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_attenuation.png}
    \column{0.33\textwidth}
    \begin{block}{Exp+offset model (left side)}
      \small
      $N(d) = A\,e^{-d/\lambda_p} + C$
      \medskip

      $\lambda_p = \LamPromptL$ (prompt)\\
      $C = \CFloorL$ (recirculated floor)\\
      $\chi^2/\mathrm{ndf} = \ChiExpoffL$
      \medskip

      Tail fit ($d>\DTail$\,cm):\\
      $\lambda_\mathrm{tail} = \LamTailL$
    \end{block}
    \begin{alertblock}{\small $\lambda_\mathrm{eff} \neq \lambda_\mathrm{bulk}$}
      \small \LamBulk\,cm (bulk) is the material ABSLENGTH.
      $\lambda_p\approx21$\,cm and $\lambda_\mathrm{tail}\approx42$\,cm
      are \emph{system} observables: dominated by
      geometry + Mylar losses, not bulk absorption.
    \end{alertblock}
  \end{columns}
\end{frame}

% ─── FRAME 7: Two-component fit diagnostics ──────────────────────────────────
\begin{frame}{Single-exp vs.\ exp+offset: model comparison}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_attenuation_twocomp.png}
    \column{0.33\textwidth}
    \begin{block}{Key diagnostics}
      \small
      \begin{tabular}{lrr}
        \toprule
        Model & $\lambda$ (cm) & $\chi^2/\mathrm{ndf}$ \\
        \midrule
        Single-exp  & \LamSingleL  & \ChiSingleL \\
        Exp+offset  & \LamPromptL  & \ChiExpoffL \\
        $\lambda_\mathrm{tail}$ ($d>\DTail$\,cm) & \LamTailL & \ChiTailL \\
        \bottomrule
      \end{tabular}
    \end{block}
    \begin{alertblock}{\small Inconsistency proof}
      \small
      Red star: actual NPE at $d\approx0$ is \ActualNearL\,PE.\\
      Single-exp $N_0 = \NzeroSingleL$\,PE (red dashed).\\
      Factor $\approx3.6$ inconsistency.\\
      Single-exp $\chi^2/\mathrm{ndf}=\ChiSingleL$ confirms failure.
    \end{alertblock}
  \end{columns}
\end{frame}

% ─── FRAME 8: Far-end light yield ────────────────────────────────────────────
\begin{frame}{Far-end light yield: where reflector quality matters}
  \begin{columns}[T]
    \column{0.55\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_far_end_yield.png}
    \column{0.43\textwidth}
    \begin{block}{Center-of-bar NPE ($|x|\leq100$\,mm)}
      \small
      \begin{tabular}{lrr}
        \toprule
        Config & $R$ & NPE \\
        \midrule
        End-only+Mylar & \MylarR & \NPETailMylar\,PE \\
        EndTop & \EndtopR & \NPETailET\,PE \\
        \bottomrule
      \end{tabular}
      \medskip

      Ratio EndTop/Mylar $\approx 2.5\times$.
    \end{block}
    \begin{alertblock}{\small Physical interpretation}
      \small
      Both configs see photons after $\geq60$\,cm propagation
      and many reflections.
      At $R=\MylarR$ (Mylar), each bounce absorbs 10\%: cumulative loss
      dominates. At $R=\EndtopR$, only 2\% per bounce.
      \medskip
      \textbf{Reflector quality, not $\lambda_\mathrm{bulk}$,
      controls the recirculated light level.}
    \end{alertblock}
  \end{columns}
\end{frame}

% ─── FRAME 9: Apples-to-apples comparison ────────────────────────────────────
\begin{frame}{Apples-to-apples: End-only+Mylar vs.\ EndTop}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_endtop_comparison.png}
    \column{0.33\textwidth}
    \begin{block}{Identical pipeline}
      \small
      Both datasets processed with the \textbf{same} end-SiPM-only
      selection, attenuation models, and tail-fit range.
    \end{block}
    \begin{block}{$\lambda_\mathrm{tail}$ comparison ($d>\DTail$\,cm)}
      \small
      \begin{tabular}{lr}
        \toprule
        Config & $\lambda_\mathrm{tail}$ \\
        \midrule
        End-only+Mylar & \LamTailL \\
        EndTop & \LamTailET \\
        \bottomrule
      \end{tabular}
      \medskip
      \textbf{Similar slope} --- dominated by geometry, not reflector type.
    \end{block}
    \begin{alertblock}{\small Conclusion}
      \small
      $\lambda_\mathrm{tail}$ does \emph{not} distinguish configs;
      the NPE \emph{amplitude} does.
      End-only+Mylar has $\approx2.5\times$ less light at center
      due to $R=\MylarR$ vs $R=\EndtopR$.
    \end{alertblock}
  \end{columns}
\end{frame}

% ─── FRAME 10: Timing distributions ──────────────────────────────────────────
\begin{frame}{Arrival-time distributions: FPT at representative positions}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_timing_histograms.png}
    \column{0.33\textwidth}
    \begin{block}{Distributions shown}
      \small
      First Photon Time (FPT) at End-Left and End-Right per event
      (\textbf{not normalized}).
      Positions: $x\in\{-690,-400,0,+400,+690\}$\,mm.
      $N = \NEv$ events per position.
    \end{block}
    \begin{alertblock}{\small Key feature}
      \small Distribution shifts to larger $t$ and broadens as beam
      moves away from the respective end --- longer propagation
      path and fewer photons (statistical minimum effect).
    \end{alertblock}
  \end{columns}
\end{frame}

% ─── FRAME 11: FPT vs t50 ────────────────────────────────────────────────────
\begin{frame}{FPT vs.\ $t_{50}$: comparing timing estimators}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_fpt_vs_t50.png}
    \column{0.33\textwidth}
    \begin{block}{FPT vs.\ $t_{50}$}
      \small
      FPT: minimum of photon arrival times per event.\\
      $t_{50}$: median --- less sensitive to the
      $N$-dependent statistical minimum.
      \medskip
      $t_{50}$ systematically later than FPT;
      offset grows with distance.
    \end{block}
    \begin{alertblock}{\small $v_\mathrm{eff}$ bias}
      \small
      FPT $v_\mathrm{eff} = \VeffFPT$ (apparent, biased
      by $N$-dependent statistical minimum).\\
      SUM4 $\Delta t$ gives $v_\mathrm{eff} = \VeffSUMfour$ (robust).
    \end{alertblock}
  \end{columns}
\end{frame}

% ─── FRAME 12: Mean arrival time + v_eff ─────────────────────────────────────
\begin{frame}{Mean arrival time and effective velocity}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_mean_arrival_time.png}
    \column{0.33\textwidth}
    \begin{block}{$v_\mathrm{eff}$ summary}
      \small
      \begin{tabular}{ll}
        \toprule
        Estimator & $v_\mathrm{eff}$ \\
        \midrule
        SUM4 $\Delta t$ & \VeffSUMfour \\
        FPT slope & \VeffFPT \\
        $t_{50}$ slope & \VeffTfifty \\
        \bottomrule
      \end{tabular}
    \end{block}
    \begin{alertblock}{\small FPT anomaly}
      \small
      $v_\mathrm{eff}^\mathrm{FPT} > c/n$
      ($c/n \approx 190$\,mm/ns for $n=\RefrIdx$).
      Artifact: FPT = statistical minimum of $N$ photon
      arrival times; fewer photons at large $d$ $\to$ earlier
      FPT bias.
    \end{alertblock}
  \end{columns}
\end{frame}

% ─── FRAME 13: sigma_t ────────────────────────────────────────────────────────
\begin{frame}{Intrinsic timing resolution $\sigma_t(x)$}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_sigma_t.png}
    \column{0.33\textwidth}
    \begin{block}{Key values}
      \small
      \begin{tabular}{ll}
        \toprule
        Position & $\sigma_\mathrm{single}$ \\
        \midrule
        $x=-690$\,mm & \SigmaAtMsixnine \\
        $x=-400$\,mm & \SigmaAtMfour \\
        $x=0$        & \SigmaAtZero \\
        $x=+400$\,mm & \SigmaAtFour \\
        $x=+690$\,mm & \SigmaAtSixnine \\
        \bottomrule
      \end{tabular}
    \end{block}
    \begin{alertblock}{\small Intrinsic only}
      \small
      $\sigma_t$ = optical + SUM4 estimator.
      \alert{SPTR ($\approx106$\,ps) and FastIC ($\approx10$\,ps)
      not folded in.}
    \end{alertblock}
  \end{columns}
\end{frame}

% ─── FRAME 14: Photon budget ──────────────────────────────────────────────────
\begin{frame}{Photon budget --- End-only + Mylar}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_photon_budget.png}
    \column{0.33\textwidth}
    \begin{block}{Fractions}
      \small
      \begin{tabular}{lr}
        \toprule
        Fate & Fraction \\
        \midrule
        Mylar-absorbed & $\approx\BudgetEsc$ \\
        Enters SiPM & \BudgetSiPM \\
        Detected (PDE) & \BudgetDet \\
        \bottomrule
      \end{tabular}
    \end{block}
    \begin{alertblock}{\small Mylar loss dominates}
      \small
      Each Mylar bounce: $(1-R)=\MylarR$ absorbed.
      $\Rightarrow$ Over many bounces in a thin bar,
      cumulative loss $\gg$ bulk loss.
      This explains $\lambda_p \approx 21$\,cm $\ll$ \LamBulk\,cm.
    \end{alertblock}
  \end{columns}
\end{frame}

% ─── FRAME 15: Summary ────────────────────────────────────────────────────────
\begin{frame}{Summary}
  \begin{columns}[T]
    \column{0.55\textwidth}
    \begin{block}{Key results}
      \begin{itemize}
        \item \textbf{Two attenuation lengths:}
              $\lambda_\mathrm{bulk}=\LamBulk$\,cm (ABSLENGTH, material property);
              $\lambda_p\approx21$\,cm (prompt system component);
              $\lambda_\mathrm{tail}\approx\LamTailL$ (tail, comparable metric).
              These are \emph{not} the same quantity.
        \item \textbf{Single-exp fails:}
              $\chi^2/\mathrm{ndf}=\ChiSingleL$;
              $N_0$ inconsistency factor $\approx3.6\times$.
              Two-component model required.
        \item \textbf{Reflector $R$ controls tail NPE:}
              End-only+Mylar ($R=\MylarR$): \NPETailMylar\,PE at center;
              EndTop ($R=\EndtopR$): \NPETailET\,PE.
              Ratio $\approx2.5\times$.
        \item $\lambda_\mathrm{tail}$ is \emph{equal} in both configs ---
              the NPE amplitude is the distinguishing observable.
        \item $\sigma_t^\mathrm{intr.}$: \SigmaAtZero\ (center)
              to \SigmaAtMsixnine\ (ends) --- intrinsic only.
      \end{itemize}
    \end{block}
    \column{0.43\textwidth}
    \begin{block}{Next steps}
      \begin{enumerate}
        \item Fold in electronic jitter:
              $\sigma_\mathrm{SPTR}=106$\,ps
              $\oplus\,\sigma_\mathrm{FastIC}=10$\,ps.
        \item Leading-edge time-walk correction.
        \item Scan Mylar $R\in[0.85,0.95]$ to map
              NPE yield vs.\ reflector quality.
        \item Scan with Tyvek for direct comparison
              to April-2026 TB configuration.
      \end{enumerate}
    \end{block}
  \end{columns}
\end{frame}

% ════════════════════════════════════════════════════════════════════════════════
% APPENDIX
% ════════════════════════════════════════════════════════════════════════════════
\appendix

\begin{frame}{Appendix A: simulation parameters}
  \tiny
  @TAB_PARAMS@
\end{frame}

\begin{frame}{Appendix B: $\sigma_t$ per-position summary}
  \centering\small
  @TAB_SIG@
  \par\medskip
  \small All values in ps.
  $\sigma_\mathrm{single}=\sigma_{LR}/\sqrt{2}$ from SUM4 leading-edge
  core Gaussian fit.
\end{frame}

\begin{frame}{Appendix C: attenuation fit details (three models)}
  \centering\tiny
  @TAB_ATT@
  \par\medskip
  \small
  All fits weighted by per-point SEM.
  Errors from covariance matrix, scaled by $\sqrt{\chi^2/\mathrm{ndf}}$ when $>1$.
  Tail fit: $d>\DTail$\,cm only.
\end{frame}

\begin{frame}{Appendix D: method \& caveats}
  \small
  \begin{itemize}
    \item \textbf{Geometry:} Bar $1400\times60\times10$\,mm$^3$; long axis $X$.
          End SiPMs on $\pm X$; Mylar on $\pm Y,\pm Z$.
    \item \textbf{SUM4 trigger:} leading-edge at 4\,PE.
          Groups $\{0\text{--}3\}/\{4\text{--}7\}$ (left);
          $\{8\text{--}11\}/\{12\text{--}15\}$ (right).
    \item \textbf{$\sigma_t$ is intrinsic only:} optical + estimator;
          SPTR ($\approx106$\,ps) and FastIC ($\approx10$\,ps)
          not folded in.
    \item \textbf{SiPM naming:} \texttt{\SiPMModelPDE}
          is used \emph{only} for the PDE curve;
          physical device is the single-element \textbf{\SiPMModel}.
    \item \textbf{No TB counterpart:} April-2026 TB used top readout
          + Tyvek wrapping $\neq$ end-only + Mylar.
    \item \textbf{Longitudinal axis $= X$} (not $Z$ or $Y$).
    \item \textbf{Yield:} OPSC-101 loaded with \ScintYield\ in
          \texttt{Materials.cc:100} --- matches Eljen EJ-204 datasheet Aug~2023.
    \item \textbf{EndTop reference:} EXEC\_07, \NEv\ events/position,
          same 31 positions. Side reflectors $R=\EndtopR$ (BarSkinReflector),
          NOT Mylar.
  \end{itemize}
\end{frame}

\end{document}
"""


def build_tex(out_dir: pathlib.Path, v: dict) -> str:
    tab_map  = v.get("tables", {})
    sigma_at = v.get("sigma_t_at_key_positions", {})

    def sg(xkey: str) -> str:
        d = sigma_at.get(str(xkey), {})
        s = d.get("sigma_single_ps")
        e = d.get("sigma_single_err_ps")
        if s is None:
            return r"\texttt{n/a}"
        return f"{float(s):.0f}\\pm{float(e):.0f}"

    n_gen  = v.get("photon_budget_generated") or 0
    n_esc  = v.get("photon_budget_escaped")   or 0
    n_sipm = v.get("photon_budget_sipm_entering") or 0
    n_det  = v.get("photon_budget_detected")  or 0

    def pct(num):
        if n_gen == 0:
            return r"\texttt{n/a}"
        return f"{float(num) / float(n_gen) * 100:.2f}"

    # Attenuation fit values
    att_l = v.get("att_left", {})
    att_r = v.get("att_right", {})

    def _pm(key_val, key_err, d, decimals=1):
        val = d.get(key_val)
        err = d.get(key_err)
        return _pmfmt(val, err, decimals)

    # EndTop
    et    = v.get("endtop", {})
    et_av = et.get("available", False)
    et_r  = et.get("reflector_R", 0.98)
    et_fl = et.get("fit_left", {})
    lam_tail_et_str = (_pm("tail_lam_cm", "tail_lam_err", et_fl)
                       if et_av else r"\texttt{n/a}")
    npe_tail_et_str = (_fmt(et.get("npe_left_at_x0"), 1)
                       if et_av else r"\texttt{n/a}")

    subs = {
        "BAR_LEN":      _fmt(v.get("bar_length_mm"), 0),
        "N_EV":         _fmt_int(v.get("n_events_per_position")),
        "N_POS":        _fmt_int(v.get("n_positions")),
        "LAM_BULK":     _fmt(v.get("lambda_bulk_cm"), 0),
        "SCINT_Y":      _fmt_int(v.get("scint_yield_per_MeV")),
        "PEAK_EM":      _fmt(v.get("peak_emission_nm"), 0),
        "REFR_IDX":     _fmt(v.get("refractive_index"), 2),
        "DENSITY":      _fmt(v.get("density_gcc"), 3),
        "TAU_R":        _fmt(v.get("tau_rise_ns"), 1),
        "TAU_D":        _fmt(v.get("tau_decay_ns"), 1),
        "MYLAR_R":      _fmt(v.get("mylar_reflectivity"), 2),
        "MYLAR_SL":     _fmt(v.get("mylar_specular_lobe"), 1),
        "MYLAR_SA":     _fmt(v.get("mylar_sigma_alpha_deg"), 1),
        "PDE_PCT":      _fmt(v.get("pde_peak_frac", 0) * 100, 0),
        "SIPM_MODEL":   str(v.get("sipm_model", "AFBR-S4N66P014M")),
        "SIPM_MODEL_PDE": str(v.get("sipm_model_pde_curve", "AFBR-S4N66P024M")),
        # Attenuation: single-exp (left side)
        "LAM_SINGLE_L": _pm("single_lam_cm", "single_lam_err", att_l),
        "LAM_SINGLE_R": _pm("single_lam_cm", "single_lam_err", att_r),
        "CHI_SINGLE_L": (_fmt(att_l.get("single_chi2ndf"), 0)
                         if att_l.get("single_chi2ndf") else r"\texttt{n/a}"),
        "N0_SINGLE_L":  (_fmt(att_l.get("single_n0"), 0)
                         if att_l.get("single_n0") else r"\texttt{n/a}"),
        # Attenuation: exp+offset (left)
        "LAM_PROMPT_L": _pm("expoff_lam_cm", "expoff_lam_err", att_l),
        "C_FLOOR_L":    _pm("expoff_C", "expoff_C_err", att_l),
        "CHI_EXPOFF_L": (_fmt(att_l.get("expoff_chi2ndf"), 0)
                         if att_l.get("expoff_chi2ndf") else r"\texttt{n/a}"),
        # Attenuation: lambda_tail
        "LAM_TAIL_L":   _pm("tail_lam_cm", "tail_lam_err", att_l),
        "LAM_TAIL_R":   _pm("tail_lam_cm", "tail_lam_err", att_r),
        "CHI_TAIL_L":   (_fmt(att_l.get("tail_chi2ndf"), 1)
                         if att_l.get("tail_chi2ndf") else r"\texttt{n/a}"),
        "D_TAIL":       str(int(v.get("att_tail_dmin_cm", 40))),
        # Actual near-end NPE (d≈0)
        "NPE_NEAR_L":   _fmt(v.get("npe_left_at_xm690"), 0),
        # EndTop
        "ENDTOP_R":     _fmt(et_r, 2),
        "LAM_TAIL_ET_L": lam_tail_et_str,
        "NPE_TAIL_MYLAR": _fmt(v.get("npe_left_at_x0"), 1),
        "NPE_TAIL_ET":    npe_tail_et_str,
        # sigma_t
        "SG_M690":  sg("-690"),
        "SG_M400":  sg("-400"),
        "SG_0":     sg("0"),
        "SG_P400":  sg("400"),
        "SG_P690":  sg("690"),
        # v_eff
        "V_FPT":  _fmt(v.get("v_eff_fpt_mm_ns"), 1),
        "V_SUM4": _fmt(v.get("v_eff_sum4_mm_ns"), 1),
        "V_T50":  _fmt(v.get("v_eff_t50_mm_ns"), 1),
        # Photon budget
        "PCT_ESC":  pct(n_esc),
        "PCT_SIPM": pct(n_sipm),
        "PCT_DET":  pct(n_det),
        # NPE at key positions
        "NPE_L_X0":  _fmt(v.get("npe_left_at_x0"), 1),
        "NPE_R_X0":  _fmt(v.get("npe_right_at_x0"), 1),
        "NPE_L_690": _fmt(v.get("npe_left_at_xm690"), 0),
        "NPE_R_690": _fmt(v.get("npe_right_at_x690"), 0),
        # Tables
        "TAB_PARAMS": _read_tex(out_dir, "tab_sim_params", tab_map),
        "TAB_SIG":    _read_tex(out_dir, "tab_sigma_t", tab_map),
        "TAB_ATT":    _read_tex(out_dir, "tab_attenuation_fits", tab_map),
    }
    return _sub(_TEMPLATE, subs)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data-dir",
                    default="/home/reriosto/SHiP/t0minidaq/endonly_mylar_20260614",
                    type=pathlib.Path)
    ap.add_argument("--out-dir", default=HERE, type=pathlib.Path)
    ap.add_argument("--skip-analysis", action="store_true")
    ap.add_argument("--no-compile",    action="store_true")
    args = ap.parse_args()

    out_dir = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    if not args.skip_analysis:
        _run_analysis(args.data_dir, out_dir)

    v   = _load_values(out_dir)
    tex = build_tex(out_dir, v)

    tex_path = out_dir / "main.tex"
    tex_path.write_text(tex)
    print(f"Written: {tex_path}")

    if args.no_compile:
        print("Skipping LaTeX compilation (--no-compile).")
        return

    pdf_path = out_dir / "main.pdf"
    env = dict(os.environ)

    latexmk = shutil.which("latexmk")
    if latexmk:
        cmd = [latexmk, "-pdf", "-interaction=nonstopmode",
               f"-output-directory={out_dir}", str(tex_path)]
        r = subprocess.run(cmd, cwd=str(out_dir), capture_output=True, text=True, env=env)
        if r.returncode != 0:
            print("latexmk stderr:", r.stderr[-3000:])
        success = r.returncode == 0
    else:
        r = None
        for _ in range(2):
            r = subprocess.run(
                ["pdflatex", "-interaction=nonstopmode",
                 "-output-directory", str(out_dir), str(tex_path)],
                cwd=str(out_dir), capture_output=True, text=True, env=env,
            )
        success = (r is not None and r.returncode == 0)
        if not success and r:
            print("pdflatex stderr:", r.stderr[-2000:])

    if success and pdf_path.exists():
        try:
            pg_info = subprocess.run(["pdfinfo", str(pdf_path)],
                                     capture_output=True, text=True)
            pages = next(
                (ln.split(":")[1].strip()
                 for ln in pg_info.stdout.splitlines()
                 if ln.startswith("Pages:")), "?"
            )
        except Exception:
            pages = "?"
        print(f"PDF compiled successfully: {pdf_path.name}  ({pages} pages)")
    else:
        print("WARNING: PDF compilation may have failed. Check main.log for details.")


if __name__ == "__main__":
    main()
