#!/usr/bin/env python3.12
"""build_beamer_20.py — EXEC_20 Beamer: END-only baseline + TOP contribution."""
import json, math
from pathlib import Path

OUT_DIR    = "/home/reriosto/SHiP/analysis_core/out/EXEC_20"
BEAMER_DIR = Path(__file__).parent
FIG_DIR    = "/mnt/d/SHiP/analysis_core/out/EXEC_20"

rj = json.loads(Path(f"{OUT_DIR}/results_exec20.json").read_text())

def g(k): v=rj.get(k,"---"); 
def G(k):
    v=rj.get(k,"---")
    try:
        fv=float(v)
        return "---" if math.isnan(fv) else f"{fv:.1f}"
    except:
        return str(v)

TOKENS = {
    "__FIGDIR__":         FIG_DIR,
    "T1_SIG_END_X0":      G("T1_sigma_END_tavg_x0_ps"),
    "T1_SIG_END_XM690":   G("T1_sigma_END_tavg_xm690_ps"),
    "T1_VEFF":            G("T1_v_eff_cm_ns").replace("-",""),  # magnitude
    "T3_IMP_X0":          G("T3_improvement_x0_pct"),
    "T3_IMP_XM690":       G("T3_improvement_xm690_pct"),
    "T3_IMP_MEAN":        G("T3_improvement_mean_pct"),
    "T3_SIG_TOP_X0":      G("T3_sigma_top_x0_ps"),
    "T3_SIG_ENDTOP_X0":   G("T3_sigma_endtop_x0_ps"),
    "T5_DYN4":            G("T5_dynamic4_sigma_ps"),
    "T5_CL4":             G("T5_cluster4_sigma_ps"),
    "CAVEAT_TEX":         "Intrinseco/PDE only (sin SPTR/FastIC). OPSC-101/EJ-204. sqrt\\_n binning, walk-corr.",
}

TEX = r"""% EXEC_20 — Linea base END-only y aporte del TOP (intrinseco)
% Generated by build_beamer_20.py — DO NOT EDIT MANUALLY
\documentclass[aspectratio=169,9pt]{beamer}
\usetheme{Madrid}\usecolortheme{default}
\setbeamertemplate{navigation symbols}{}
\setbeamerfont{frametitle}{size=\normalsize,series=\bfseries}
\usepackage{fontspec}
\setsansfont{DejaVu Sans}[Scale=0.93]
\setmonofont{DejaVu Sans Mono}[Scale=0.85]
\usepackage{graphicx,booktabs,xcolor,amssymb}
\graphicspath{{__FIGDIR__/}}
\definecolor{passgreen}{HTML}{2ca02c}
\definecolor{decgold}{HTML}{e67e00}
\title[EXEC\_20 --- END-only + TOP (intrinseco)]{%
  EXEC\_20 --- Linea base END-only y aporte del TOP\\
  \large Intrinseco/PDE only --- EJ-204 EndTop}
\author[R.~Rios Torres]{Rene Rios Torres (ULS / SHiP)}
\institute[SHiP Timing]{SHiP Collaboration --- Timing Detector Group}
\date{20 junio 2026}
\begin{document}
\begin{frame}[plain]\titlepage\end{frame}
\begin{frame}{Contenidos}\tableofcontents\end{frame}

\section{Reorientacion: intrinseco/PDE only}

\begin{frame}{Reorientacion de EXEC\_20 (decision Rene)}
  \begin{block}{Enfoque}
    \textbf{Solo nivel intrinseco/PDE.} SPTR y FastIC quedan en un \textit{apendice diferido}.\\
    La pregunta de fisica es: \textbf{cuanto aporta el TOP sobre la linea base END-only de dos extremos?}
  \end{block}
  \begin{itemize}
    \item Gerardo, con lectura END de dos extremos, obtiene mejores metricas que las nuestras
    \item Lo que medimos = la mejora marginal de instrumentar el TOP (no si el TOP cumple un requisito)
    \item Binning canonico: sqrt\_n (resuelve artefacto FD de EXEC\_18)
    \item Walk correction: parametrico $\alpha+\beta/\sqrt{s}$
    \item $\sigma_\text{int}$ ya incluye jitter SiPMSD (= 0 ns en ambas campanas)
  \end{itemize}
\end{frame}

\section{T1: Linea base END-only}

\begin{frame}{T1 --- Linea base END-only (t\_avg de dos extremos)}
  \begin{columns}[T]
    \begin{column}{0.62\textwidth}
      \includegraphics[width=\textwidth,height=0.58\textheight,keepaspectratio]{T1/T1_end_baseline}
    \end{column}
    \begin{column}{0.37\textwidth}\small
      Estimador: $t_\text{avg} = \frac{t_L+t_R}{2}$\\
      $t_L/t_R$ = primer foton en stream mergeado de los 8 SiPMs END por cara\\[0.4em]
      @ $x=0$: $\sigma_\text{END}=$ T1_SIG_END_X0\,ps\\
      \quad (solo 0.37\,PE/ev por cara!)\\[0.3em]
      @ $x=-690$: $\sigma_\text{END}=$ T1_SIG_END_XM690\,ps\\
      \quad (END\_L ve 903\,PE/ev, END\_R ve 0.07)\\[0.3em]
      $v_\text{eff}=$ T1_VEFF\,cm/ns (slope $\langle\Delta t\rangle(x)$)\\[0.3em]
      \textit{$t_\text{avg}$ requiere ambos extremos; pierde eficiencia cerca de los extremos}
    \end{column}
  \end{columns}
\end{frame}

\section{T2: Scan END-only nuevo}

\begin{frame}{T2 --- Scan END-only nuevo (500 ev/pos): hallazgo optico}
  \begin{block}{Hallazgo: TOP absorbe luz que iria al END}
    Scan endonly (sin TOP): $\langle N_\text{pe}\rangle_\text{END\_L}(x=0) = 0.74$\,PE/ev\\
    EndTop data (con TOP SiPMs): $\langle N_\text{pe}\rangle_\text{END\_L}(x=0) = 0.37$\,PE/ev\\
    \textbf{Factor $\approx 2\times$}: los SiPMs TOP absorben fotones que habrian llegado al END
  \end{block}
  \begin{itemize}\small
    \item Scan: 31 posiciones, 500\,ev/pos, build \texttt{feat/endonly-mylar} (R=0.90 vs R=0.95 EndTop)
    \item T2a: PASS --- OPSC-101, 16 SiPMs [0,15], sin TOP hits, reflector skin fix presente
    \item $\sigma_\text{END}(x=-690)$: endonly=533\,ps vs EndTop-derivado=609\,ps\\
          Endonly recibe mas luz (menos absorcion) pero 10$\times$ menos eventos
    \item @ $x=0$: endonly=1678\,ps vs 882\,ps (estadistica insuficiente con 500\,ev)
    \item \textbf{Diferencia metodologica con Gerardo} (a confirmar): si su medida usa mas eventos o un estimador diferente
  \end{itemize}
\end{frame}

\section{T3: Aporte del TOP}

\begin{frame}{T3 --- Aporte del TOP sobre END-only (la pregunta central)}
  \includegraphics[width=\textwidth,height=0.60\textheight,keepaspectratio]{T3/T3_top_contribution}
  \begin{itemize}\small
    \item \textbf{Mejora @ $x=0$: T3_IMP_X0\,\%} (END=T1_SIG_END_X0\,ps $\to$ TOP=T3_SIG_TOP_X0\,ps)
    \item \textbf{Mejora media (31 pos): T3_IMP_MEAN\,\%}
    \item $\sigma_\text{EndTop(GLS)}>$ $\sigma_\text{TOP}$ por covarianza positiva: TOP domina; combinacion optima = TOP solo
    \item Fisica: TOP ayuda \textit{mas} al centro (END casi ciego) y \textit{menos} en extremos (END excelente ahi)
  \end{itemize}
\end{frame}

\section{T4 + T5: Reconciliacion y canonicos}

\begin{frame}{T4/T5 --- Reconciliacion con Gerardo + estimadores canonicos}
  \begin{columns}[T]
    \begin{column}{0.50\textwidth}
      \textbf{Por que nuestra END-only es peor:}
      \begin{itemize}\small
        \item $t_\text{avg}$ requiere AMBOS extremos: raro en $x=\pm690$ (END opuesto = 0.07\,PE/ev)
        \item @ $x=-690$: END\_L ve 903\,PE/ev pero END\_R ve 0.07 $\to$ eficiencia $\approx7\%$
        \item Si Gerardo usa la MEJOR cara: $\sigma_\text{END\_L}(x=-690)\approx30.5$\,ps (EXEC-19 canonico)
        \item Estimador de Gerardo a \textcolor{decgold}{\textbf{confirmar}} (canales, combinacion, posicion)
      \end{itemize}
    \end{column}
    \begin{column}{0.49\textwidth}
      \textbf{Fix EXEC-18 (T5): binning sqrt\_n}
      \begin{itemize}\small
        \item dynamic nearest-4: T5_DYN4\,ps
        \item id//4 fijo:         T5_CL4\,ps
        \item dynamic $\leq$ cluster (mas luz = mejor $\sigma$)\\
              \textcolor{passgreen}{\checkmark} artefacto FD resuelto
      \end{itemize}
      \vspace{0.4em}
      \textbf{Electrónica diferida (decision Rene):}\\
      SPTR, FastIC, $\sigma_\text{tot}$ fuera del headline.\\
      Ver EXEC-19 para numeros completos.
    \end{column}
  \end{columns}
  {\tiny \textit{CAVEAT_TEX}}
\end{frame}

\section{Resumen}

\begin{frame}{Resumen EXEC\_20}
  \begin{columns}[T]
    \begin{column}{0.48\textwidth}
      \textbf{Linea base END-only (intrinseco):}
      \begin{itemize}\small
        \item @ $x=0$: $\sigma_\text{END}=$ T1_SIG_END_X0\,ps (pocos fotones)
        \item @ $x=-690$: $\sigma_\text{END}=$ T1_SIG_END_XM690\,ps
        \item $v_\text{eff}=$ T1_VEFF\,cm/ns
        \item Hallazgo scan endonly: TOP absorbe $\approx 50\%$ de la luz que llegaria al END
      \end{itemize}
      \vspace{0.2em}
      \textbf{Aporte del TOP (intrinseco):}
      \begin{itemize}\small
        \item Mejora @ $x=0$: \textcolor{passgreen}{\textbf{T3_IMP_X0\,\%}}
        \item Mejora media: \textcolor{passgreen}{\textbf{T3_IMP_MEAN\,\%}}
        \item Estrategia optima: \textbf{usar TOP solo} (correlacion positiva degrada la combinacion GLS)
      \end{itemize}
    \end{column}
    \begin{column}{0.51\textwidth}
      \textbf{\textcolor{decgold}{Pendiente Gerardo:}}
      \begin{itemize}\small
        \item Confirmar estimador END-only exacto (para comparacion apples-to-apples)
        \item Topologia SUM TOP: dynamic T5_DYN4\,ps vs id//4 T5_CL4\,ps
        \item Decision clustering ya no cambia el mensaje principal (TOP $\approx$70-76\,ps)
      \end{itemize}
      \vspace{0.2em}
      \textbf{Proximos pasos:}
      \begin{itemize}\small
        \item EXEC-02b: plegado con SPTR/FastIC (diferido)
        \item Comparacion TB DESY (Mylar vs Tyvek, diferente wrapping)
        \item EJ-230 EndTop pendiente (cierre 2$\times$2)
      \end{itemize}
    \end{column}
  \end{columns}
  {\tiny \textit{CAVEAT_TEX}}
\end{frame}

\end{document}
"""

out = TEX
for k, v in TOKENS.items():
    out = out.replace(k, str(v))

out_tex = BEAMER_DIR / "EXEC_20_endonly_top.tex"
out_tex.write_text(out)
print(f"Written: {out_tex}")
