#!/usr/bin/env python3.12
"""build_beamer_21.py — EXEC_21 Beamer: END light collection diagnosis."""
import json, math
from pathlib import Path

OUT_DIR    = "/home/reriosto/SHiP/analysis_core/out/EXEC_21"
BEAMER_DIR = Path(__file__).parent
FIG_DIR    = "/mnt/d/SHiP/analysis_core/out/EXEC_21"

rj = json.loads(Path(f"{OUT_DIR}/results_exec21.json").read_text())

def G(k, d=1):
    v = rj.get(k, "---")
    try: fv = float(v); return "---" if math.isnan(fv) else f"{fv:.{d}f}"
    except: return str(v)

TOKENS = {
    "__FIGDIR__":           FIG_DIR,
    "D1_SIGMA_X0":          G("D1_sigma_END_x0_ps"),
    "D1_N_BROKEN":          str(rj.get("D1_n_broken","?")),
    "D2_NPE_OBS":           G("D2_npe_obs_x0", 2),
    "D2_NPE_METAL":         G("D2_npe_expected_metallic", 3),
    "D2_NPE_TIR":           G("D2_npe_expected_tir", 0),
    "D2_FACTOR":            G("D2_deficit_factor", 0),
    "D4_R1":                G("D4_even_R1", 2),
    "D5_NL_X0":             G("D5_npe_L_x0_tir", 1),
    "D5_SIG_XM690":         G("D5_sigma_END_xm690_tir_ps", 0),
    "D5_SIG_X0":            G("D5_sigma_END_x0_tir_ps", 0),
    "D5_PROMPT":            G("D5_bimodal_xm690_prompt_pct", 1),
    "D6_SIG_TOP":           G("D6_sig_TOP_x0", 1),
    "D6_SIG_INVVAR":        G("D6_sig_invvar_FIXED_ps", 1),
    "CAVEAT":               "Intrinseco/PDE. EJ-204 OPSC-101. sqrt\\_n, walk-corr. Diagnosis EXEC-21.",
}

TEX = r"""% EXEC_21 — Diagnosis END light collection
% Generated by build_beamer_21.py
\documentclass[aspectratio=169,9pt]{beamer}
\usetheme{Madrid}\usecolortheme{default}
\setbeamertemplate{navigation symbols}{}
\setbeamerfont{frametitle}{size=\normalsize,series=\bfseries}
\usepackage{fontspec}
\setsansfont{DejaVu Sans}[Scale=0.93]
\setmonofont{DejaVu Sans Mono}[Scale=0.85]
\usepackage{graphicx,booktabs,xcolor,amssymb}
\graphicspath{{__FIGDIR__/}}
\definecolor{brokenred}{HTML}{d62728}
\definecolor{okgreen}{HTML}{2ca02c}
\definecolor{warngold}{HTML}{e67e00}
\title[EXEC\_21 --- Diagnostico coleccion luz END]{%
  EXEC\_21 --- Diagnostico de la coleccion de luz del END\\
  \large Por que la sim sub-colecta? (Falsado con datos reales)}
\author[R.~Rios Torres]{Rene Rios Torres (ULS / SHiP)}
\institute[SHiP Timing]{SHiP Collaboration --- Timing Detector Group}
\date{21 junio 2026}
\begin{document}
\begin{frame}[plain]\titlepage\end{frame}
\begin{frame}{Contenidos}\tableofcontents\end{frame}

\section{D1: Gate de falsacion}

\begin{frame}{D1 --- Gate de falsacion: sim vs datos reales}
  \includegraphics[width=\textwidth,height=0.58\textheight,keepaspectratio]{D1/D1_falsification_gate}
  \begin{itemize}\small
    \item \textcolor{brokenred}{\textbf{BROKEN: D1_N_BROKEN/31 posiciones}} tienen $\sigma_\text{END}^\text{sim}>\sigma_\text{real}$ (fisicamente imposible)
    \item $\sigma_\text{END}(x=0)=$ D1_SIGMA_X0\,ps $\gg$ real single-filtered 250\,ps
    \item Incluso $x=-690$ (near-end): $\sigma=609$\,ps $>$ 250\,ps $\to$ BROKEN
    \item \textit{El intrinseco de la sim no puede superar al medido real (que incluye electronica)}
  \end{itemize}
\end{frame}

\section{D2: Presupuesto de fotones}

\begin{frame}{D2 --- Presupuesto de fotones: la sim ES consistente, pero MALA fisica}
  \includegraphics[width=\textwidth,height=0.55\textheight,keepaspectratio]{D2/D2_photon_budget}
  \begin{columns}[T]
    \begin{column}{0.5\textwidth}\small
      \textbf{Con modelo metalico (actual, R=0.98):}
      \begin{itemize}
        \item 164 rebotes promedio hasta END
        \item $0.98^{164} \times e^{-328\,\text{cm}/160\,\text{cm}} = 0.46\%$
        \item Esperado: D2_NPE_METAL\,PE/ev --- observado: D2_NPE_OBS\,PE/ev $\approx$ consistente
      \end{itemize}
    \end{column}
    \begin{column}{0.49\textwidth}\small
      \textbf{Con TIR (dielectric\_dielectric):}
      \begin{itemize}
        \item TIR: 77\% rebotes sin perdida
        \item Esperado: \textbf{D2_NPE_TIR\,PE/ev} (factor D2_FACTOR$\times$)
        \item Real detector: $\approx40$\,PE $\to$ entre los dos modelos
      \end{itemize}
    \end{column}
  \end{columns}
  \vspace{0.2em}
  \textbf{Incluso R=1.0 metalico da solo D4_R1\,PE} (ABSLENGTH mata en el camino largo).
\end{frame}

\section{D3: Historia de fotones}

\begin{frame}{D3 --- Historia de fotones desde distribucion temporal}
  \includegraphics[width=\textwidth,height=0.60\textheight,keepaspectratio]{D3/D3_time_distributions}
  \begin{itemize}\small
    \item Near-end ($x=-690$): 47.5\% prompt + 31\% tardios $\to$ mezcla directo + guiado
    \item Centro ($x=0$): 100\% tardios $>3$\,ns (fotones directos tambien llegan tarde: $t_\text{direct}=3.7$\,ns)
    \item Si el guiado funcionara: bump tardio claro en END a distancia $\to$ \textbf{ausente en sim}
  \end{itemize}
\end{frame}

\section{D4: Causa raiz}

\begin{frame}{D4 --- Causa raiz: dielectric\_metal elimina TIR}
  \includegraphics[width=\textwidth,height=0.58\textheight,keepaspectratio]{D4/D4_optical_parameter_sweep}
  \begin{alertblock}{\textcolor{brokenred}{Culpable identificado}}\small
    \texttt{CreateBarSkinReflector()} usa \texttt{dielectric\_metal} (R=0.98) $\to$
    sin TIR posible. 164 rebotes $\times$ 2\% perdida/rebote $\times$ ABSLENGTH $\to$ 0.04\,PE esperado (sim: 0.37).\\
    \textbf{Incluso R=1.0 da solo D4_R1\,PE} --- la unica solucion es TIR.
  \end{alertblock}
\end{frame}

\section{D5: Fix parcial (TIR)}

\begin{frame}{D5 --- Fix TIR (branch exec21-optfix): validacion parcial}
  \begin{columns}[T]
    \begin{column}{0.55\textwidth}
      \includegraphics[width=\textwidth,height=0.58\textheight,keepaspectratio]{D5/D5_validation_tir}
    \end{column}
    \begin{column}{0.44\textwidth}\small
      \textbf{Cambio: dielectric\_metal $\to$ dielectric\_dielectric}\\[0.4em]
      \textbf{Resultado (3 condiciones D5):}
      \begin{itemize}
        \item (a) Npe realista? $x=0$: D5_NL_X0\,PE --- \textcolor{brokenred}{NO} (falta Mylar)
        \item (b) $\sigma<$ real? $x=-690$: D5_SIG_XM690\,ps $\approx250$\,ps --- \textcolor{warngold}{PARCIAL}
        \item (c) Bimodal? D5_PROMPT\% prompt near-end --- \textcolor{okgreen}{SI}
      \end{itemize}
      \vspace{0.3em}
      \textbf{Causa del fallo parcial:}\\
      Foton no-TIR (23\%) escapa sin Mylar que lo recupere.\\
      Fix completo = TIR + envolvente Mylar explicita.\\[0.3em]
      \textbf{Branch \texttt{exec21-optfix}: commit af5ddb7}
    \end{column}
  \end{columns}
\end{frame}

\section{D6: GLS y consecuencias}

\begin{frame}{D6 --- Bug GLS (EXEC-20) + consecuencias}
  \begin{columns}[T]
    \begin{column}{0.5\textwidth}
      \textbf{GLS bug de EXEC-20:}
      \begin{itemize}\small
        \item $\sigma_\text{GLS}=75.8$\,ps vs $\sigma_\text{TOP}=$ D6_SIG_TOP\,ps
        \item En este caso GLS $\approx\sigma_\text{TOP}$ (correcto: END no aporta)
        \item Correccion: inv-varianza $=$ D6_SIG_INVVAR\,ps $\leq\sigma_\text{TOP}$ \textcolor{okgreen}{\checkmark}
      \end{itemize}
      \vspace{0.3em}
      \textbf{Consecuencias para resultados previos:}
      \begin{itemize}\small
        \item $\sigma_\text{END}(x=0)=882$\,ps NO es fisico (sim sub-colecta luz)
        \item El ``aporte TOP 85\%'' de EXEC-20 T3 compara TOP fisico vs END no-fisico
        \item \textcolor{warngold}{\textbf{Re-evaluar T3 una vez que END sea fisico (fix Mylar completo)}}
      \end{itemize}
    \end{column}
    \begin{column}{0.49\textwidth}
      \begin{block}{Resumen del diagnostico}
        \small
        1. \textbf{Culpable}: \texttt{dielectric\_metal} mata TIR\\
        2. Prediccion teorica: 0.04\,PE (metalico) $\to$ 749\,PE (TIR)\\
        3. Real: $\sim40$\,PE (necesita TIR + Mylar)\\
        4. Fix parcial: TIR habilitado, Mylar pendiente\\
        5. End near-end ($x=-690$): mejora real ($\sigma$: 609$\to$259\,ps, bimodal!)\\
        6. Centro: no cambia sin Mylar (fotones escapan)
      \end{block}
    \end{column}
  \end{columns}
  {\tiny \textit{CAVEAT}}
\end{frame}

\end{document}
"""

out = TEX
for k, v in TOKENS.items():
    out = out.replace(k, str(v))

Path(BEAMER_DIR).mkdir(parents=True, exist_ok=True)
out_tex = BEAMER_DIR / "EXEC_21_diagnosis.tex"
out_tex.write_text(out)
print(f"Written: {out_tex}")
