#!/usr/bin/env python3.12
"""
build_beamer_17.py — Generate EXEC_17 Beamer deck.
Numbers injected via token substitution from CSVs/JSONs.
Compile: cd /mnt/d/SHiP/analysis_core/beamer/EXEC_17 && latexmk -lualatex EXEC_17_validation_corrections.tex
"""

import json, csv, math
from pathlib import Path

OUT_DIR    = "/home/reriosto/SHiP/analysis_core/out/EXEC_17"
BEAMER_DIR = Path(__file__).parent
FIG_DIR    = "/mnt/d/SHiP/analysis_core/out/EXEC_17"

c0_json   = json.loads(Path(f"{OUT_DIR}/c0_patch_summary.json").read_text())
corr_json = json.loads(Path(f"{OUT_DIR}/results_corrections.json").read_text())

def nan_(v): return v is None or (isinstance(v, float) and math.isnan(v))
def ff(v, d=1): return f"{v:.{d}f}" if not nan_(v) else "---"

# ── helper functions defined BEFORE use ────────────────────────────────────────

def build_c4_rows(table):
    rows = ""
    for r in table:
        est  = r.get("estimator","?").replace("_", r"\_")
        si   = r.get("sigma_int_ps", 0)
        Ne   = r.get("N_eff", 1)
        sA   = r.get("SPTR_analog_ps", 106)
        sB   = r.get("SPTR_digital_ps", 0)
        tA   = r.get("tot_analog_ps", 0)
        tB   = r.get("tot_digital_ps", 0)
        gA   = r.get("goal_met_analog","?")
        gB   = r.get("goal_met_digital","?")
        mA = r"\textcolor{passgreen}{\checkmark}" if gA=="YES" else r"\textcolor{failred}{$\times$}"
        mB = r"\textcolor{passgreen}{\checkmark}" if gB=="YES" else r"\textcolor{failred}{$\times$}"
        rows += (f"    {est} & ${si:.0f}$ & {Ne} & ${sA:.0f}$ & "
                 f"${sB:.0f}$ & ${tA:.0f}$ {mA} / ${tB:.0f}$ {mB} \\\\\n")
    return rows

def get_tot(table, est, model):
    key = "tot_analog_ps" if model == "A" else "tot_digital_ps"
    for r in table:
        if r.get("estimator") == est:
            return f"{r.get(key, 0):.0f}"
    return "---"

# ── load numbers ───────────────────────────────────────────────────────────────

v5b      = c0_json["C0_1_V5b"]
pred_ns  = v5b["pred_direct_ps"] / 1000.0
obs_ns   = v5b["obs_median_ps"]  / 1000.0
delta_p  = v5b["delta_pct_median"]

v7       = c0_json["C0_2_V7"]
a_ps     = v7["a_ps"];    a_err = v7["a_err_ps"];    b_up = v7["b_upper_1sigma_ps"]

v2_      = c0_json["C0_3_V2"]
eta_pct  = v2_["eta_global_pct"];   eff_y = v2_["effective_yield_PE_MeV"];   cv = v2_["cv_npe"]

r_np     = corr_json.get("C1_ratio_nonpond_x0")
r_p      = corr_json.get("C1_ratio_pond_x0")
sig_end  = corr_json.get("C1_sigma_end_x0")
sig_np   = corr_json.get("C1_sigma_et_nonpond_x0")
sig_p    = corr_json.get("C1_sigma_et_pond_x0")
ben_np   = corr_json.get("C1_benefit_nonpond_pct")
ben_p    = corr_json.get("C1_benefit_pond_pct")

c3_opt   = corr_json.get("C3_optimal_N", {})
c4_table = corr_json.get("C4_table", [])

c4_rows_tex = build_c4_rows(c4_table)
tot_A_sum4  = get_tot(c4_table, "TOP_SUM4", "A")
tot_B_sum4  = get_tot(c4_table, "TOP_SUM4", "B")
tot_B_sum8  = get_tot(c4_table, "TOP_SUM8", "B")
opt_x0      = c3_opt.get("x0_TOP_SUM4", "?")
opt_x690    = c3_opt.get("x-690_TOP_SUM4", "?")

CAVEAT = ("Intrinseco (sin SPTR/FastIC). OPSC-101/EJ-204. "
          "Branch feat/endtop-sslg4 (a0368c4). 31 pos x 5000 ev.")

# ── tex template ───────────────────────────────────────────────────────────────

GP = "{" + "{" + FIG_DIR + "/}" + "}"

TEX_HEADER = r"""% EXEC_17 — Validacion sim + correcciones de EXEC_16
% Generated by build_beamer_17.py — DO NOT EDIT MANUALLY
\documentclass[aspectratio=169,9pt]{beamer}
\usetheme{Madrid}\usecolortheme{default}
\setbeamertemplate{navigation symbols}{}
\setbeamerfont{frametitle}{size=\normalsize,series=\bfseries}
\usepackage{fontspec}
\setsansfont{DejaVu Sans}[Scale=0.93]
\setmonofont{DejaVu Sans Mono}[Scale=0.85]
\usepackage{graphicx,booktabs,xcolor,tikz,amssymb}
\graphicspath{{__FIGDIR__/}}
\definecolor{passgreen}{HTML}{2ca02c}
\definecolor{failred}{HTML}{d62728}
\definecolor{shipgoal}{HTML}{d62728}
\title[EXEC\_17 --- Validacion sim + correcciones]{%
  EXEC\_17 --- Validacion de la simulacion EJ-204 EndTop\\
  \large Bateria V1--V9 (9/9 PASS) + correcciones EXEC\_16}
\author[R.~Rios Torres]{Rene Rios Torres (ULS / SHiP)}
\institute[SHiP Timing]{SHiP Collaboration --- Timing Detector Group}
\date{20 junio 2026}
\begin{document}
\begin{frame}[plain]\titlepage\end{frame}
\begin{frame}{Contenidos}\tableofcontents\end{frame}
"""

TEX_VAL = r"""
\section{Validacion (V1--V9): CONFIABLE}

\begin{frame}{Resumen V1--V9}
  \begin{center}\small
  \begin{tabular}{clp{4.2cm}l}
  \toprule Test & Prediccion & Observado & Veredicto \\ \midrule
  V1 & END $\pm699.75$\,mm, 86 ch & $\bar{x}=-699.5$\,mm; rms\_x(TOP)=0.27\,mm & \textcolor{passgreen}{\textbf{PASS}} \\
  V2 & Landau, MPV$\approx$99\,PE, CV$\sim$0.3 & MPV=105\,PE, CV=CV_NPE & \textcolor{passgreen}{\textbf{PASS}} \\
  V3 & Pico $\lambda=408.8$\,nm & 407.8\,nm ($\Delta=1.0$\,nm) & \textcolor{passgreen}{\textbf{PASS}} \\
  V4 & Asimetria near/far; cresta diagonal & Asim.=0.999; $|\Delta x|_\text{med}=2.0$\,mm & \textcolor{passgreen}{\textbf{PASS}} \\
  V5 & $\tau_d=1.8$\,ns; bump END$@\sim$9.3\,ns & $\tau_d=1.835\pm0.013$\,ns; OBS_NS\,ns & \textcolor{passgreen}{\textbf{PASS}} \\
  V6 & L/R $<5\%$ & 3.0\% & \textcolor{passgreen}{\textbf{PASS}} \\
  V7 & $\sigma_t\propto1/\sqrt{N}$, $b\approx0$ & $a=A_PS\pm A_ERR$\,ps, $b<B_UP$\,ps & \textcolor{passgreen}{\textbf{PASS}} \\
  V8 & $|\text{sesgo}|<5\%$ & Max 1.4\% en $\sigma\in[30,200]$\,ps & \textcolor{passgreen}{\textbf{PASS}} \\
  V9 & 0\% muertos, cola minoritaria & 0.000\% muertos, 0.06\% anom $>5\sigma$ & \textcolor{passgreen}{\textbf{PASS}} \\
  \bottomrule
  \end{tabular}
  \end{center}
  \vspace{0.2em}
  \begin{center}\large\textcolor{passgreen}{\textbf{Veredicto global: CONFIABLE (9/9 PASS)}}\end{center}
\end{frame}

\begin{frame}{V4 -- Atenuacion y heatmap TOP (evidencia mas directa)}
  \includegraphics[width=\textwidth,height=0.62\textheight,keepaspectratio]{V4/V4_attenuation_heatmap}
  \begin{itemize}\small
    \item END\_L: $\langle N_\text{pe}\rangle=902/\text{ev}$ @ $x=-690$\,mm; $<0.1$ en extremo opuesto
    \item TOP: cresta diagonal --- canal mas cercano al haz tiene $|\Delta x|_\text{med}=2.0$\,mm
    \item \textbf{Mapeo global\_id$\to$posicion fisica es correcto}; no hay inversion ni error de indice
  \end{itemize}
\end{frame}

\begin{frame}{V5 -- Forma temporal: $\tau_d$ y bump far-end (con C0.1)}
  \includegraphics[width=0.82\textwidth,height=0.55\textheight,keepaspectratio]{V5/C0_1_V5b_corrected}
  \begin{columns}[T]
    \begin{column}{0.5\textwidth}\small
      Bug corregido (C0.1): \texttt{path\_mm / v\_eff\_mm\_ns}\\
      Correcto: $1389.75\,\text{mm} / 150.2\,\text{mm/ns} = $ PRED_NS\,ns\\
      Obs. mediana = OBS_NS\,ns; $|\Delta|=$DELTA_PCT\% \textbf{(PASS)}
    \end{column}
    \begin{column}{0.49\textwidth}\small
      $\tau_d^\text{fit}=1.835\pm0.013$\,ns; config 1.8\,ns (1.9\%) \textbf{PASS}\\
      326 hits END\_L con haz en $x=+690$ --- no muertos ni ruido anomalo
    \end{column}
  \end{columns}
\end{frame}

\begin{frame}{V7 + V2 -- Escalado Poisson y rendimiento optico (C0.2, C0.3)}
  \begin{columns}[T]
    \begin{column}{0.58\textwidth}
      \includegraphics[width=\textwidth,height=0.55\textheight,keepaspectratio]{V7/C0_2_V7_b_sigma}
    \end{column}
    \begin{column}{0.41\textwidth}\small
      \textbf{V7 (C0.2):}\\
      $a=A_PS\pm A_ERR$\,ps; $b<B_UP$\,ps ($1\sigma$)\\
      $R^2=0.955$; \textbf{Poisson puro}\\[0.4em]
      \textbf{V2 (C0.3) --- rendimiento:}\\
      $N_\text{gen}^\text{MPV}=20800$\,ph; $N_\text{det}=105$\,PE\\
      $\eta=ETA_PCT\%$; yield ef.=EFF_YIELD\,PE/MeV\\
      CV=CV_NPE (Landau, esperado 0.3--0.5)\\
      En $x=0$: TOP domina 99.4\% hits
    \end{column}
  \end{columns}
\end{frame}
"""

TEX_CORR = r"""
\section{Correcciones EXEC\_16 (C1--C4)}

\begin{frame}{C1 -- Razon EndTop/END-only: reconciliacion}
  \includegraphics[width=\textwidth,height=0.55\textheight,keepaspectratio]{C1/C1_endtop_ratio_corrected}
  \begin{itemize}\small
    \item \textbf{No-ponderado (EXEC\_16)}: $\bar{t}_\text{EndTop}=\tfrac{1}{2}(t_\text{END}+t_\text{TOP})$;
          $\sigma_\text{EndTop}=SIG_NP$\,ps; razon=R_NP (\textbf{TOP reduce BEN_NP\%})\\
          Teorico: $\tfrac{1}{2}\sqrt{883^2+74^2}\approx443$\,ps; medido 520\,ps (correlaciones)
    \item \textbf{Ponderado inv-varianza}: $\sigma_\text{opt}=1/\sqrt{1/883^2+1/74^2}\approx SIG_P$\,ps;
          razon=R_P (\textbf{TOP reduce BEN_P\%})
    \item En $x=0$: $\sigma_\text{END}\approx SIG_END$\,ps $\gg$ $\sigma_\text{TOP}\approx74$\,ps $\Rightarrow$ combinacion optima $\approx$ TOP solo
  \end{itemize}
\end{frame}

\begin{frame}{C2 -- Curvas END banda completa [5, 2000 ps]}
  \includegraphics[width=\textwidth,height=0.60\textheight,keepaspectratio]{C2/C2_end_curves_full_band}
  \begin{itemize}\small
    \item END\_L\_SUM4: $\sigma\approx30$\,ps @ $x=-690$ (near-end) $\to$ $>$900\,ps @ $x=0$
    \item No es fallo de ajuste: distribucion fisicamente ancha con pocos fotones lejos del extremo
    \item (EXEC\_16 abortaba estas curvas por $\sigma>400$\,ps; escala log en $y$ para ver rango completo)
  \end{itemize}
\end{frame}

\begin{frame}{C3 -- Barrido $N$ en $\{2,3,4,6,8\}$}
  \includegraphics[width=0.90\textwidth,height=0.58\textheight,keepaspectratio]{C3/C3_sumN_sweep}
  \begin{itemize}\small
    \item Optimo en $\{2..8\}$: $N=$ OPT_N_X0 @ $x=0$\,mm; OPT_N_X690 @ $x=-690$\,mm
    \item $N=1$ (EXEC\_16) sigue siendo mejor: $\sigma=72.6$\,ps vs 84--89\,ps para $N\geq2$
    \item Anomalia SUM8$>$SUM4: los 4 canales adicionales (de SUM4 a SUM8) estan mas lejos del haz, aportan fotones tardios --- efecto pequeno, dentro del bootstrap
  \end{itemize}
\end{frame}

\begin{frame}{C4 -- Tabla SPTR: dos modelos de lectura}
  \begin{center}\small
  \begin{tabular}{lccccl}
  \toprule
  Estimador & $\sigma_\text{int}$ & $N_\text{eff}$ & $\sigma_\text{SPTR}^\text{A}$ & $\sigma_\text{SPTR}^\text{B}$ & $\sigma_\text{tot}$ A / B \\
  \midrule
""" + c4_rows_tex + r"""  \bottomrule
  \end{tabular}
  \end{center}
  \begin{itemize}\small
    \item \textbf{Modelo A} (analogico + CFD): SPTR = 106\,ps (single-channel, plano)
    \item \textbf{Modelo B} (digital multi-canal): SPTR\_eff $\approx 106/\sqrt{N_\text{eff}}$
    \item $\sigma_\text{int}$ ya incluye jitter SiPM; NO volver a sumar
    \item \textbf{Modelo B TOP\_SUM8}: $\sigma_\text{tot}\approx$ TOT_B_SUM8\,ps $<100$\,ps SHiP!
    \item \textbf{El $<$100\,ps de EXEC\_16 es intrinseco}: con Modelo A, $\approx$ TOT_A_SUM4\,ps
  \end{itemize}
  {\tiny \textit{CAVEAT_TEX}}
\end{frame}
"""

TEX_SUMMARY = r"""
\section{Resumen y proximos pasos}

\begin{frame}{Resumen EXEC\_17}
  \begin{columns}[T]
    \begin{column}{0.50\textwidth}
      \textbf{Validacion (9/9 PASS):}
      \begin{itemize}\small
        \item Canal-map exacto ($<0.3$\,mm) --- V1 PASS
        \item $\tau_d=1.835$\,ns (config 1.8\,ns, 1.9\%) --- V5a PASS
        \item Bump far-end: OBS_NS\,ns vs PRED_NS\,ns (DELTA_PCT\%) --- V5b PASS
        \item L/R simetria = 3.0\% --- V6 PASS
        \item $\sigma_t\propto1/\sqrt{N_\text{pe}}$, $b<B_UP$\,ps --- V7 PASS
        \item Cierre estimador: sesgo $<1.4\%$ --- V8 PASS
        \item $\eta_\text{global}=ETA_PCT\%$, CV=CV_NPE (Landau) --- V2 PASS
      \end{itemize}
    \end{column}
    \begin{column}{0.49\textwidth}
      \textbf{Correcciones (C0--C4):}
      \begin{itemize}\small
        \item \textbf{C1}: Razon ponderada @ $x=0$ = R_P (BEN_P\%); no-pond. = R_NP (BEN_NP\%)
        \item \textbf{C2}: END near-end @ $x=-690$: $\sigma\approx30$\,ps intrinseco
        \item \textbf{C3}: $N^\text{opt}=$ OPT_N_X0 (en $\{2..8\}$) @ $x=0$; $N=1$ (EXEC\_16) sigue siendo mejor
        \item \textbf{C4}: Modelo B TOP\_SUM8: $\approx TOT_B_SUM8$\,ps ($<100$\,ps SHiP)
        \item \textbf{C4}: Modelo A TOP\_SUM4: $\approx TOT_A_SUM4$\,ps
      \end{itemize}
    \end{column}
  \end{columns}
  \vspace{0.3em}
  {\tiny \textit{CAVEAT_TEX}}
\end{frame}

\begin{frame}{Proximos pasos}
  \begin{enumerate}
    \item \textbf{EXEC\_02b}: SPTR + FastIC en cuadratura (hooks listos en exec16\_endtop\_ej204.py)
    \item \textbf{Razon ponderada}: adoptar inv-varianza (C1) como estandar; retirar promedio simple
    \item \textbf{$N^\text{opt}(x)$}: usar barrido C3 para elegir $N$ optimo por posicion dinamicamente
    \item \textbf{HOOK\_WALK}: correccion time-walk leading-edge (stub reservado)
    \item \textbf{Clustering}: decision de Gerardo (id//4 fijo vs ventana movil)
    \item \textbf{EJ-230 EndTop}: cierre del 2$\times$2 material$\times$readout pendiente
  \end{enumerate}
  \vspace{0.3em}
  {\tiny \textit{CAVEAT_TEX}}
\end{frame}

\end{document}
"""

# Assemble and substitute tokens
out = TEX_HEADER + TEX_VAL + TEX_CORR + TEX_SUMMARY

TOKENS = {
    "__FIGDIR__":  FIG_DIR,
    "CV_NPE":     f"{cv:.3f}",
    "OBS_NS":     f"{obs_ns:.3f}",
    "PRED_NS":    f"{pred_ns:.3f}",
    "DELTA_PCT":  f"{delta_p:.1f}",
    "A_PS":       f"{a_ps:.0f}",
    "A_ERR":      f"{a_err:.0f}",
    "B_UP":       f"{b_up:.0f}",
    "ETA_PCT":    f"{eta_pct:.2f}",
    "EFF_YIELD":  f"{eff_y:.0f}",
    "SIG_END":    ff(sig_end, 0),
    "SIG_NP":     ff(sig_np, 0),
    "SIG_P":      ff(sig_p, 0),
    "R_NP":       ff(r_np, 3),
    "R_P":        ff(r_p, 3),
    "BEN_NP":     str(int(ben_np)) if ben_np is not None else "---",
    "BEN_P":      str(int(ben_p))  if ben_p  is not None else "---",
    "OPT_N_X0":   str(opt_x0),
    "OPT_N_X690": str(opt_x690),
    "TOT_B_SUM8": tot_B_sum8,
    "TOT_A_SUM4": tot_A_sum4,
    "CAVEAT_TEX": CAVEAT,
}
for k, v in TOKENS.items():
    out = out.replace(k, v)

out_tex = BEAMER_DIR / "EXEC_17_validation_corrections.tex"
out_tex.write_text(out)
print(f"Written: {out_tex}")
