#!/usr/bin/env python3.12
"""build_beamer_22.py — EXEC_22 Beamer: optical fix, velocity audit, END baseline."""
import json, math
from pathlib import Path

OUT_DIR    = "/home/reriosto/SHiP/analysis_core/out/EXEC_22"
BEAMER_DIR = Path(__file__).parent
FIG_DIR    = "/mnt/d/SHiP/analysis_core/out/EXEC_22"

rj = json.loads(Path(f"{OUT_DIR}/results_exec22.json").read_text())

def G(k, d=1):
    v = rj.get(k, "---")
    try: return "---" if math.isnan(float(v)) else f"{float(v):.{d}f}"
    except: return str(v)

TOKENS = {
    "__FIGDIR__":       FIG_DIR,
    "T2_GATE":          rj.get("T2_gate","?"),
    "T2_MAX_V":         G("T2_max_v_over_cn", 3),
    "T3_NPE_X0":        G("T3_npe_L_x0", 2),
    "T3_NPE_XM600":     G("T3_npe_L_xm600", 1),
    "T3_NPE_XM690":     G("T3_npe_L_xm690", 1),
    "T3_COND_A":        rj.get("T3_cond_a","?"),
    "T3_COND_B":        rj.get("T3_cond_b","?"),
    "T3_COND_C":        rj.get("T3_cond_c","?"),
    "T3_PROFILE":       rj.get("T3_profile_shape","?"),
    "T4_VEL":           rj.get("T4_velocity","?"),
    "DIAG_SURFACE":     rj.get("diagnosis_surface_only","?"),
    "FULL_FIX":         rj.get("full_fix_needed","?"),
    "CAVEAT":           "Intrinseco/PDE. EJ-204 OPSC-101. No SPTR/FastIC.",
}

TEX = r"""% EXEC_22 — Fix optico, auditoria velocidad, baseline END
% Generated by build_beamer_22.py
\documentclass[aspectratio=169,9pt]{beamer}
\usetheme{Madrid}\usecolortheme{default}
\setbeamertemplate{navigation symbols}{}
\setbeamerfont{frametitle}{size=\normalsize,series=\bfseries}
\usepackage{fontspec}
\setsansfont{DejaVu Sans}[Scale=0.93]
\setmonofont{DejaVu Sans Mono}[Scale=0.85]
\usepackage{graphicx,booktabs,xcolor,amssymb}
\graphicspath{{__FIGDIR__/}}
\definecolor{passgreen}{HTML}{2ca02c}
\definecolor{failred}{HTML}{d62728}
\definecolor{warngold}{HTML}{e67e00}
\title[EXEC\_22 --- Fix optico + auditoria velocidad]{%
  EXEC\_22 --- Fix optico TIR, auditoria anti-superluminica,\\
  \large baseline END-only fisico (parcial)}
\author[R.~Rios Torres]{Rene Rios Torres (ULS / SHiP)}
\institute[SHiP Timing]{SHiP Collaboration --- Timing Detector Group}
\date{21 junio 2026}
\begin{document}
\begin{frame}[plain]\titlepage\end{frame}
\begin{frame}{Contenidos}\tableofcontents\end{frame}

\section{T1: Fix optico (dielectric\_dielectric + REFLECTIVITY)}

\begin{frame}{T1 --- Estrategia del fix (superficie, sin air gap)}
  \begin{columns}[T]
    \begin{column}{0.55\textwidth}
      \textbf{Causa raiz (EXEC\_21)}: \texttt{dielectric\_metal} elimina TIR.\\
      164 rebotes $\times$ 2\% perdida $\to$ 0.04\,PE esperado (sim: 0.37\,PE)\\[0.4em]
      \textbf{Fix aplicado en \texttt{exec21-optfix} (ej200\_endonly):}
      \begin{enumerate}\small
        \item \texttt{dielectric\_dielectric} (TIR habilitado)
        \item \texttt{polished}, sigma\_alpha = 0
        \item \texttt{REFLECTIVITY=0.95} en MPT (Mylar no-TIR)
        \item World RINDEX=1.0 ya estaba definido $\to$ TIR funciona
      \end{enumerate}
      \vspace{0.3em}
      \textbf{Port a EndTop} en \texttt{exec22-endtop-optfix} (commit 76b582c).
    \end{column}
    \begin{column}{0.44\textwidth}
      \begin{block}{Fix en Materials.cc:337-373}\small
        \texttt{surf->SetType(dielectric\_dielectric);}\\
        \texttt{surf->SetFinish(polished);}\\
        \texttt{mpt->AddProperty("REFLECTIVITY", e, 0.95);}
      \end{block}
      \vspace{0.3em}
      \begin{alertblock}{\small Limitacion}\footnotesize
        El REFLECTIVITY para fotones no-TIR en Geant4 11.04 no
        recupera completamente los fotones no-TIR en superficie sola.
        Fix completo = geometria con gap de aire + panel Mylar (pendiente).
      \end{alertblock}
    \end{column}
  \end{columns}
\end{frame}

\section{T2: Auditoria anti-superluminica (GATE)}

\begin{frame}{T2 --- Auditoria de velocidad: T2_GATE}
  \begin{columns}[T]
    \begin{column}{0.54\textwidth}
      \begin{block}{\textcolor{passgreen}{T2 GATE: T2_GATE}}
        Max $v/(c/n) = $ T2_MAX_V $< 1.0$ \\
        Fraccion superluminica = 0.0000\%\\
        \textbf{Ningun foton viaja $> c/n$ en el centellador.}
      \end{block}
      \vspace{0.3em}
      \begin{itemize}\small
        \item World RINDEX=1.0 verificado: fotones en WorldLV viajan a $c$
        \item Sin gap de aire $\to$ sin fotones en volumen de aire $\to$ sin superluminico
        \item T4 EndTop mini-sim: tambien PASS (max $v/(c/n)=0.936$)
      \end{itemize}
    \end{column}
    \begin{column}{0.45\textwidth}\small
      Metodo: para cada fotón detectado en END:\\
      $v_\text{eff} = d_\text{min}/t_\text{hit}$ (limite inferior)\\
      Si $v_\text{eff} > c/n$ $\to$ superluminico.\\[0.5em]
      $d_\text{min}$ = distancia directa gun$\to$SiPM\\
      Fotones que rebotan tienen $v_\text{eff} \ll c/n$ (camino real $> d_\text{min}$).\\[0.5em]
      El hecho de que $\max v_\text{eff}/(c/n) < 1.0$ confirma\\
      que el RINDEX del centellador esta correcto.
    \end{column}
  \end{columns}
\end{frame}

\section{T3: Validacion de las 3 condiciones}

\begin{frame}{T3 --- Revalidacion: 3 condiciones (fix parcial)}
  \includegraphics[width=\textwidth,height=0.55\textheight,keepaspectratio]{T3/T3_T5_npe_sigma_profiles}
  \begin{itemize}\small
    \item \textbf{(a)} Npe realista: $x=0$: T3_NPE_X0\,PE; $x=-600$: T3_NPE_XM600\,PE; $x=-690$: T3_NPE_XM690\,PE --- \textcolor{failred}{FALLA @ centro}
    \item \textbf{(b)} $\sigma_\text{END} < 250$\,ps: sigue roto en centro --- \textcolor{failred}{FALLA}
    \item \textbf{(c)} Bimodal: 48\% prompt @ $x=-690$ --- \textcolor{passgreen}{PASA}
    \item \textcolor{warngold}{\textbf{Mejora REAL}}: T3_PROFILE
  \end{itemize}
\end{frame}

\begin{frame}{T3 --- Diagnostico del fix parcial}
  \begin{alertblock}{Por que falla el centro con superficie-sola}
    En Geant4 11.04, la propiedad REFLECTIVITY en el MPT de una superficie
    \texttt{dielectric\_dielectric} no recupera completamente los fotones no-TIR.
    Consecuencia: 23\% de fotones por rebote siguen escapando.\\
    Con 164 rebotes promedio (centro$\to$END): $(0.77)^{164} \to 0$ supervivencia.\\[0.3em]
    \textbf{Fix incompleto}: TIR encendio (bimodal visible), pero no-TIR sigue escapando.\\
    \textbf{Fix completo}: geometria explicita (bar + gap de aire + panel Mylar exterior).
  \end{alertblock}
  \begin{itemize}\small
    \item El perfil de Npe es MAS SUAVE (seno de TIR activo cerca de extremos)
    \item Centro sigue fallando condiciones (a) y (b)
    \item T4 EndTop: port aplicado, auditoria OK, NO re-simular campaña sin aprobacion Rene
  \end{itemize}
  {\tiny \textit{CAVEAT}}
\end{frame}

\section{T5-T7: Baseline provisional y proximos pasos}

\begin{frame}{T5/T6 --- Baseline END-only provisional + proximos pasos}
  \begin{columns}[T]
    \begin{column}{0.50\textwidth}
      \textbf{Baseline END (scan 500\,ev/pos, R=0.90):}
      \begin{itemize}\small
        \item Npe perfil: suave cerca extremos, colapso en centro
        \item $\sigma_\text{END}(x=0)$ aun no fisico ($>250$\,ps)
        \item Comparacion TB Gerardo: pendiente de fix completo
      \end{itemize}
      \vspace{0.3em}
      \textbf{TOP contribution (provisional):}
      \begin{itemize}\small
        \item $\sigma_\text{END}$ no fisico $\to$ aporte TOP 85\% sigue invalido
        \item Una vez fix completo: recalcular
      \end{itemize}
    \end{column}
    \begin{column}{0.49\textwidth}
      \textbf{Proximos pasos (en orden):}
      \begin{enumerate}\small
        \item \textcolor{warngold}{\textbf{FIX COMPLETO}}: gap de aire + panel Mylar
          en \texttt{exec21-optfix} (ej200\_endonly)
        \item Re-validar 3 condiciones T3 con geometria correcta
        \item Re-simular campana EndTop (5000\,ev/pos) con fix:\\
          \texttt{[comando en EXEC\_22\_REPORT.md §T4]}
        \item Recalcular baseline END y aporte TOP con datos validos
        \item Comparacion apples-to-apples con Gerardo
      \end{enumerate}
      \vspace{0.2em}
      \textbf{GLS (D6 EXEC-21)}: $\sigma_\text{EndTop}\approx\sigma_\text{TOP}=75.9$\,ps\\
      (confirmed; fix unitario en la formula)
    \end{column}
  \end{columns}
  {\tiny \textit{CAVEAT}}
\end{frame}

\end{document}
"""

out = TEX
for k, v in TOKENS.items():
    out = out.replace(k, str(v))

Path(BEAMER_DIR).mkdir(parents=True, exist_ok=True)
out_tex = BEAMER_DIR / "EXEC_22_optical_fix.tex"
out_tex.write_text(out)
print(f"Written: {out_tex}")
