#!/usr/bin/env python3
"""
build_deck_ej230.py — Generate and compile the Beamer presentation
  "End-only + Mylar-wrapped EJ-230 bar: optical simulation study"

Usage:
  python build_deck_ej230.py [--pres-dir PATH] [--skip-compile]

All numerical values sourced from deck_values.json (no hardcoding).
LaTeX template uses @PLACEHOLDER@ markers.

Corrections vs. EJ-204 mirror (ADDENDUM FINAL):
  1.  M2: no "good fit" — "identifies two empirical scales; chi2/ndf=101 >> 1"
  2.  Covariance errors vs bootstrap CIs distinguished explicitly
  3.  Bootstrap type documented: position-level pairs bootstrap, C++/OpenMP, seed 230123
  4.  FPT: no causal "more photons inflates v_app" — use "estimator-dependent response"
  5.  Two NPE metrics: center_point_npe (x=0 exact) vs central_region_npe (|x|<=100mm avg)
  6.  EndTop: "consistent with higher-R boundaries; configuration-level result"
  7.  M3 offset C: "finite-range offset" not "recirculated floor"
  8.  Photon budget: surface+bulk not separated in census
  9.  Motivation: escape category included in fate description
  10. sigma_eq everywhere (not sigma_single in any label)
  11. Full M2 parameters (A_s, A_l, lambda_s, lambda_l) in four-models table
  12. Summary text uses approved template
  13. verify_deck_ej230.py checks forbidden phrases
"""

from __future__ import annotations

import argparse
import json
import math
import os
import pathlib
import shutil
import subprocess
import sys

HERE = pathlib.Path(__file__).parent
PRES_DIR = HERE  # deck_values.json, figures/, tables/ are all here


# ── helpers ───────────────────────────────────────────────────────────────────

def _load_values(pres_dir: pathlib.Path) -> dict:
    p = pres_dir / "deck_values.json"
    if not p.exists():
        sys.exit(f"ERROR: deck_values.json not found at {p}")
    with open(p) as f:
        return json.load(f)


def _fmt(v, decimals: int = 1, unit: str = "") -> str:
    if v is None or (isinstance(v, float) and not math.isfinite(v)):
        return r"\texttt{n/a}"
    s = f"{float(v):.{decimals}f}"
    return s + (r"\," + unit if unit else "")


def _fmt_int(v) -> str:
    if v is None:
        return r"\texttt{n/a}"
    return f"{int(v):,}"


def _sub(template: str, subs: dict[str, str]) -> str:
    for key, val in subs.items():
        template = template.replace(f"@{key}@", val)
    return template


def _read_tex(pres_dir: pathlib.Path, tab_key: str) -> str:
    p = pres_dir / "tables" / f"{tab_key}.tex"
    return p.read_text() if p.exists() else f"% {tab_key} not found\n"


def _pmfmt(val, err, decimals: int = 1) -> str:
    if val is None or err is None:
        return r"\texttt{n/a}"
    if not (math.isfinite(float(val)) and math.isfinite(float(err))):
        return r"\texttt{n/a}"
    return f"{float(val):.{decimals}f}\\pm{float(err):.{decimals}f}"


def _na_or(v, fmt=".1f") -> str:
    if v is None or (isinstance(v, float) and not math.isfinite(v)):
        return r"\texttt{n/a}"
    return f"{float(v):{fmt}}"


# ── LaTeX template ────────────────────────────────────────────────────────────

_TEMPLATE = r"""% auto-generated by build_deck_ej230.py -- do not edit by hand
% All numerical values sourced from deck_values.json
\documentclass[aspectratio=169,10pt]{beamer}

\usetheme{default}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage{amsmath}
\usepackage{xcolor}
\usepackage{siunitx}

\definecolor{shipblue}{RGB}{20,74,130}
\definecolor{warnorange}{RGB}{210,105,30}
\definecolor{okgreen}{RGB}{0,128,0}
\setbeamercolor{structure}{fg=shipblue}
\setbeamercolor{alerted text}{fg=warnorange}
\setbeamertemplate{navigation symbols}{}
\setbeamertemplate{footline}[frame number]

% ---- macros sourced from deck_values.json -----------------------------------
\newcommand{\BarLen}{@BAR_LEN@}
\newcommand{\NEv}{@N_EV@}
\newcommand{\NPos}{@N_POS@}
% Material properties (EJ-230 / OPSC-106, Materials.cc)
\newcommand{\LamBulk}{@LAM_BULK@}
\newcommand{\ScintYield}{@SCINT_Y@\,$\gamma$/MeV}
\newcommand{\PeakEm}{@PEAK_EM@}
\newcommand{\RefrIdx}{@REFR_IDX@}
\newcommand{\DensityGcc}{@DENSITY@}
\newcommand{\TauRise}{@TAU_R@\,ns}
\newcommand{\TauDecay}{@TAU_D@\,ns}
% Optical group velocity
\newcommand{\VGroup}{@V_GROUP@\,mm/ns}
% Mylar
\newcommand{\MylarR}{@MYLAR_R@}
\newcommand{\MylarLoss}{@MYLAR_LOSS@}
\newcommand{\MylarSL}{@MYLAR_SL@}
\newcommand{\MylarSA}{@MYLAR_SA@}
% SiPM
\newcommand{\PDEpeak}{@PDE_PCT@\%}
\newcommand{\SiPMModel}{@SIPM_MODEL@}
\newcommand{\SiPMModelPDE}{@SIPM_MODEL_PDE@}
% Attenuation -- M1 (single-exp)
\newcommand{\LamSingleL}{\ensuremath{@LAM_SINGLE_L@}\,cm}
\newcommand{\LamSingleR}{\ensuremath{@LAM_SINGLE_R@}\,cm}
\newcommand{\ChiSingleL}{@CHI_SINGLE_L@}
\newcommand{\NzeroSingleL}{@N0_SINGLE_L@}
% Attenuation -- M3 (exp + finite-range offset)
\newcommand{\LamPromptL}{\ensuremath{@LAM_PROMPT_L@}\,cm}
\newcommand{\COffsetL}{\ensuremath{@C_OFFSET_L@}\,PE}
\newcommand{\ChiExpoffL}{@CHI_EXPOFF_L@}
% Attenuation -- M2 (constrained double-exp)
\newcommand{\LamShortL}{\ensuremath{@LAM_SHORT_L@}\,cm}
\newcommand{\LamLongL}{\ensuremath{@LAM_LONG_L@}\,cm}
\newcommand{\AmpShortL}{\ensuremath{@AMP_SHORT_L@}}
\newcommand{\AmpLongL}{\ensuremath{@AMP_LONG_L@}}
\newcommand{\ChiMtwo}{@CHI_M2_L@}
% Attenuation -- M4 (tail slope)
\newcommand{\LamTailL}{\ensuremath{@LAM_TAIL_L@}\,cm}
\newcommand{\LamTailR}{\ensuremath{@LAM_TAIL_R@}\,cm}
\newcommand{\ChiTailL}{@CHI_TAIL_L@}
\newcommand{\DTail}{@D_TAIL@}
% NPE at key positions
\newcommand{\ActualNearL}{@NPE_NEAR_L@}
\newcommand{\NpeLeftZero}{@NPE_L_X0@}         % x=0 exact (center_point_npe)
\newcommand{\NpeRightZero}{@NPE_R_X0@}
\newcommand{\NpeCentralLeft}{@NPE_CENTRAL_L@}  % |x|<=100 mm average
\newcommand{\NpeCentralRight}{@NPE_CENTRAL_R@}
% Near / far ends
\newcommand{\NpeNearLeft}{@NPE_NEAR_LEFT@}
\newcommand{\NpeFarRightAtLeft}{@NPE_FAR_R_AT_XNEG@}
\newcommand{\NpeNearRight}{@NPE_NEAR_RIGHT@}
\newcommand{\NpeFarLeftAtRight}{@NPE_FAR_L_AT_XPOS@}
% EndTop
\newcommand{\EndtopR}{@ENDTOP_R@}
\newcommand{\LamTailET}{\ensuremath{@LAM_TAIL_ET_L@}\,cm}
\newcommand{\NPECentralMylar}{@NPE_CENTRAL_MYLAR@}   % |x|<=100 mm avg
\newcommand{\NPECentralET}{@NPE_CENTRAL_ET@}
\newcommand{\NPEPointMylar}{@NPE_POINT_MYLAR@}        % x=0 exact
\newcommand{\NPEPointET}{@NPE_POINT_ET@}
% sigma_eq = sigma(tL-tR)/sqrt(2)
\newcommand{\SigEqAtMsixnine}{\ensuremath{@SG_M690@}\,ps}
\newcommand{\SigEqAtMfour}{\ensuremath{@SG_M400@}\,ps}
\newcommand{\SigEqAtZero}{\ensuremath{@SG_0@}\,ps}
\newcommand{\SigEqAtFour}{\ensuremath{@SG_P400@}\,ps}
\newcommand{\SigEqAtSixnine}{\ensuremath{@SG_P690@}\,ps}
% Apparent estimator velocities (not photon propagation speed)
\newcommand{\VappFPT}{@V_FPT@\,mm/ns}
\newcommand{\VappSUMfour}{@V_SUM4@\,mm/ns}
\newcommand{\VappTfifty}{@V_T50@\,mm/ns}
% Photon budget fractions
\newcommand{\PctSurfaceBulk}{@PCT_SURF_BULK@}
\newcommand{\PctEsc}{@PCT_ESC@}
\newcommand{\PctSiPM}{@PCT_SIPM@}
\newcommand{\PctDet}{@PCT_DET@}
\newcommand{\PDEeff}{@PDE_EFF@}
% Bootstrap summary (C++/OpenMP, 200 replicas) -- M4 tail
\newcommand{\BootTailMed}{@BOOT_M4_MED@}
\newcommand{\BootTailPlo}{@BOOT_M4_P16@}
\newcommand{\BootTailPhi}{@BOOT_M4_P84@}
\newcommand{\BootNReplicas}{@BOOT_N@}

\title[End-only + Mylar EJ-230]{%
  End-only + Mylar-wrapped EJ-230 bar:\\
  Optical simulation study}
\subtitle{Geant4 11.4.0 / SSLG4-OPSim}
\author{R.\ R\'ios (ULS)}
\institute{SHiP Collaboration Meeting}
\date{2026-06-14}

\begin{document}

% ---- FRAME 1: Title ----------------------------------------------------------
\begin{frame}
  \titlepage
\end{frame}

% ---- FRAME 2: Motivation & scope --------------------------------------------
\begin{frame}{Motivation \& scope}
  \begin{columns}[T]
    \column{0.55\textwidth}
    \begin{itemize}
      \item \textbf{Controlled optical study:} readout \emph{only} at the
            two ends ($\pm X$ faces); all other faces wrapped in Mylar.
            Not a final detector configuration.
      \item \textbf{Goals:}
        \begin{itemize}
          \item Isolate end-readout optical response.
          \item Characterize multi-component attenuation with Mylar.
          \item Benchmark timing estimators in a clean geometry.
        \end{itemize}
      \item \NPos\ beam positions ($x=-690\ldots+690$\,mm),
            \NEv\ $\mu^-$ events per position.
    \end{itemize}
    \column{0.43\textwidth}
    \begin{block}{This study}
      \textbf{End-only + Mylar} = extreme limit.
      Photons either exit to an end SiPM,
      \textbf{escape} through the bar boundaries,
      or are absorbed (surface or bulk) after multiple reflections.
    \end{block}
    \begin{alertblock}{\small No TB counterpart}
      \small This configuration has \alert{no direct test-beam counterpart}
      (April-2026 TB used top readout + Tyvek).
    \end{alertblock}
    \begin{alertblock}{\small Electronic jitter not included}
      \small SPTR ($\approx106$\,ps) and FastIC ($\approx10$\,ps) are
      post-processing steps, not folded into $\sigma_{\rm eq}$ shown here.
    \end{alertblock}
  \end{columns}
\end{frame}

% ---- FRAME 3: Geometry & simulation setup ------------------------------------
\begin{frame}{Geometry \& simulation setup}
  \begin{columns}[T]
    \column{0.55\textwidth}
    \begin{itemize}
      \item \textbf{Bar:} EJ-230 (OPSC-106),
            $\BarLen \times 60 \times 10$\,mm$^3$; long axis $X$.
      \item \textbf{End-left SiPMs} (IDs 0--7): $-X$ face.
            \textbf{End-right SiPMs} (IDs 8--15): $+X$ face.
      \item \textbf{Wrapping:} Mylar dielectric surface on $\pm Y,\pm Z$.
            $R=\MylarR$, specular lobe $=\MylarSL$,
            $\sigma_\alpha=\MylarSA^\circ$.
      \item \textbf{SUM4:} leading-edge at 4\,PE;
            groups $\{0\text{--}3\}/\{4\text{--}7\}$ (left),
            $\{8\text{--}11\}/\{12\text{--}15\}$ (right).
      \item \textbf{Rayleigh scattering:} active
            ($\lambda_{\rm Rayl}\approx150$\,cm at peak;
            $\propto\lambda^4$; Materials.cc:45--55).
    \end{itemize}
    \column{0.43\textwidth}
    \begin{block}{Key parameters}
      \small
      \begin{tabular}{ll}
        \toprule
        Scint.~yield    & \ScintYield \\
        Emission peak   & \PeakEm\,nm \\
        Bulk $\lambda$ (ABSLENGTH) & \LamBulk\,cm \\
        $n$ (flat)      & \RefrIdx \\
        $v_g = c/n$     & \VGroup \\
        $\tau_r/\tau_d$ & \TauRise/\TauDecay \\
        Mylar $R$       & \MylarR \\
        \bottomrule
      \end{tabular}
    \end{block}
    \begin{alertblock}{\small Note on $v_g$}
      \small No \texttt{GROUPVEL} property set.
      Geant4 computes $v_g=c/n=\VGroup$ from flat $n=\RefrIdx$.
    \end{alertblock}
  \end{columns}
\end{frame}

% ---- FRAME 4: Photon yield vs position ---------------------------------------
\begin{frame}{Photon yield at ends vs.\ beam position}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_npe_vs_x.png}
    \column{0.33\textwidth}
    \begin{block}{Representative values}
      \small
      Near \textbf{left} end ($x=-690$\,mm):\\
      \quad End-Left (near) $\approx \NpeNearLeft$\,PE\\
      \quad End-Right (far) $\approx \NpeFarRightAtLeft$\,PE
      \medskip

      \textbf{Center} ($x=0$, center-point):\\
      \quad End-Left $\approx \NpeLeftZero$\,PE\\
      \quad Central avg ($|x|\!\leq\!100$\,mm): $\approx\NpeCentralLeft$\,PE

      \medskip
      Near \textbf{right} end ($x=+690$\,mm):\\
      \quad End-Right (near) $\approx \NpeNearRight$\,PE\\
      \quad End-Left (far) $\approx \NpeFarLeftAtRight$\,PE
    \end{block}
    \begin{alertblock}{\small Two-scale structure}
      \small Near-end: prompt contribution.
      Center: $\approx\NpeCentralLeft$\,PE residual sustained by
      Mylar recirculation (many bounces at $R=\MylarR$).
    \end{alertblock}
  \end{columns}
\end{frame}

% ---- FRAME 5: Bulk vs system response ----------------------------------------
\begin{frame}{Bulk attenuation and longitudinal light-yield scales}
  \begin{columns}[T]
    \column{0.50\textwidth}
    \begin{block}{ABSLENGTH = \LamBulk\,cm (material property)}
      \small
      Describes absorption along the \textbf{actual optical path length} $s$:
      $P_{\rm bulk}(s)=e^{-s/\lambda_{\rm bulk}}$.
      A photon propagating 70\,cm longitudinally may traverse
      significantly more path via reflections.
      ABSLENGTH knows nothing about bar geometry or reflectors.
    \end{block}
    \begin{exampleblock}{Fitted longitudinal scale (system observable)}
      \small
      NPE vs.\ distance $d$ combines: bulk absorption (over actual $s$),
      Rayleigh scattering, geometry, repeated Mylar surface losses,
      SiPM acceptance, and PDE.
      \textbf{Any fitted scale is a system-dependent empirical parameter.}
    \end{exampleblock}
    \column{0.48\textwidth}
    \begin{alertblock}{Why single-exp fails}
      \small
      Three numbers inconsistent with $N_0\,e^{-d/\lambda}$:
      \begin{enumerate}
        \item Two-point: $\lambda\approx19$\,cm
        \item Fit: $N_0=\NzeroSingleL$\,PE, $\lambda=\LamSingleL$
        \item Observed at $d\approx0$: $\ActualNearL$\,PE
      \end{enumerate}
      Items (2) and (3) disagree by $\approx3.6\times$.\\
      $\chi^2/\mathrm{ndf}=\ChiSingleL$: catastrophic.
      \medskip
      \textbf{Cause:} superposition of a prompt component
      and a long-range contribution with finite-range offset.
    \end{alertblock}
  \end{columns}
\end{frame}

% ---- FRAME 6: Attenuation curve ----------------------------------------------
\begin{frame}{Attenuation: four models and empirical tail slope}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_attenuation.png}
    \column{0.33\textwidth}
    \begin{block}{M3 result (exp + finite-range offset)}
      \small
      $N(d) = A\,e^{-d/\lambda_p} + C$
      \medskip

      $\lambda_p = \LamPromptL$ (prompt scale)\\
      $C = \COffsetL$ (finite-range offset)\\
      $\chi^2/\mathrm{ndf} = \ChiExpoffL$
    \end{block}
    \begin{block}{M4 (empirical tail slope)}
      \small
      $d>\DTail$\,cm:\quad $\lambda_{\rm tail}=\LamTailL$\\
      $\chi^2/\mathrm{ndf}=\ChiTailL$
    \end{block}
    \begin{alertblock}{\small All $\chi^2/\mathrm{ndf}\gg1$}
      \small All models are \emph{empirical approximations}.
      $\lambda_p$, $\lambda_{\rm tail}$ are system-dependent scales,
      not the EJ-230 bulk ABSLENGTH (\LamBulk\,cm).
    \end{alertblock}
  \end{columns}
\end{frame}

% ---- FRAME 7: Model comparison -----------------------------------------------
\begin{frame}{Model comparison: M1, M2, M3, M4 (left side)}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth,height=0.80\textheight,keepaspectratio]{figures/fig_attenuation_twocomp.png}
    \column{0.33\textwidth}
    \begin{block}{Fit diagnostics (covariance errors)}
      \tiny
      \begin{tabular}{lrr}
        \toprule
        Parameter & Value & $\chi^2/\mathrm{ndf}$ \\
        \midrule
        M1: $\lambda$             & \LamSingleL  & \ChiSingleL \\
        M3: $\lambda_p$           & \LamPromptL  & \ChiExpoffL \\
        M3: $C$ (offset)          & \COffsetL    & --- \\
        M2: $A_s$                 & \AmpShortL   & \ChiMtwo \\
        M2: $\lambda_s$           & \LamShortL   & --- \\
        M2: $A_l$                 & \AmpLongL    & --- \\
        M2: $\lambda_l$           & \LamLongL    & --- \\
        M4: $\lambda_{\rm tail}$  & \LamTailL    & \ChiTailL \\
        \bottomrule
      \end{tabular}
    \end{block}
    \begin{alertblock}{\small Empirical approximations}
      \small
      Red star: observed NPE $\approx\ActualNearL$\,PE at $d\approx0$.\\
      M1 $N_0=\NzeroSingleL$\,PE: factor $\approx3.6$ off.\\
      M2 identifies two empirical scales but
      $\chi^2/\mathrm{ndf}=\ChiMtwo\gg1$:
      not an exact description.
    \end{alertblock}
  \end{columns}
\end{frame}

% ---- FRAME 8: Far-end light yield -------------------------------------------
\begin{frame}{Far-end light yield: where reflector quality matters}
  \begin{columns}[T]
    \column{0.55\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_far_end_yield.png}
    \column{0.43\textwidth}
    \begin{block}{Central-region NPE ($|x|\leq100$\,mm)}
      \small
      \begin{tabular}{lrr}
        \toprule
        Config & $R$ & NPE \\
        \midrule
        End-only+Mylar & \MylarR & \NPECentralMylar\,PE \\
        EndTop         & \EndtopR & \NPECentralET\,PE \\
        \bottomrule
      \end{tabular}
      \medskip
      Ratio EndTop/Mylar $\approx 2.5\times$.
    \end{block}
    \begin{alertblock}{\small Interpretation}
      \small
      Both see photons after $\geq60$\,cm and many
      reflections.
      Mylar loss/interaction: $1{-}R=\MylarLoss$ (10\%).
      Accumulated over many bounces, this strongly suppresses
      far-end yield.
      \smallskip
      $2.5\times$ difference is \textbf{consistent with}
      higher-$R$ boundaries in EndTop ($R=\EndtopR$),
      but this is a \textbf{configuration-level result}.
    \end{alertblock}
  \end{columns}
\end{frame}

% ---- FRAME 9: Apples-to-apples EndTop ----------------------------------------
\begin{frame}{Apples-to-apples: End-only+Mylar vs.\ EndTop (end SiPMs only)}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_endtop_comparison.png}
    \column{0.33\textwidth}
    \begin{block}{Identical pipeline}
      \small
      Both datasets: same end-SiPM-only selection,
      same models, same tail-fit range $d>\DTail$\,cm.
    \end{block}
    \begin{block}{Empirical tail slope ($d>\DTail$\,cm)}
      \tiny
      \begin{tabular}{lr}
        \toprule
        Config & $\lambda_{\rm tail}$ \\
        \midrule
        End-only+Mylar & \LamTailL \\
        EndTop (end SiPMs) & \LamTailET \\
        \bottomrule
      \end{tabular}

      Numerically similar slopes in this fit range.
      Does \emph{not} establish reflector independence
      or exclude model error.
    \end{block}
    \begin{alertblock}{\small Key conclusion}
      \small
      NPE amplitude at center differs $2.5\times$.
      The tail slope is not the discriminating observable;
      the \textbf{absolute light yield} is.
      Difference is consistent with higher-$R$ boundaries
      (configuration-level).
    \end{alertblock}
  \end{columns}
\end{frame}

% ---- FRAME 10: Timing distributions -----------------------------------------
\begin{frame}{Arrival-time distributions: FPT at representative positions}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth,height=0.78\textheight,keepaspectratio]{figures/fig_timing_histograms.png}
    \column{0.33\textwidth}
    \begin{block}{Distributions shown}
      \small
      FPT at End-Left and End-Right.\\
      $x\in\{-690,-400,0,+400,+690\}$\,mm.\\
      $N = \NEv$ events/position.
    \end{block}
    \begin{alertblock}{\small Shape}
      \small Distribution shifts later and broadens
      as beam moves from the SiPM:
      longer path, fewer photons, estimator-dependent
      response to photon-population size.
    \end{alertblock}
  \end{columns}
\end{frame}

% ---- FRAME 11: FPT vs t50 ---------------------------------------------------
\begin{frame}{FPT vs.\ $t_{50}$: estimator comparison}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_fpt_vs_t50.png}
    \column{0.33\textwidth}
    \begin{block}{FPT vs.\ $t_{50}$}
      \small
      FPT: minimum arrival time per event.\\
      $t_{50}$: per-event median --- less sensitive
      to photon-population size effects.
      \medskip
      $t_{50}$ is systematically later than FPT;
      offset grows with distance.
    \end{block}
    \begin{alertblock}{\small Estimator-dependent response}
      \small
      Both FPT and $t_{50}$ slopes exhibit
      position-dependent apparent velocities.
      These reflect the \textbf{estimator-dependent apparent
      longitudinal response}: systematic shifts of the
      estimator mean with photon-population size and
      reflection path-length distribution.
      This is a sampling and bias effect, not superluminal transport.
    \end{alertblock}
  \end{columns}
\end{frame}

% ---- FRAME 12: Position dependence of timing estimators ---------------------
\begin{frame}{Position dependence of timing estimators}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_mean_arrival_time.png}
    \column{0.33\textwidth}
    \begin{block}{Apparent estimator velocities}
      \small
      \begin{tabular}{ll}
        \toprule
        Estimator & $v_{\rm app}$ \\
        \midrule
        SUM4 $\Delta t$  & \VappSUMfour \\
        FPT slope        & \VappFPT \\
        $t_{50}$ slope   & \VappTfifty \\
        \midrule
        $c/n$ (theory)   & \VGroup \\
        \bottomrule
      \end{tabular}
    \end{block}
    \begin{alertblock}{\small All exceed $c/n$}
      \small
      These are \textbf{estimator-dependent apparent longitudinal
      responses}, not direct measurements of photon group velocity.
      All exceed $c/n = \VGroup$\ ($n=\RefrIdx$, flat RINDEX).
      Reflects position-dependent photon-population and
      estimator biases (reflections, path-length distributions,
      threshold selection).
    \end{alertblock}
  \end{columns}
\end{frame}

% ---- FRAME 13: sigma_eq(x) --------------------------------------------------
\begin{frame}{Intrinsic timing metric $\sigma_{\rm eq}(x)$}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_sigma_t.png}
    \column{0.33\textwidth}
    \begin{block}{Key values of $\sigma_{\rm eq}$}
      \small
      \begin{tabular}{ll}
        \toprule
        $x$ (mm) & $\sigma_{\rm eq}$ (ps) \\
        \midrule
        $-690$ & \SigEqAtMsixnine \\
        $-400$ & \SigEqAtMfour \\
        $0$    & \SigEqAtZero \\
        $+400$ & \SigEqAtFour \\
        $+690$ & \SigEqAtSixnine \\
        \bottomrule
      \end{tabular}
    \end{block}
    \begin{alertblock}{\small Definition and caveats}
      \small
      $\sigma_{\rm eq}\equiv\sigma(t_L-t_R)/\sqrt{2}$
      (SUM4, core Gaussian fit).
      \textbf{Equals per-end resolution only under equal,
      independent-end assumptions} --- which break down at
      the bar ends where NPE is strongly asymmetric.
      \medskip
      Intrinsic optical+estimator only.
      SPTR and electronics \alert{not} included.
    \end{alertblock}
  \end{columns}
\end{frame}

% ---- FRAME 14: Photon budget -------------------------------------------------
\begin{frame}{Photon budget --- End-only + Mylar}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_photon_budget.png}
    \column{0.33\textwidth}
    \begin{block}{Panel A --- Terminal fates}
      \small
      \begin{tabular}{lr}
        \toprule
        Fate & Fraction \\
        \midrule
        Surface+bulk absorbed & $\approx\PctSurfaceBulk$\% \\
        Escaped               & $\PctEsc$\% \\
        Entered SiPM          & $\PctSiPM$\% \\
        \bottomrule
        Total                 & $\approx100$\% \\
      \end{tabular}
    \end{block}
    \begin{block}{Panel B --- SiPM conversion}
      \small
      $\epsilon_{\rm PDE,eff}
       = N_{\rm det}/N_{\rm SiPM}
       \approx \PDEeff$
    \end{block}
    \begin{alertblock}{\small Loss note}
      \small Surface and bulk absorption are
      \textbf{not} separately resolved:
      the census cannot distinguish which
      mechanism removed the photon.
      Mylar loss/interaction: $1{-}R=\MylarLoss$.
    \end{alertblock}
  \end{columns}
\end{frame}

% ---- FRAME 15: Summary -------------------------------------------------------
\begin{frame}{Summary}
  \begin{columns}[T]
    \column{0.55\textwidth}
    \begin{block}{Key findings}
      \small
      \begin{itemize}
        \item \textbf{ABSLENGTH $=\LamBulk$\,cm} = material property
              (actual path, not longitudinal distance).
              All fitted scales are system-dependent.
        \item \textbf{Tail slope} ($d>\DTail$\,cm):
              $\lambda_{\rm tail}=\BootTailMed\,[\BootTailPlo,\BootTailPhi]$\,cm
              (bootstrap 68\,\% CI, \BootNReplicas\ replicas).
        \item \textbf{M1:} $\chi^2/\mathrm{ndf}=\ChiSingleL$.
              \textbf{M2:} two scales, $\chi^2/\mathrm{ndf}=\ChiMtwo\gg1$.
        \item \textbf{EndTop} ($R=\EndtopR$): $2.5\times$ more central NPE.
              Consistent with higher-$R$; configuration-level result.
        \item $v_{\rm app}$ all exceed $c/n=\VGroup$:
              estimator-dependent apparent responses.
        \item $\sigma_{\rm eq}=\SigEqAtZero$ (center), intrinsic only.
              \textbf{Add SPTR+electronics separately.}
      \end{itemize}
    \end{block}
    \column{0.43\textwidth}
    \begin{block}{Next steps}
      \small
      \begin{enumerate}
        \item $\hat{t}_0-t_0^{\rm true}$ as primary metric.
        \item SPTR \emph{per detected photon}; no quadrature sum.
        \item Separate surface from bulk in census.
        \item Reflectivity scan ($R=0.85\text{--}0.95$).
        \item Simulate the actual TB geometry.
      \end{enumerate}
    \end{block}
  \end{columns}
\end{frame}

% ============================================================================
% APPENDIX
% ============================================================================
\appendix

\begin{frame}{Appendix A: simulation parameters}
  \tiny
  @TAB_PARAMS@
\end{frame}

\begin{frame}{Appendix B: $\sigma_{\rm eq}$ per-position summary}
  \centering\small
  @TAB_SIG@
  \par\medskip
  \small
  $\sigma_{\rm eq}=\sigma(t_L-t_R)/\sqrt{2}$ from SUM4 leading-edge
  core Gaussian fit.
  Equals per-end resolution only under equal, independent-end assumptions.
  Intrinsic optical+estimator only; SPTR and electronics not included.
\end{frame}

\begin{frame}{Appendix C: attenuation fit details (four models)}
  \centering\tiny
  @TAB_ATT@
  \par\medskip
  \small
  Weighted fits (per-point SEM). Errors from covariance diagonal.
  M4 tail: $d>\DTail$\,cm.
  All $\chi^2/\mathrm{ndf}\gg1$: empirical approximations only.
\end{frame}

\begin{frame}{Appendix D: empirical tail-slope range sensitivity}
  \centering\small
  \begin{tabular}{ccccc}
    \toprule
    $d_{\rm min}$ & $\lambda_{\rm tail}^{\rm L}$ & $\lambda_{\rm tail}^{\rm R}$ & $\chi^2/\mathrm{ndf}$ (L) \\
    \midrule
    30\,cm & $@TAIL_LAM_30L@$\,cm & $@TAIL_LAM_30R@$\,cm & @TAIL_CHI_30L@ \\
    40\,cm & $@TAIL_LAM_40L@$\,cm & $@TAIL_LAM_40R@$\,cm & @TAIL_CHI_40L@ \\
    50\,cm & $@TAIL_LAM_50L@$\,cm & $@TAIL_LAM_50R@$\,cm & @TAIL_CHI_50L@ \\
    \bottomrule
  \end{tabular}
  \par\medskip
  \small
  The empirical tail slope increases with $d_{\rm min}$,
  indicating residual curvature even in the ``tail'' region.
  Reference: $d_{\rm min}=\DTail$\,cm.
\end{frame}

\begin{frame}{Appendix E: M2 and M4 bootstrap stability
  (\BootNReplicas\ replicas, left side)}
  \centering\small
  \begin{tabular}{lccc}
    \toprule
    Parameter & Median & P16 & P84 \\
    \midrule
    M2: $\lambda_s$ (cm) & @M2_LS_MED@ & @M2_LS_P16@ & @M2_LS_P84@ \\
    M2: $\lambda_l$ (cm) & @M2_LL_MED@ & @M2_LL_P16@ & @M2_LL_P84@ \\
    M4: $\lambda_{\rm tail}$ (cm) & @M4_LT_MED@ & @M4_LT_P16@ & @M4_LT_P84@ \\
    \bottomrule
  \end{tabular}
  \par\medskip
  \small
  \textbf{Method:} position-level pairs bootstrap, C++/OpenMP,
  seed~230123, \BootNReplicas\ replicas.
  M2 failure rate: @M2_FAIL_FRAC@\%.
  Intervals are 68\,\% bootstrap CIs (P16--P84), distinct from
  covariance errors reported in Appendix~C.
  $\lambda_l^{\rm M2}$ consistent with $\lambda_{\rm tail}^{\rm M4}$.
\end{frame}

\begin{frame}{Appendix F: group-velocity and slope-velocity discussion}
  \small
  \begin{columns}[T]
    \column{0.50\textwidth}
    \begin{block}{Theoretical $v_g = c/n$}
      Flat $n=\RefrIdx$ in \texttt{Materials.cc}:41.
      No explicit \texttt{GROUPVEL} property set
      (Geant4 computes $v_g=c/n$):
      \[ v_g = 299.792/1.58 = \VGroup. \]
    \end{block}
    \begin{block}{Apparent slope velocities}
      \small
      \begin{tabular}{ll}
        \toprule
        Estimator & $v_{\rm app}$ \\
        \midrule
        SUM4 $\Delta t$ & \VappSUMfour \\
        FPT             & \VappFPT \\
        $t_{50}$        & \VappTfifty \\
        $c/n$ (theory)  & \VGroup \\
        \bottomrule
      \end{tabular}
    \end{block}
    \column{0.48\textwidth}
    \begin{exampleblock}{Why all exceed $c/n$}
      \small
      Slope-derived velocities are \textbf{estimator-dependent
      apparent longitudinal responses}.
      \medskip
      SUM4 $\Delta t$: $v_{\rm app}=2/|d\Delta t/dx|$.
      Photons travel longer actual paths via reflections,
      delaying both SUM4 times; net $\Delta t$ slope
      is shallower than a direct-path signal would give.
      \medskip
      FPT and $t_{50}$: both shift systematically with
      photon-population size and reflection path-length
      distribution, yielding estimator-specific biases.
      \medskip
      An axial single-photon injection test (no reflections,
      known $d$) is needed to validate Geant4's $v_g$.
    \end{exampleblock}
  \end{columns}
\end{frame}

\begin{frame}{Appendix G: method \& caveats}
  \small
  \begin{itemize}
    \item \textbf{Bar geometry:} $1400\times60\times10$\,mm$^3$, axis $X$.
          End SiPMs on $\pm X$; Mylar dielectric surface on $\pm Y,\pm Z$.
    \item \textbf{$\sigma_{\rm eq} = \sigma(t_L-t_R)/\sqrt{2}$} is an
          \emph{equivalent} per-end metric assuming equal, independent ends.
          Not a bar-level resolution measurement.
    \item \textbf{Intrinsic only:} SPTR ($\approx106$\,ps) and FastIC
          ($\approx10$\,ps) not folded in.
          Apply SPTR at the photoelectron level; do not add full SPTR
          directly in quadrature to event resolution.
    \item \textbf{SiPM naming:} \texttt{\SiPMModelPDE} used only for the
          PDE curve; physical device is \textbf{\SiPMModel}.
    \item \textbf{Photon budget:} surface+bulk absorption not separately
          resolved in the boundary census.
    \item \textbf{Rayleigh:} active ($\lambda_{\rm Rayl}\approx150$\,cm
          at 391\,nm, $\propto\lambda^4$); constitutes an additional
          scattering mechanism beyond ABSLENGTH.
    \item \textbf{No TB counterpart:} April-2026 TB used top readout
          + Tyvek $\neq$ end-only + Mylar.
    \item \textbf{EndTop reference:} EXEC\_07 data, \NEv\ events/position,
          31 positions. Side reflectors $R=\EndtopR$ (BarSkinReflector).
    \item \textbf{Bootstrap:} position-level pairs resampling, C++/OpenMP,
          seed~230123. 68\,\% CI = P16--P84 interval; distinct from
          covariance diagonal errors reported elsewhere.
  \end{itemize}
\end{frame}

\end{document}
"""


def build_tex(pres_dir: pathlib.Path, v: dict) -> str:
    sigma_at = v.get("sigma_t_at_key_positions", {})

    def sg(xkey: str) -> str:
        d = sigma_at.get(str(xkey), {})
        # addendum: use sigma_eq (= sigma(tL-tR)/sqrt(2)); stored as sigma_single_ps
        s = d.get("sigma_eq_ps") or d.get("sigma_single_ps")
        e = d.get("sigma_eq_err_ps") or d.get("sigma_single_err_ps")
        if s is None:
            return r"\texttt{n/a}"
        return f"{float(s):.0f}\\pm{float(e):.0f}"

    att_l = v.get("att_left", {})
    att_r = v.get("att_right", {})

    def _pm(key_val, key_err, d, decimals=1):
        val = d.get(key_val)
        err = d.get(key_err)
        return _pmfmt(val, err, decimals)

    et    = v.get("endtop", {})
    et_av = et.get("available", False)
    et_fl = et.get("fit_left", {})
    lam_tail_et_str = (_pm("tail_lam_cm", "tail_lam_err", et_fl, 1)
                       if et_av else r"\texttt{n/a}")

    rs = v.get("att_tail_range_sensitivity", {})
    def _rs_lam(dmin_key, side):
        d2 = rs.get(f"dmin_{dmin_key}cm", {}).get(side)
        if not d2:
            return r"\texttt{n/a}"
        return _pmfmt(d2.get("lam_cm"), d2.get("lam_err"), 1)
    def _rs_chi(dmin_key, side):
        d2 = rs.get(f"dmin_{dmin_key}cm", {}).get(side)
        if not d2:
            return r"\texttt{n/a}"
        val = d2.get("chi2ndf")
        return _fmt(val, 0) if val else r"\texttt{n/a}"

    # Bootstrap: use C++ OpenMP results (authoritative)
    boot_cpp = att_l.get("bootstrap_cpp", {})
    def _boot(key, stat):
        d2 = boot_cpp.get(key, {})
        if not d2:
            return r"\texttt{n/a}"
        val = d2.get(stat)
        return f"{float(val):.1f}" if val is not None else r"\texttt{n/a}"

    pct_sb   = v.get("photon_budget_pct_surface_bulk")
    pct_esc  = v.get("photon_budget_pct_escaped")
    pct_sipm = v.get("photon_budget_pct_sipm")
    pct_det  = v.get("photon_budget_pct_detected")
    pde_eff  = v.get("photon_budget_pde_eff")

    mylar_r    = float(v.get("mylar_reflectivity", 0.9))
    mylar_loss = 1.0 - mylar_r

    subs = {
        "BAR_LEN":      _fmt(v.get("bar_length_mm"), 0),
        "N_EV":         _fmt_int(v.get("n_events_per_position")),
        "N_POS":        _fmt_int(v.get("n_positions")),
        "LAM_BULK":     _fmt(v.get("lambda_bulk_cm"), 0),
        "SCINT_Y":      _fmt_int(v.get("scint_yield_per_MeV")),
        "PEAK_EM":      _fmt(v.get("peak_emission_nm"), 0),
        "REFR_IDX":     _fmt(v.get("refractive_index"), 2),
        "DENSITY":      _fmt(v.get("density_gcc"), 3),
        "TAU_R":        _fmt(v.get("tau_rise_ns"), 1),
        "TAU_D":        _fmt(v.get("tau_decay_ns"), 1),
        "V_GROUP":      _fmt(v.get("group_velocity_theoretical_mm_ns"), 1),
        "MYLAR_R":      _fmt(mylar_r, 2),
        "MYLAR_LOSS":   _fmt(mylar_loss, 2),
        "MYLAR_SL":     _fmt(v.get("mylar_specular_lobe"), 1),
        "MYLAR_SA":     _fmt(v.get("mylar_sigma_alpha_deg"), 1),
        "PDE_PCT":      _fmt(v.get("pde_peak_frac", 0) * 100, 0),
        "SIPM_MODEL":   str(v.get("sipm_model", "AFBR-S4N66P014M")),
        "SIPM_MODEL_PDE": str(v.get("sipm_model_pde_curve", "AFBR-S4N66P024M")),
        # M1
        "LAM_SINGLE_L": _pm("single_lam_cm", "single_lam_err", att_l),
        "LAM_SINGLE_R": _pm("single_lam_cm", "single_lam_err", att_r),
        "CHI_SINGLE_L": _na_or(att_l.get("single_chi2ndf"), ".0f"),
        "N0_SINGLE_L":  _na_or(att_l.get("single_n0"), ".0f"),
        # M3 (finite-range offset, NOT recirculated floor)
        "LAM_PROMPT_L": _pm("expoff_lam_cm", "expoff_lam_err", att_l),
        "C_OFFSET_L":   _pm("expoff_C", "expoff_C_err", att_l),
        "CHI_EXPOFF_L": _na_or(att_l.get("expoff_chi2ndf"), ".0f"),
        # M2 (full parameters)
        "LAM_SHORT_L":  _pm("dblexp_lam_s_cm", "dblexp_lam_s_err", att_l),
        "LAM_LONG_L":   _pm("dblexp_lam_l_cm", "dblexp_lam_l_err", att_l),
        "AMP_SHORT_L":  _na_or(att_l.get("dblexp_A_s"), ".0f"),
        "AMP_LONG_L":   _na_or(att_l.get("dblexp_A_l"), ".0f"),
        "CHI_M2_L":     _na_or(att_l.get("dblexp_chi2ndf"), ".0f"),
        # M4
        "LAM_TAIL_L":   _pm("tail_lam_cm", "tail_lam_err", att_l),
        "LAM_TAIL_R":   _pm("tail_lam_cm", "tail_lam_err", att_r),
        "CHI_TAIL_L":   _na_or(att_l.get("tail_chi2ndf"), ".1f"),
        "D_TAIL":       str(int(v.get("att_tail_dmin_cm", 40))),
        # NPE keys — two metrics (addendum item 5)
        "NPE_NEAR_L":        _fmt(v.get("npe_left_at_xm690"), 0),
        "NPE_L_X0":          _fmt(v.get("center_point_npe_left"), 1),
        "NPE_R_X0":          _fmt(v.get("center_point_npe_right"), 1),
        "NPE_CENTRAL_L":     _fmt(v.get("central_region_npe_left"), 1),
        "NPE_CENTRAL_R":     _fmt(v.get("central_region_npe_right"), 1),
        "NPE_NEAR_LEFT":     _fmt(v.get("npe_left_at_xm690"), 0),
        "NPE_FAR_R_AT_XNEG": _fmt(v.get("npe_right_at_xm690"), 1),
        "NPE_NEAR_RIGHT":    _fmt(v.get("npe_right_at_x690"), 0),
        "NPE_FAR_L_AT_XPOS": _fmt(v.get("npe_left_at_x690"), 1),
        # EndTop NPE — two metrics
        "NPE_CENTRAL_MYLAR": _fmt(v.get("central_region_npe_left"), 1),
        "NPE_CENTRAL_ET":    (_fmt(v.get("endtop_central_region_npe_left"), 1)
                              if et_av else r"\texttt{n/a}"),
        "NPE_POINT_MYLAR":   _fmt(v.get("center_point_npe_left"), 1),
        "NPE_POINT_ET":      (_fmt(v.get("endtop_center_point_npe_left"), 1)
                              if et_av else r"\texttt{n/a}"),
        # EndTop
        "ENDTOP_R":       _fmt(et.get("reflector_R", 0.98), 2),
        "LAM_TAIL_ET_L":  lam_tail_et_str,
        # sigma_eq (addendum item 10: label as sigma_eq everywhere)
        "SG_M690": sg("-690"),
        "SG_M400": sg("-400"),
        "SG_0":    sg("0"),
        "SG_P400": sg("400"),
        "SG_P690": sg("690"),
        # Apparent velocities
        "V_FPT":  _fmt(v.get("v_eff_fpt_mm_ns"), 1),
        "V_SUM4": _fmt(v.get("v_eff_sum4_mm_ns"), 1),
        "V_T50":  _fmt(v.get("v_eff_t50_mm_ns"), 1),
        # Photon budget
        "PCT_SURF_BULK": _na_or(pct_sb,   ".1f"),
        "PCT_ESC":       _na_or(pct_esc,  ".2f"),
        "PCT_SIPM":      _na_or(pct_sipm, ".2f"),
        "PCT_DET":       _na_or(pct_det,  ".2f"),
        "PDE_EFF":       _na_or(pde_eff,  ".2f"),
        # Range sensitivity
        "TAIL_LAM_30L": _rs_lam("30", "left"),
        "TAIL_LAM_40L": _rs_lam("40", "left"),
        "TAIL_LAM_50L": _rs_lam("50", "left"),
        "TAIL_LAM_30R": _rs_lam("30", "right"),
        "TAIL_LAM_40R": _rs_lam("40", "right"),
        "TAIL_LAM_50R": _rs_lam("50", "right"),
        "TAIL_CHI_30L": _rs_chi("30", "left"),
        "TAIL_CHI_40L": _rs_chi("40", "left"),
        "TAIL_CHI_50L": _rs_chi("50", "left"),
        # Bootstrap (C++/OpenMP, addendum items 2/3)
        "M2_LS_MED":    _boot("M2_lam_s_cm", "median"),
        "M2_LS_P16":    _boot("M2_lam_s_cm", "p16"),
        "M2_LS_P84":    _boot("M2_lam_s_cm", "p84"),
        "M2_LL_MED":    _boot("M2_lam_l_cm", "median"),
        "M2_LL_P16":    _boot("M2_lam_l_cm", "p16"),
        "M2_LL_P84":    _boot("M2_lam_l_cm", "p84"),
        "M4_LT_MED":    _boot("M4_lam_cm", "median"),
        "M4_LT_P16":    _boot("M4_lam_cm", "p16"),
        "M4_LT_P84":    _boot("M4_lam_cm", "p84"),
        "M2_FAIL_FRAC": _fmt(v.get("bootstrap_m2_failure_left_pct", 0.0), 0),
        "BOOT_M4_MED":  _boot("M4_lam_cm", "median"),
        "BOOT_M4_P16":  _boot("M4_lam_cm", "p16"),
        "BOOT_M4_P84":  _boot("M4_lam_cm", "p84"),
        "BOOT_N":       str(v.get("bootstrap_n_replicas", 200)),
        # Tables
        "TAB_PARAMS": _read_tex(pres_dir, "tab_sim_params"),
        "TAB_SIG":    _read_tex(pres_dir, "tab_sigma_t"),
        "TAB_ATT":    _read_tex(pres_dir, "tab_attenuation_fits"),
    }
    return _sub(_TEMPLATE, subs)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pres-dir", default=str(PRES_DIR), type=pathlib.Path,
                    help="Directory with deck_values.json, figures/, tables/")
    ap.add_argument("--skip-compile", action="store_true",
                    help="Write main.tex but skip latexmk")
    args = ap.parse_args()

    pres_dir = args.pres_dir.resolve()
    v   = _load_values(pres_dir)
    tex = build_tex(pres_dir, v)

    tex_path = pres_dir / "main.tex"
    tex_path.write_text(tex)
    print(f"Written: {tex_path}")

    # Unresolved placeholders check
    import re
    remaining = re.findall(r"@[A-Z0-9_]+@", tex)
    if remaining:
        print(f"WARNING: {len(remaining)} unresolved placeholders: {set(remaining)}")

    if args.skip_compile:
        print("Skipping LaTeX compilation (--skip-compile).")
        return

    pdf_path = pres_dir / "main.pdf"
    env = dict(os.environ)

    latexmk = shutil.which("latexmk")
    if latexmk:
        cmd = [latexmk, "-pdf", "-interaction=nonstopmode",
               "-halt-on-error",
               f"-output-directory={pres_dir}", str(tex_path)]
        r = subprocess.run(cmd, cwd=str(pres_dir), capture_output=True, text=True, env=env)
        if r.returncode != 0:
            print("latexmk FAILED. Last 3000 chars of stderr:")
            print(r.stderr[-3000:])
            # also show log
            log_path = pres_dir / "main.log"
            if log_path.exists():
                lines = log_path.read_text().splitlines()
                err_lines = [l for l in lines if "Error" in l or "error" in l or "!" in l]
                print("Log errors:")
                for l in err_lines[-20:]:
                    print(" ", l)
        success = r.returncode == 0
    else:
        r = None
        for _ in range(2):
            r = subprocess.run(
                ["pdflatex", "-interaction=nonstopmode",
                 "-output-directory", str(pres_dir), str(tex_path)],
                cwd=str(pres_dir), capture_output=True, text=True, env=env,
            )
        success = (r is not None and r.returncode == 0)
        if not success and r:
            print("pdflatex FAILED. stderr:", r.stderr[-2000:])

    if success and pdf_path.exists():
        try:
            pg = subprocess.run(["pdfinfo", str(pdf_path)],
                                capture_output=True, text=True)
            pages = next(
                (ln.split(":")[1].strip()
                 for ln in pg.stdout.splitlines()
                 if ln.startswith("Pages:")), "?")
        except Exception:
            pages = "?"
        print(f"PDF compiled: {pdf_path}  ({pages} pages)")
    else:
        print("WARNING: PDF may have failed. Check main.log.")


if __name__ == "__main__":
    main()
