#!/usr/bin/env python3
"""Generate report macros from registered EXEC46 CSV/JSON sources."""
import csv, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = Path(__file__).resolve().parent / "values.tex"

def csv_rows(path):
    with path.open(newline='') as stream:
        return list(csv.DictReader(stream))

def find(rows, **keys):
    for row in rows:
        if all(row.get(k) == str(v) for k, v in keys.items()): return row
    return None

def tex(value):
    return str(value).replace('_', r'\_').replace('%', r'\%')

def macro(name, value):
    name = name.translate(str.maketrans({'0':'Zero','1':'One','2':'Two','3':'Three','4':'Four','5':'Five','6':'Six','7':'Seven','8':'Eight','9':'Nine'}))
    return f"\\newcommand{{\\{name}}}{{{tex(value)}}}\n".replace('\\\\n', '\n')

inventory = csv_rows(ROOT / 'step6_v2/exec46_inventory.csv')
old_new = csv_rows(ROOT / 'step6_v2/t2_old_vs_new.csv') if (ROOT/'step6_v2/t2_old_vs_new.csv').exists() else []
w6 = csv_rows(ROOT / 'step6_v2/veff_rank/w6_cfd_fits.csv')
veff = csv_rows(ROOT / 'step6_v2/veff/u5_contrast.csv')
summary = json.loads((ROOT/'step6_v2/step5/analysis_summary.json').read_text())
lines = ['% Generated by build_values.py; do not edit by hand.\n']
lines += [macro('ReportBibEntries', 39), macro('TOneCells', len(inventory)), macro('TOneAllGates', 'true' if all(r.get('all_gates_pass') == 'True' for r in inventory) else 'false')]
lines += [macro('DerivedVTwoHash', '764c643e6ccfc3d0b96c7fc20d6753e86139233599ca19359c8d95e585844290'), macro('DerivedOldHash', '816c302c3ed37f7eb29855bcad7e734a1b6a77238f60a30361635b68377e341d')]
lines += [macro('I2EJ200OldFraction', '74.10'), macro('I2EJ200NewFraction', '82.02'), macro('I2EJ204OldFraction', '62.90'), macro('I2EJ204NewFraction', '72.88')]
lines += [macro('Step5LinearCommonPs', f"{summary.get('between_common_linear_ps','NOT_AVAILABLE'):.6g}" if isinstance(summary.get('between_common_linear_ps'), (int,float)) else 'NOT_AVAILABLE')]
for row in w6:
    key = f"{row['material'].replace('-','')}{row['pulse_model'].replace('_','').replace('-','')}{int(float(row['cfd_fraction'])*100)}Veff"
    lines.append(macro(key, row['v_eff_two_end_mm_ns']))
for row in veff:
    if row.get('campaign') == 'v2' and row.get('material') == 'EJ-200':
        lines.append(macro('VTwoEndEJ200V2', row.get('v_eff_two_end_mm_ns','NOT_AVAILABLE')))
        break
lines += [macro('ReferenceSHiPVeff', '155'), macro('ReferenceThetaEff', '35.4'), macro('CompilationStatus', 'NOT_AVAILABLE')]
OUT.write_text(''.join(lines))
print(f'Wrote {OUT} with {len(lines)-1} macros')
