# endtop scan — x = 600 mm — 5000 events — feat/endtop-sslg4
# index [28/31]  seeds: 737243 964459
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/run/numberOfThreads 24
/det/readout EndTop
/det/scintillator OPSC-101
/sipm/model AFBR-S4N66P024M
/run/initialize
/sipm/jitterSigma 0 ns
/gun/particle mu-
/gun/energy 1 GeV
/muon/angle 0
/random/setSeeds 737243 964459
/muon/gunX 600 mm
/run/beamOn 5000
