# endtop scan — x = -450 mm — 5000 events — feat/endtop-sslg4
# index [07/31]  seeds: 716054 922102
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/run/numberOfThreads 24
/det/readout EndTop
/det/scintillator OPSC-101
/sipm/model AFBR-S4N66P024M
/run/initialize
/sipm/jitterSigma 0 ns
/gun/particle mu-
/gun/energy 1 GeV
/muon/angle 0
/random/setSeeds 716054 922102
/muon/gunX -450 mm
/run/beamOn 5000
