# endtop scan — x = -200 mm — 5000 events — feat/endtop-sslg4
# index [12/31]  seeds: 721099 932187
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/run/numberOfThreads 24
/det/readout EndTop
/det/scintillator OPSC-101
/sipm/model AFBR-S4N66P024M
/run/initialize
/sipm/jitterSigma 0 ns
/gun/particle mu-
/gun/energy 1 GeV
/muon/angle 0
/random/setSeeds 721099 932187
/muon/gunX -200 mm
/run/beamOn 5000
