#ifndef TIMING_SYMMETRY_DIAGNOSTIC_FIGURES_C
#define TIMING_SYMMETRY_DIAGNOSTIC_FIGURES_C
#include <TCanvas.h>
#include <TFile.h>
#include <TF1.h>
#include <TGraphAsymmErrors.h>
#include <TGraphErrors.h>
#include <TH1D.h>
#include <TH2D.h>
#include <TLatex.h>
#include <TLegend.h>
#include <TLine.h>
#include <TNamed.h>
#include <TPad.h>
#include <TPaveText.h>
#include <TStyle.h>

#include <algorithm>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <map>
#include <numeric>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace diag {
struct Table{std::vector<std::string>h;std::vector<std::map<std::string,std::string>>r;};
std::vector<std::string>split(const std::string&s){std::stringstream ss(s);std::string x;std::vector<std::string>v;while(std::getline(ss,x,','))v.push_back(x);return v;}
Table read(const std::string&p){std::ifstream f(p);if(!f)throw std::runtime_error("cannot open "+p);Table t;std::string s;std::getline(f,s);t.h=split(s);while(std::getline(f,s)){if(s.empty())continue;auto v=split(s);std::map<std::string,std::string>r;for(size_t j=0;j<t.h.size()&&j<v.size();j++)r[t.h[j]]=v[j];t.r.push_back(r);}return t;}
double d(const std::map<std::string,std::string>&r,const std::string&k){return std::stod(r.at(k));}int i(const std::map<std::string,std::string>&r,const std::string&k){return std::stoi(r.at(k));}
void style(){gStyle->SetOptStat(0);gStyle->SetOptFit(0);gStyle->SetTitleFont(42,"XYZ");gStyle->SetLabelFont(42,"XYZ");gStyle->SetLegendFont(42);gStyle->SetTextFont(42);gStyle->SetTitleSize(.05,"XYZ");gStyle->SetLabelSize(.042,"XYZ");gStyle->SetPadLeftMargin(.14);gStyle->SetPadBottomMargin(.14);gStyle->SetPadTopMargin(.06);gStyle->SetPadRightMargin(.04);}
int col(const std::string&m){return m=="EJ-200"?kBlue+1:m=="EJ-204"?kGreen+2:kRed+1;}
std::string key(const std::string&m,int a){std::string k=m+"_"+std::to_string(a)+"_median";std::replace(k.begin(),k.end(),'-','_');return k;}
void meta(const std::string&n,const std::string&q,const std::string&m){std::ofstream f("figures/"+n+".meta.json");f<<"{\n  \"figure\": \""<<n<<"\",\n  \"created_utc\": \"2026-09-14\",\n  \"question\": \""<<q<<"\",\n  \"input\": \"current corrected-transport timing events, N=10000/cell\",\n  \"method\": \""<<m<<"\",\n  \"generator\": \"CERN ROOT macro macros/"<<n<<".C\"\n}\n";}
void prov(TFile&f,const std::string&m){f.cd();TNamed s("source","presentations/v9/sources/timing_events.root; current corrected transport; no new simulation");TNamed x("method",m.c_str());s.Write();x.Write();}

void fitGrid(const std::string&mat,const std::string&name){style();auto wt=read("sources/timing_widths.csv"),ft=read("sources/timing_fit_stability.csv");std::map<int,std::map<std::string,std::string>> row,fitrow;for(auto&r:wt.r)if(r.at("material")==mat&&r.at("estimator")=="first_pe")row[i(r,"x_mm")]=r;for(auto&r:ft.r)if(r.at("material")==mat&&r.at("estimator")=="first_pe"&&r.at("study")=="baseline")fitrow[i(r,"x_mm")]=r;TFile in("sources/timing_fit_stability.root","READ"),out(("figures/"+name+".root").c_str(),"RECREATE");std::vector<int>xs={-650,-500,-200,0,200,500,650};TCanvas c(name.c_str(),"",1450,760);c.Divide(4,2,.002,.002);for(size_t j=0;j<xs.size();j++){c.cd(j+1);gPad->SetLeftMargin(.15);gPad->SetBottomMargin(.15);std::string id=row[xs[j]].at("cell_id");auto*ha=(TH1D*)in.Get((id+"/t0_histogram").c_str());auto*fa=(TF1*)in.Get((id+"/gaussian_fit").c_str());if(!ha||!fa)throw std::runtime_error("missing fit objects "+id);double med=d(row[xs[j]],"median_ns"),norm=ha->Integral("width");auto*h=new TH1D(("hist_"+id).c_str(),"",ha->GetNbinsX(),-.32,.32);for(int b=0;b<=ha->GetNbinsX()+1;b++){h->SetBinContent(b,ha->GetBinContent(b)/norm);h->SetBinError(b,ha->GetBinError(b)/norm);}h->SetDirectory(&out);double shift=fa->GetParameter(1)-med;auto*f=new TF1(("fit_"+id).c_str(),"gaus",fa->GetXmin()-med,fa->GetXmax()-med);f->SetParameters(fa->GetParameter(0)/norm,shift,fa->GetParameter(2));f->SetLineColor(kRed+1);f->SetLineWidth(3);h->SetLineColor(kBlue+1);h->GetXaxis()->SetTitle("T_{0}-median [ns]");h->GetYaxis()->SetTitle("density");h->Draw("HIST");f->Draw("SAME");auto&fr=fitrow[xs[j]];auto*b=new TPaveText(.14,.52,.82,.92,"NDC");b->SetFillColor(kWhite);b->SetBorderSize(1);b->SetTextAlign(12);b->SetTextSize(.034);b->AddText(Form("x=%+d mm; #mu_{fit}=%.4f ns",xs[j],d(fr,"fit_mu_ns")));b->AddText(Form("#sigma_{G}=%.2f#pm%.2f ps",1000*d(row[xs[j]],"baseline_sigma_G_ns"),1000*d(row[xs[j]],"baseline_sigma_G_err_ns")));b->AddText(Form("RMS=%.2f; q_{68}=%.2f ps",1000*d(row[xs[j]],"RMS_ns"),1000*d(row[xs[j]],"sigma68_ns")));b->AddText(Form("fit=[%.3f,%.3f] ns",d(fr,"fit_lo_ns"),d(fr,"fit_hi_ns")));b->AddText(Form("#chi^{2}/ndf=%.2f; status=%d",d(row[xs[j]],"baseline_chi2")/i(row[xs[j]],"baseline_ndf"),i(row[xs[j]],"baseline_fit_status")));b->Draw();out.cd();h->Write();f->Write();}
 c.cd(8);gPad->Range(0,0,1,1);TLatex tx;tx.SetTextSize(.06);tx.DrawLatex(.10,.78,(mat+": common display policy").c_str());tx.SetTextSize(.048);tx.DrawLatex(.10,.61,"4 ps bins; relative range #pm0.32 ns");tx.DrawLatex(.10,.50,"unit-area normalization");tx.DrawLatex(.10,.39,"Gaussian window: median #pm2q_{68}");tx.DrawLatex(.10,.28,"Minuit2/Migrad; covariance quality 3");c.SaveAs(("figures/"+name+".pdf").c_str());out.cd();c.Write();prov(out,"Baseline 4 ps histogram; median +/-0.32 ns; chi2 Gaussian fit in median +/-2q68; exact stored parameters and covariance");out.Close();meta(name,"What distribution produces each timing-width point?","Seven normalized T0 histograms with identical relative range/binning and stored baseline Gaussian fits");}

void mirror(const std::string&mat,const std::string&name){style();TFile in("sources/mirror_diagnostics.root","READ"),out(("figures/"+name+".root").c_str(),"RECREATE");TCanvas c(name.c_str(),"",1400,760);c.Divide(3,2,.004,.004);int p=0;for(int a:{200,500,650}){std::string k=key(mat,a);auto*hn=(TH1D*)in.Get((k+"/minus_density").c_str());auto*hp=(TH1D*)in.Get((k+"/plus_density").c_str());auto*hd=(TH1D*)in.Get((k+"/plus_minus_difference").c_str());if(!hn||!hp||!hd)throw std::runtime_error("missing mirror "+k);c.cd(++p);gPad->SetLeftMargin(.15);auto*n=(TH1D*)hn->Clone(Form("minus_%d",a));auto*q=(TH1D*)hp->Clone(Form("plus_%d",a));n->SetDirectory(&out);q->SetDirectory(&out);n->SetLineColor(kBlue+1);q->SetLineColor(kRed+1);n->SetLineWidth(3);q->SetLineWidth(3);n->SetMaximum(7.2);n->GetXaxis()->SetTitle("T_{0}-median [ns]");n->GetYaxis()->SetTitle("density");n->Draw("HIST");q->Draw("HIST SAME");auto*leg=new TLegend(.61,.70,.90,.90);leg->SetBorderSize(0);leg->SetFillStyle(0);leg->AddEntry(n,Form("x=-%d mm",a),"l");leg->AddEntry(q,Form("x=+%d mm",a),"l");leg->Draw();auto*tx=new TLatex();tx->SetNDC();tx->SetTextSize(.043);tx->DrawLatex(.18,.86,Form("|x|=%d mm",a));c.cd(p+3);gPad->SetLeftMargin(.15);auto*z=(TH1D*)hd->Clone(Form("difference_%d",a));z->SetDirectory(&out);z->SetLineColor(kBlack);z->SetLineWidth(2);z->SetMinimum(-2.2);z->SetMaximum(2.2);z->GetXaxis()->SetTitle("T_{0}-median [ns]");z->GetYaxis()->SetTitle("density(+x)-density(-x)");z->Draw("HIST");TLine line(-.32,0,.32,0);line.SetLineStyle(2);line.Draw();}c.SaveAs(("figures/"+name+".pdf").c_str());out.cd();c.Write();prov(out,"Median-centered mirrored pairs; identical [-0.32,+0.32] ns, 4 ps bins, unit density; lower panels are plus-minus differences");out.Close();meta(name,"Do mirrored T0 distributions have different shapes?","Median-centered normalized overlays and density differences using common range, bins and y limits");}

void widthMethods(const std::string&mat,const std::string&name){style();auto t=read("sources/timing_widths.csv");std::vector<double>x,e0,sg,sge,rms,rmse,q,qe;for(auto&r:t.r)if(r.at("material")==mat&&r.at("estimator")=="first_pe"){x.push_back(d(r,"x_mm"));e0.push_back(0);sg.push_back(1000*d(r,"baseline_sigma_G_ns"));sge.push_back(1000*d(r,"baseline_sigma_G_err_ns"));rms.push_back(1000*d(r,"RMS_ns"));rmse.push_back(1000*d(r,"RMS_bootstrap_err_ns"));q.push_back(1000*d(r,"sigma68_ns"));qe.push_back(1000*d(r,"sigma68_bootstrap_err_ns"));}TCanvas c(name.c_str(),"",930,650);TGraphErrors gs(x.size(),x.data(),sg.data(),e0.data(),sge.data()),gr(x.size(),x.data(),rms.data(),e0.data(),rmse.data()),gq(x.size(),x.data(),q.data(),e0.data(),qe.data());gs.SetName("sigma_G");gr.SetName("RMS");gq.SetName("sigma68");gs.SetMarkerStyle(20);gr.SetMarkerStyle(21);gq.SetMarkerStyle(22);gs.SetMarkerColor(kRed+1);gr.SetMarkerColor(kBlue+1);gq.SetMarkerColor(kGreen+2);gs.SetLineColor(kRed+1);gr.SetLineColor(kBlue+1);gq.SetLineColor(kGreen+2);for(auto*g:{&gs,&gr,&gq}){g->SetLineWidth(3);g->SetMarkerSize(1.25);}gs.SetTitle("");gs.GetXaxis()->SetTitle("Muon position x [mm]");gs.GetYaxis()->SetTitle("Width of T_{0} [ps]");double ymin=*std::min_element(q.begin(),q.end())-4,ymax=*std::max_element(rms.begin(),rms.end())+5;gs.GetYaxis()->SetRangeUser(ymin,ymax);gs.Draw("ALP");gr.Draw("LP SAME");gq.Draw("LP SAME");TLegend leg(.16,.69,.42,.89);leg.SetBorderSize(0);leg.SetFillStyle(0);leg.AddEntry(&gs,"Gaussian core","lp");leg.AddEntry(&gr,"global RMS","lp");leg.AddEntry(&gq,"q_{68}","lp");leg.Draw();TLatex tx;tx.SetNDC();tx.SetTextSize(.043);tx.DrawLatex(.68,.86,mat.c_str());tx.SetTextSize(.032);tx.DrawLatex(.48,.18,"RMS/q_{68}: 500 bootstrap replicas");c.SaveAs(("figures/"+name+".pdf").c_str());TFile out(("figures/"+name+".root").c_str(),"RECREATE");gs.Write();gr.Write();gq.Write();c.Write();prov(out,"Baseline Gaussian core versus global RMS and q68; fixed 500-replica bootstrap seed series");out.Close();meta(name,"Is the timing-width asymmetry physical or definition-dependent?","Gaussian, global RMS and robust q68 curves with statistical uncertainties");}

void fitStabilityEJ200(){style();auto t=read("sources/timing_fit_stability.csv");std::vector<int>xis={-650,-500,-200,0,200,500,650};TCanvas c("fit_stability_EJ200","",1200,820);c.Divide(2,2,.01,.01);TFile out("figures/fit_stability_EJ200.root","RECREATE");auto panelEnvelope=[&](int pad,const std::string&study,const char*title){std::vector<double>x,y,exl,exh,eyl,eyh;for(int xx:xis){std::vector<double>v;for(auto&r:t.r)if(r.at("material")=="EJ-200"&&r.at("study")==study&&i(r,"x_mm")==xx)v.push_back(1000*d(r,"fit_sigma_ns"));double mid=std::accumulate(v.begin(),v.end(),0.0)/v.size();x.push_back(xx);y.push_back(mid);exl.push_back(0);exh.push_back(0);eyl.push_back(mid-*std::min_element(v.begin(),v.end()));eyh.push_back(*std::max_element(v.begin(),v.end())-mid);}c.cd(pad);gPad->SetLeftMargin(.16);auto*g=new TGraphAsymmErrors(x.size(),x.data(),y.data(),exl.data(),exh.data(),eyl.data(),eyh.data());g->SetName((study+"_envelope").c_str());g->SetMarkerStyle(20);g->SetLineColor(kBlue+1);g->SetMarkerColor(kBlue+1);g->SetTitle("");g->GetXaxis()->SetTitle("x [mm]");g->GetYaxis()->SetTitle(title);g->GetYaxis()->SetRangeUser(70,91);g->Draw("AP");out.cd();g->Write();};panelEnvelope(1,"binning_offset","#sigma_{G} [ps]: 2/4/8 ps bins + offsets");panelEnvelope(2,"fit_window","#sigma_{G} [ps]: 1.5/2/2.5 q_{68} windows");
  c.cd(3);gPad->SetLeftMargin(.16);TH2D frame("method_frame","",10,-700,700,10,70,91);frame.GetXaxis()->SetTitle("x [mm]");frame.GetYaxis()->SetTitle("#sigma_{G} [ps]: fit method");frame.Draw();TLegend leg(.16,.68,.56,.89);leg.SetBorderSize(0);leg.SetFillStyle(0);int colors[3]={kRed+1,kBlue+1,kGreen+2},marks[3]={20,21,22},idx=0;for(auto method:{"chi2","binned_likelihood","RooFit_unbinned"}){std::vector<double>x,y,ex,ey;for(int xx:xis)for(auto&r:t.r)if(r.at("material")=="EJ-200"&&r.at("study")=="fit_method"&&r.at("method")==method&&i(r,"x_mm")==xx){x.push_back(xx);y.push_back(1000*d(r,"fit_sigma_ns"));ex.push_back(0);ey.push_back(1000*d(r,"fit_sigma_err_ns"));}auto*g=new TGraphErrors(x.size(),x.data(),y.data(),ex.data(),ey.data());g->SetName((std::string("method_")+method).c_str());g->SetMarkerStyle(marks[idx]);g->SetMarkerColor(colors[idx]);g->SetLineColor(colors[idx]);g->SetLineWidth(2);g->Draw("LP SAME");leg.AddEntry(g,method,"lp");out.cd();g->Write();idx++;}leg.Draw();
  c.cd(4);gPad->Range(0,0,1,1);TLatex tx;tx.SetTextSize(.062);tx.DrawLatex(.10,.84,"Initialization A/B/C");tx.SetTextSize(.050);tx.DrawLatex(.10,.71,"Maximum #Delta#sigma: <10^{-6} ps");tx.DrawLatex(.10,.59,"All fits: status 0, covariance quality 3");tx.DrawLatex(.10,.43,"Window spread: median 3.40 ps");tx.DrawLatex(.10,.34,"Window spread: maximum 8.67 ps");tx.DrawLatex(.10,.20,"Fit errors are typically 0.8--0.9 ps.");c.SaveAs("figures/fit_stability_EJ200.pdf");out.cd();c.Write();prov(out,"EJ-200 sensitivity envelopes and method curves from timing_fit_stability.csv");out.Close();meta("fit_stability_EJ200","Which technical choice moves the Gaussian width?","Binning/offset and window envelopes, chi2/likelihood/unbinned methods, and initialization convergence");}

void mean5EJ230(){style();auto t=read("sources/timing_widths.csv");std::vector<double>x,e,first,fe,m5,m5e;for(int xx:{-650,-500,-200,0,200,500,650})for(auto&r:t.r)if(r.at("material")=="EJ-230"&&i(r,"x_mm")==xx){if(r.at("estimator")=="first_pe"){x.push_back(xx);e.push_back(0);first.push_back(1000*d(r,"sigma68_ns"));fe.push_back(1000*d(r,"sigma68_bootstrap_err_ns"));}else{m5.push_back(1000*d(r,"sigma68_ns"));m5e.push_back(1000*d(r,"sigma68_bootstrap_err_ns"));}}TCanvas c("mean5_EJ230","",930,650);TGraphErrors g1(x.size(),x.data(),first.data(),e.data(),fe.data()),g5(x.size(),x.data(),m5.data(),e.data(),m5e.data());g1.SetName("first_pe_sigma68");g5.SetName("mean_first_5_sigma68");g1.SetMarkerStyle(20);g5.SetMarkerStyle(22);g1.SetMarkerColor(kRed+1);g5.SetMarkerColor(kBlue+1);g1.SetLineColor(kRed+1);g5.SetLineColor(kBlue+1);g1.SetLineWidth(3);g5.SetLineWidth(3);g1.SetTitle("");g1.GetXaxis()->SetTitle("Muon position x [mm]");g1.GetYaxis()->SetTitle("#sigma_{68}(T_{0}) [ps]");g1.GetYaxis()->SetRangeUser(56,90);g1.Draw("ALP");g5.Draw("LP SAME");TLegend leg(.16,.72,.47,.89);leg.SetBorderSize(0);leg.SetFillStyle(0);leg.AddEntry(&g1,"first PE per END","lp");leg.AddEntry(&g5,"mean first 5 PE per END","lp");leg.Draw();TLatex tx;tx.SetNDC();tx.SetTextSize(.038);tx.DrawLatex(.54,.85,"EJ-230: 59.92 #pm 0.62 ps at x=0");tx.DrawLatex(.54,.79,"all mirrored mean-5 #sigma_{68}: |z| < 0.65");c.SaveAs("figures/mean5_EJ230.pdf");TFile out("figures/mean5_EJ230.root","RECREATE");g1.Write();g5.Write();c.Write();prov(out,"EJ-230 first-PE and arithmetic mean-first-five END estimators using primary q68 with 500 event bootstraps");out.Close();meta("mean5_EJ230","Does the mean-first-five improvement persist away from x=0?","Seven-position first-PE versus mean-first-five comparison using robust q68 and 500 event bootstraps");}

void sigma68All(){style();auto t=read("sources/timing_widths.csv");TCanvas c("sigma68_vs_x","",930,650);TFile out("figures/sigma68_vs_x.root","RECREATE");TLegend leg(.16,.70,.40,.89);leg.SetBorderSize(0);leg.SetFillStyle(0);int n=0;for(auto mat:{std::string("EJ-200"),std::string("EJ-204"),std::string("EJ-230")}){std::vector<double>x,y,ex,ey;for(int xx:{-650,-500,-200,0,200,500,650})for(auto&r:t.r)if(r.at("material")==mat&&r.at("estimator")=="first_pe"&&i(r,"x_mm")==xx){x.push_back(xx);y.push_back(1000*d(r,"sigma68_ns"));ex.push_back(0);ey.push_back(1000*d(r,"sigma68_bootstrap_err_ns"));}auto*g=new TGraphErrors(x.size(),x.data(),y.data(),ex.data(),ey.data());g->SetName(("sigma68_"+mat).c_str());g->SetMarkerStyle(20+n);g->SetMarkerSize(1.25);g->SetMarkerColor(col(mat));g->SetLineColor(col(mat));g->SetLineWidth(3);g->SetTitle("");if(n==0){g->GetXaxis()->SetTitle("Muon position x [mm]");g->GetYaxis()->SetTitle("#sigma_{68}(T_{0}) [ps]");g->GetYaxis()->SetRangeUser(63,90);g->Draw("ALP");}else g->Draw("LP SAME");leg.AddEntry(g,mat.c_str(),"lp");out.cd();g->Write();n++;}leg.Draw();TLatex tx;tx.SetNDC();tx.SetTextSize(.035);tx.DrawLatex(.55,.18,"500 event-bootstrap replicas");c.SaveAs("figures/sigma68_vs_x.pdf");out.cd();c.Write();prov(out,"Primary robust timing resolution q68=(q84-q16)/2 for all 21 cells; 500 deterministic event bootstraps");out.Close();meta("sigma68_vs_x","What robust timing resolution does the corrected optical model predict?","q68=(q84-q16)/2 for first-PE T0; 500 deterministic event-bootstrap replicas");}
}
#endif
