#!/usr/bin/env python3
"""
build_deck.py — Generate and compile the Beamer presentation
  "End-only + Mylar-wrapped EJ-204 bar: optical simulation study"

Usage:
  python build_deck.py [--data-dir PATH] [--out-dir PATH] [--skip-analysis] [--no-compile]

  --data-dir       ROOT of simulation output
                   (default: /home/reriosto/SHiP/t0minidaq/endonly_mylar_20260614)
  --out-dir        Directory for output files (default: same dir as this script)
  --skip-analysis  Use existing analysis outputs (do not re-run analysis_endonly_mylar.py)
  --no-compile     Generate main.tex but skip LaTeX compilation

All numerical values in main.tex come from deck_values.json (no hardcoding).
The LaTeX template uses @PLACEHOLDER@ markers to avoid Python f-string / LaTeX
brace conflicts.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import pathlib
import shutil
import subprocess
import sys

HERE = pathlib.Path(__file__).parent


# ── helpers ───────────────────────────────────────────────────────────────────

def _run_analysis(data_dir: pathlib.Path, out_dir: pathlib.Path) -> None:
    script = HERE / "analysis_endonly_mylar.py"
    if not script.exists():
        sys.exit(f"ERROR: analysis_endonly_mylar.py not found at {script}")
    print("Running analysis...")
    subprocess.run([sys.executable, str(script),
                    "--data-dir", str(data_dir),
                    "--out-dir", str(out_dir)], check=True)


def _load_values(out_dir: pathlib.Path) -> dict:
    p = out_dir / "deck_values.json"
    if not p.exists():
        sys.exit(f"ERROR: deck_values.json not found. Run without --skip-analysis first.")
    with open(p) as f:
        return json.load(f)


def _load_caption(fig_path: pathlib.Path) -> str:
    txt = fig_path.with_suffix(".txt")
    return txt.read_text().strip() if txt.exists() else fig_path.stem.replace("_", " ")


def _fmt(v, decimals: int = 1, unit: str = "") -> str:
    if v is None or (isinstance(v, float) and not math.isfinite(v)):
        return r"\texttt{TODO}"
    s = f"{float(v):.{decimals}f}"
    return s + (r"\," + unit if unit else "")


def _fmt_int(v) -> str:
    if v is None:
        return r"\texttt{TODO}"
    return f"{int(v):,}"


def _sub(template: str, subs: dict[str, str]) -> str:
    """Replace all @KEY@ markers in template with subs[KEY]."""
    for key, val in subs.items():
        template = template.replace(f"@{key}@", val)
    return template


def _read_tex(out_dir: pathlib.Path, tab_key: str, tab_map: dict) -> str:
    rel = tab_map.get(tab_key, f"tables/{tab_key}")
    p = out_dir / (rel + ".tex")
    return p.read_text() if p.exists() else f"% {tab_key} not found\n"


# ── LaTeX template (uses @PLACEHOLDER@ to avoid f-string brace issues) ───────

_TEMPLATE = r"""% auto-generated by build_deck.py — do not edit by hand
% All numerical values sourced from deck_values.json
\documentclass[aspectratio=169,10pt]{beamer}

\usetheme{default}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage{amsmath}
\usepackage{xcolor}
\usepackage{siunitx}

\definecolor{shipblue}{RGB}{20,74,130}
\definecolor{warnorange}{RGB}{210,105,30}
\setbeamercolor{structure}{fg=shipblue}
\setbeamercolor{alerted text}{fg=warnorange}
\setbeamertemplate{navigation symbols}{}
\setbeamertemplate{footline}[frame number]

% ── macros sourced from deck_values.json ──────────────────────────────────────
\newcommand{\BarLen}{@BAR_LEN@}
\newcommand{\NEv}{@N_EV@}
\newcommand{\NPos}{@N_POS@}
\newcommand{\LamBulk}{@LAM_BULK@}
\newcommand{\LamEffL}{\ensuremath{@LAM_EFF_L@}\,cm}
\newcommand{\LamEffR}{\ensuremath{@LAM_EFF_R@}\,cm}
\newcommand{\LamEffC}{\ensuremath{@LAM_EFF_C@}\,cm}
\newcommand{\MylarR}{@MYLAR_R@}
\newcommand{\MylarSL}{@MYLAR_SL@}
\newcommand{\MylarSA}{@MYLAR_SA@}
\newcommand{\PDEpeak}{@PDE_PCT@\%}
\newcommand{\SiPMModel}{@SIPM_MODEL@}
\newcommand{\SiPMModelPDE}{@SIPM_MODEL_PDE@}
\newcommand{\ScintYield}{@SCINT_Y@\,$\gamma$/MeV}
\newcommand{\TauRise}{@TAU_R@\,ns}
\newcommand{\TauDecay}{@TAU_D@\,ns}
\newcommand{\SigmaAtMsixnine}{@SG_M690@\,ps}
\newcommand{\SigmaAtMfour}{@SG_M400@\,ps}
\newcommand{\SigmaAtZero}{@SG_0@\,ps}
\newcommand{\SigmaAtFour}{@SG_P400@\,ps}
\newcommand{\SigmaAtSixnine}{@SG_P690@\,ps}
\newcommand{\VeffFPT}{@V_FPT@\,mm/ns}
\newcommand{\VeffSUMfour}{@V_SUM4@\,mm/ns}
\newcommand{\VeffTfifty}{@V_T50@\,mm/ns}
\newcommand{\BudgetEsc}{@PCT_ESC@\%}
\newcommand{\BudgetSiPM}{@PCT_SIPM@\%}
\newcommand{\BudgetDet}{@PCT_DET@\%}
\newcommand{\NpeLeftZero}{@NPE_L_X0@}
\newcommand{\NpeRightZero}{@NPE_R_X0@}
\newcommand{\NpeLeftNear}{@NPE_L_690@}
\newcommand{\NpeRightNear}{@NPE_R_690@}

\title[End-only + Mylar EJ-204]{%
  End-only + Mylar-wrapped EJ-204 bar:\\
  Optical simulation study}
\subtitle{Geant4 11.4.0 / SSLG4-OPSim}
\author{R.\ R\'ios (ULS)}
\institute{SHiP Collaboration Meeting}
\date{2026-06-14}

\begin{document}

% ─── FRAME 1: Title ───────────────────────────────────────────────────────────
\begin{frame}
  \titlepage
\end{frame}

% ─── FRAME 2: Motivation & scope ─────────────────────────────────────────────
\begin{frame}{Motivation \& scope}
  \begin{columns}[T]
    \column{0.55\textwidth}
    \begin{itemize}
      \item \textbf{Deliberate simplification:} readout \emph{only} at the
            two ends ($\pm X$ faces); all other faces wrapped in Mylar.
      \item \textbf{Goals:}
        \begin{itemize}
          \item Isolate end-readout contribution.
          \item Verify exponential attenuation with Mylar recirculation.
          \item Benchmark the SUM4 timing estimator on a clean geometry.
        \end{itemize}
      \item \NPos\ beam positions ($x=-690\ldots+690$\,mm),
            \NEv\ $\mu^-$ events per position.
    \end{itemize}
    \column{0.43\textwidth}
    \begin{block}{This study}
      \textbf{End-only + Mylar} = extreme limit.
      Photons either exit to an end SiPM or are absorbed by Mylar
      after multiple reflections.
    \end{block}
    \begin{alertblock}{\small No TB counterpart}
      \small This configuration has \alert{no direct test-beam counterpart}
      (April-2026 TB used top readout + Tyvek).
    \end{alertblock}
    \begin{alertblock}{\small Electronic jitter not included}
      \small SPTR $\oplus$ FastIC jitter are post-processing steps,
      not folded into $\sigma_t$ shown here.
    \end{alertblock}
  \end{columns}
\end{frame}

% ─── FRAME 3: Geometry & simulation setup ────────────────────────────────────
\begin{frame}{Geometry \& simulation setup}
  \begin{columns}[T]
    \column{0.55\textwidth}
    \begin{itemize}
      \item \textbf{Bar:} EJ-204 (OPSC-101),
            $\BarLen \times 60 \times 10$\,mm$^3$.
      \item \textbf{Longitudinal axis:} $X$ ($-700$ to $+700$\,mm).
      \item \textbf{End-left SiPMs} (IDs 0--7): $-X$ face.
            \textbf{End-right SiPMs} (IDs 8--15): $+X$ face.
      \item \textbf{Wrapping:} Mylar on $\pm Y$ and $\pm Z$ faces;
            $R=\MylarR$, specular lobe $=\MylarSL$,
            $\sigma_\alpha=\MylarSA^\circ$.
      \item \textbf{Readout:} SUM4 leading-edge at 4\,PE;
            groups $\{0\text{--}3\}/\{4\text{--}7\}$ (left),
            $\{8\text{--}11\}/\{12\text{--}15\}$ (right).
      \item \textbf{Estimator:}
            $\sigma_\mathrm{single} = \sigma_{LR}/\sqrt{2}$.
      \item \textbf{Beam:} $\mu^-$, 1\,GeV, normal incidence.
    \end{itemize}
    \column{0.43\textwidth}
    \begin{block}{SiPM model}
      \textbf{\SiPMModel} (single-element, Broadcom).\\
      PDE \PDEpeak\ @ 420\,nm.\\
      \small\textit{Note: macro uses \texttt{\SiPMModelPDE} string
      only for the PDE curve; physical device is the single-element P014M.}
    \end{block}
    \begin{block}{Software stack}
      Geant4 11.4.0; SSLG4/OPSim.
    \end{block}
  \end{columns}
\end{frame}

% ─── FRAME 4: Physics inputs ──────────────────────────────────────────────────
\begin{frame}{Physics inputs}
  \begin{columns}[T]
    \column{0.50\textwidth}
    \begin{block}{EJ-204 (OPSC-101)}
      \small
      \begin{tabular}{lll}
        \toprule
        Property & Value & Unit \\
        \midrule
        Scint.\ yield & \ScintYield & \\
        Rise time $\tau_r$ & \TauRise & \\
        Decay time $\tau_d$ & \TauDecay & \\
        Bulk atten.\ $\lambda$ & \LamBulk & cm \\
        \bottomrule
      \end{tabular}
    \end{block}
    \begin{block}{Mylar wrapping ($\pm Y,\pm Z$)}
      \small $R=\MylarR$; specular lobe $=\MylarSL$;
      $\sigma_\alpha=\MylarSA^\circ$
    \end{block}
    \column{0.48\textwidth}
    \begin{block}{SiPM: \SiPMModel}
      \small
      \begin{tabular}{ll}
        \toprule
        Property & Value \\
        \midrule
        PDE (peak) & \PDEpeak\ @ 420\,nm \\
        Type & Single-element \\
        PDE curve model & \SiPMModelPDE \\
        \bottomrule
      \end{tabular}
    \end{block}
    \begin{block}{Scan parameters}
      \small \NPos\ positions; \NEv\ events each;
      $\mu^-$ 1\,GeV normal incidence.
    \end{block}
  \end{columns}
\end{frame}

% ─── FRAME 5: Photon count vs position ────────────────────────────────────────
\begin{frame}{Photon count at ends vs.\ beam position}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_npe_vs_x.png}
    \column{0.33\textwidth}
    \begin{block}{Key values}
      \small
      At $x=0$:\\
      $\langle N^\mathrm{L}_\mathrm{pe}\rangle = \NpeLeftZero$\,PE\\
      $\langle N^\mathrm{R}_\mathrm{pe}\rangle = \NpeRightZero$\,PE
      \medskip

      Near $x=-690$\,mm:\\
      Left $\approx \NpeLeftNear$\,PE\\
      Right $\approx \NpeRightNear$\,PE
    \end{block}
    \begin{alertblock}{\small Mylar role}
      \small Without Mylar the far-end count would collapse;
      Mylar recirculates photons and sustains far-end yield.
      Log scale shows exponential falloff.
    \end{alertblock}
  \end{columns}
\end{frame}

% ─── FRAME 6: Attenuation curve & λ_eff ──────────────────────────────────────
\begin{frame}{Attenuation curve \& effective attenuation length $\lambda_\mathrm{eff}$}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_attenuation.png}
    \column{0.33\textwidth}
    \begin{block}{Fit results}
      \small
      \begin{tabular}{ll}
        \toprule
        Side & $\lambda_\mathrm{eff}$ (cm) \\
        \midrule
        Left     & \LamEffL \\
        Right    & \LamEffR \\
        Combined & \LamEffC \\
        \bottomrule
      \end{tabular}
    \end{block}
    \begin{alertblock}{\small $\lambda_\mathrm{eff} \ll \lambda_\mathrm{bulk}$}
      \small $\lambda_\mathrm{eff}\approx\LamEffC$ vs.\
      bulk $\lambda=\LamBulk$.
      Mylar ($R=\MylarR$) recirculates light but each bounce
      has a $(1-R)$ loss. Many bounces $\Rightarrow$ short
      effective range.
    \end{alertblock}
  \end{columns}
\end{frame}

% ─── FRAME 7: Timing distributions ───────────────────────────────────────────
\begin{frame}{Arrival-time distributions: FPT at representative positions}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_timing_histograms.png}
    \column{0.33\textwidth}
    \begin{block}{Distributions shown}
      \small
      First Photon Time (FPT) at End-Left and End-Right per event
      (\textbf{not normalized}).
      Positions: $x\in\{-690,-400,0,+400,+690\}$\,mm.
      $N = \NEv$ events per position.
    \end{block}
    \begin{alertblock}{\small Key feature}
      \small Distribution shifts to larger $t$ and broadens as beam
      moves away from the respective end --- from longer propagation
      path and fewer photons (statistical minimum effect).
    \end{alertblock}
  \end{columns}
\end{frame}

% ─── FRAME 8: FPT vs t50 ─────────────────────────────────────────────────────
\begin{frame}{FPT vs.\ $t_{50}$: comparing timing estimators}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_fpt_vs_t50.png}
    \column{0.33\textwidth}
    \begin{block}{Estimators}
      \small
      \textbf{FPT} = first photon arrival time per event.\\
      $t_{50}$ = median photon arrival time per event.
    \end{block}
    \begin{block}{Observation}
      \small $t_{50}$ is shifted to later times relative to FPT,
      due to Mylar-reflected photons with longer paths.
      The shift grows with distance from the end
      (more reflected photons at large $d$).
    \end{block}
  \end{columns}
\end{frame}

% ─── FRAME 9: Mean arrival time & v_eff ──────────────────────────────────────
\begin{frame}{Mean arrival time \& effective velocity $v_\mathrm{eff}$}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_mean_arrival_time.png}
    \column{0.33\textwidth}
    \begin{block}{$v_\mathrm{eff}$ summary}
      \small
      \begin{tabular}{ll}
        \toprule
        Estimator & $v_\mathrm{eff}$ (mm/ns) \\
        \midrule
        FPT       & \VeffFPT \\
        $t_{50}$  & \VeffTfifty \\
        SUM4 $\Delta t$ & \VeffSUMfour \\
        \bottomrule
      \end{tabular}
    \end{block}
    \begin{alertblock}{\small $v_\mathrm{eff}$(FPT) anomaly}
      \small FPT bias: near the end ($N_\mathrm{pe}\sim 3000$)
      the statistical minimum is very small; far away
      ($N_\mathrm{pe}\sim 17$) it is larger.
      This $N$-dependent effect inflates the apparent slope,
      yielding $v_\mathrm{eff}(\mathrm{FPT}) > v_\mathrm{eff}(\Delta t)$.
      The SUM4 $\Delta t$ value (\VeffSUMfour) is more reliable.
    \end{alertblock}
  \end{columns}
\end{frame}

% ─── FRAME 10: σ_t(x) ────────────────────────────────────────────────────────
\begin{frame}{Intrinsic timing resolution $\sigma_t(x)$}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_sigma_t.png}
    \column{0.33\textwidth}
    \begin{block}{$\sigma_t$ at key positions}
      \small
      \begin{tabular}{rl}
        \toprule
        $x$ (mm) & $\sigma_\mathrm{single}$ (ps) \\
        \midrule
        $-690$ & \SigmaAtMsixnine \\
        $-400$ & \SigmaAtMfour    \\
        $0$    & \SigmaAtZero     \\
        $+400$ & \SigmaAtFour     \\
        $+690$ & \SigmaAtSixnine  \\
        \bottomrule
      \end{tabular}
    \end{block}
    \begin{alertblock}{\small Intrinsic only}
      \small $\sigma_t$ shown = optical + SUM4 estimator.
      SiPM SPTR and electronics jitter \textbf{not} included.
      $\sigma_t^\mathrm{total} = \sqrt{\sigma_t^2
      + \sigma_\mathrm{SPTR}^2 + \sigma_\mathrm{elec}^2}$.
    \end{alertblock}
  \end{columns}
\end{frame}

% ─── FRAME 11: Photon budget ──────────────────────────────────────────────────
\begin{frame}{Photon budget: fate of scintillation photons}
  \begin{columns}[T]
    \column{0.65\textwidth}
    \includegraphics[width=\textwidth]{figures/fig_photon_budget.png}
    \column{0.33\textwidth}
    \begin{block}{Budget (all 31 positions)}
      \small
      \begin{tabular}{ll}
        \toprule
        Fate & Fraction \\
        \midrule
        Escaped       & \BudgetEsc \\
        Enter SiPM    & \BudgetSiPM \\
        Detected      & \BudgetDet \\
        \bottomrule
      \end{tabular}
    \end{block}
    \begin{alertblock}{\small Mylar absorption dominates}
      \small $\approx98\%$ absorbed by Mylar over many bounces
      ($R=\MylarR$ per reflection).
      ``Reflector panel crossings'' counts every bounce,
      not unique photons.
    \end{alertblock}
  \end{columns}
\end{frame}

% ─── FRAME 12: Summary & next steps ──────────────────────────────────────────
\begin{frame}{Summary \& next steps}
  \begin{columns}[T]
    \column{0.55\textwidth}
    \begin{block}{Summary}
      \begin{itemize}
        \item End-only + Mylar = clean simulation limit.
        \item $\lambda_\mathrm{eff} \approx \LamEffC$
              $\ll \lambda_\mathrm{bulk} = \LamBulk$.
              Mylar absorption ($1-R$ per bounce) explains reduction.
        \item $\sigma_t^\mathrm{intr.}$: \SigmaAtZero\ (center)
              to \SigmaAtMsixnine\ (ends).
        \item $v_\mathrm{eff}(\Delta t) \approx \VeffSUMfour$.
        \item Photon yield: Mylar absorbs $\gtrsim 98\%$.
      \end{itemize}
    \end{block}
    \column{0.43\textwidth}
    \begin{block}{Next steps}
      \begin{enumerate}
        \item Fold in electronic jitter:
              $\sigma_\mathrm{SPTR}=106$\,ps
              $\oplus\,\sigma_\mathrm{FastIC}=10$\,ps.
        \item Leading-edge time-walk correction.
        \item Compare with April-2026 TB data (different config:
              top readout + Tyvek).
        \item Scan Mylar $R\in[0.85,0.95]$ for systematic study.
      \end{enumerate}
    \end{block}
  \end{columns}
\end{frame}

% ════════════════════════════════════════════════════════════════════════════════
% APPENDIX
% ════════════════════════════════════════════════════════════════════════════════
\appendix

\begin{frame}{Appendix: simulation parameters}
  \small
  @TAB_PARAMS@
\end{frame}

\begin{frame}{Appendix: $\sigma_t$ per-position summary}
  \centering\small
  @TAB_SIG@
  \par\medskip
  \small All values in ps.
  $\sigma_\mathrm{single}=\sigma_{LR}/\sqrt{2}$ from SUM4 leading-edge
  core Gaussian fit.
\end{frame}

\begin{frame}{Appendix: attenuation fit details}
  \centering\small
  @TAB_ATT@
  \par\medskip
  \small Fit: $N_\mathrm{pe}(d)=N_0\exp(-d/\lambda_\mathrm{eff})$.
  31 points per side; 62 combined.
  Errors are $1\sigma$ from covariance matrix.
\end{frame}

\begin{frame}{Appendix: method \& caveats}
  \small
  \begin{itemize}
    \item \textbf{Geometry:} Bar $1400\times60\times10$\,mm$^3$; long axis $X$.
          End SiPMs on $\pm X$; Mylar on $\pm Y,\pm Z$.
    \item \textbf{SUM4 trigger:} leading-edge at 4\,PE.
          Groups $\{0\text{--}3\}/\{4\text{--}7\}$ (left);
          $\{8\text{--}11\}/\{12\text{--}15\}$ (right).
    \item \textbf{$\sigma_t$ is intrinsic only:} optical + estimator;
          SPTR ($\approx106$\,ps) and FastIC ($\approx10$\,ps)
          not folded in.
    \item \textbf{SiPM naming:} macro string \texttt{\SiPMModelPDE}
          is used \emph{only} for the PDE curve;
          physical device is the single-element \textbf{\SiPMModel}.
    \item \textbf{No TB counterpart:} April-2026 TB used top readout
          + Tyvek wrapping $\neq$ end-only + Mylar.
    \item \textbf{Longitudinal axis $= X$} (not $Z$ or $Y$).
  \end{itemize}
\end{frame}

\end{document}
"""


def build_tex(out_dir: pathlib.Path, v: dict) -> str:
    tab_map   = v.get("tables", {})
    sigma_at  = v.get("sigma_t_at_key_positions", {})

    def sg(xkey: str) -> str:
        d = sigma_at.get(str(xkey), {})
        s = d.get("sigma_single_ps")
        e = d.get("sigma_single_err_ps")
        if s is None:
            return r"\texttt{TODO}"
        return f"${float(s):.0f}\\pm{float(e):.0f}$"

    n_gen  = v.get("photon_budget_generated") or 0
    n_esc  = v.get("photon_budget_escaped")  or 0
    n_sipm = v.get("photon_budget_sipm_entering") or 0
    n_det  = v.get("photon_budget_detected") or 0

    def pct(num):
        if n_gen == 0:
            return _fmt(None)
        return f"{float(num) / float(n_gen) * 100:.2f}"

    lam_l  = v.get("lambda_eff_left_cm");  lam_le = v.get("lambda_eff_left_err_cm")
    lam_r  = v.get("lambda_eff_right_cm"); lam_re = v.get("lambda_eff_right_err_cm")
    lam_c  = v.get("lambda_eff_combined_cm"); lam_ce = v.get("lambda_eff_combined_err_cm")

    subs = {
        "BAR_LEN":     _fmt(v.get("bar_length_mm"), 0),
        "N_EV":        _fmt_int(v.get("n_events_per_position")),
        "N_POS":       _fmt_int(v.get("n_positions")),
        "LAM_BULK":    _fmt(v.get("lambda_bulk_cm"), 0),
        "LAM_EFF_L":   (f"{float(lam_l):.1f}\\pm{float(lam_le):.1f}"
                        if lam_l is not None else r"\texttt{TODO}"),
        "LAM_EFF_R":   (f"{float(lam_r):.1f}\\pm{float(lam_re):.1f}"
                        if lam_r is not None else r"\texttt{TODO}"),
        "LAM_EFF_C":   (f"{float(lam_c):.1f}\\pm{float(lam_ce):.1f}"
                        if lam_c is not None else r"\texttt{TODO}"),
        "MYLAR_R":     _fmt(v.get("mylar_reflectivity"), 2),
        "MYLAR_SL":    _fmt(v.get("mylar_specular_lobe"), 1),
        "MYLAR_SA":    _fmt(v.get("mylar_sigma_alpha_deg"), 1),
        "PDE_PCT":     _fmt(v.get("pde_peak_frac", 0) * 100, 0),
        "SIPM_MODEL":  str(v.get("sipm_model", "AFBR-S4N66P014M")),
        "SIPM_MODEL_PDE": str(v.get("sipm_model_pde_curve", "AFBR-S4N66P024M")),
        "SCINT_Y":     _fmt_int(v.get("scint_yield_per_MeV")),
        "TAU_R":       _fmt(v.get("tau_rise_ns"), 1),
        "TAU_D":       _fmt(v.get("tau_decay_ns"), 1),
        "SG_M690":     sg("-690"),
        "SG_M400":     sg("-400"),
        "SG_0":        sg("0"),
        "SG_P400":     sg("400"),
        "SG_P690":     sg("690"),
        "V_FPT":       _fmt(v.get("v_eff_fpt_mm_ns"), 1),
        "V_SUM4":      _fmt(v.get("v_eff_sum4_mm_ns"), 1),
        "V_T50":       _fmt(v.get("v_eff_t50_mm_ns"), 1),
        "PCT_ESC":     pct(n_esc),
        "PCT_SIPM":    pct(n_sipm),
        "PCT_DET":     pct(n_det),
        "NPE_L_X0":    _fmt(v.get("npe_left_at_x0"), 1),
        "NPE_R_X0":    _fmt(v.get("npe_right_at_x0"), 1),
        "NPE_L_690":   _fmt(v.get("npe_left_at_xm690"), 0),
        "NPE_R_690":   _fmt(v.get("npe_right_at_x690"), 0),
        "TAB_PARAMS":  _read_tex(out_dir, "tab_sim_params", tab_map),
        "TAB_SIG":     _read_tex(out_dir, "tab_sigma_t", tab_map),
        "TAB_ATT":     _read_tex(out_dir, "tab_attenuation_fits", tab_map),
    }
    return _sub(_TEMPLATE, subs)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data-dir",
                    default="/home/reriosto/SHiP/t0minidaq/endonly_mylar_20260614",
                    type=pathlib.Path)
    ap.add_argument("--out-dir", default=HERE, type=pathlib.Path)
    ap.add_argument("--skip-analysis", action="store_true")
    ap.add_argument("--no-compile",    action="store_true")
    args = ap.parse_args()

    out_dir = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    if not args.skip_analysis:
        _run_analysis(args.data_dir, out_dir)

    v   = _load_values(out_dir)
    tex = build_tex(out_dir, v)

    tex_path = out_dir / "main.tex"
    tex_path.write_text(tex)
    print(f"Written: {tex_path}")

    if args.no_compile:
        print("Skipping LaTeX compilation (--no-compile).")
        return

    pdf_path = out_dir / "main.pdf"
    env = dict(os.environ)

    latexmk = shutil.which("latexmk")
    if latexmk:
        cmd = [latexmk, "-pdf", "-interaction=nonstopmode",
               f"-output-directory={out_dir}", str(tex_path)]
        r = subprocess.run(cmd, cwd=str(out_dir), capture_output=True, text=True, env=env)
        if r.returncode != 0:
            print("latexmk stderr:", r.stderr[-3000:])
            print("latexmk stdout:", r.stdout[-3000:])
        success = r.returncode == 0
    else:
        r = None
        for _ in range(2):
            r = subprocess.run(
                ["pdflatex", "-interaction=nonstopmode",
                 "-output-directory", str(out_dir), str(tex_path)],
                cwd=str(out_dir), capture_output=True, text=True, env=env,
            )
        success = (r is not None and r.returncode == 0)
        if not success and r:
            print("pdflatex stderr:", r.stderr[-2000:])

    if success and pdf_path.exists():
        try:
            pg_info = subprocess.run(["pdfinfo", str(pdf_path)],
                                     capture_output=True, text=True)
            pages = next(
                (ln.split(":")[1].strip()
                 for ln in pg_info.stdout.splitlines()
                 if ln.startswith("Pages:")), "?"
            )
        except Exception:
            pages = "?"
        print(f"PDF compiled successfully: {pdf_path.name}  ({pages} pages)")
    else:
        print("WARNING: PDF compilation may have failed. Check main.log for details.")


if __name__ == "__main__":
    main()
