#!/usr/bin/env python3.12
"""
build_beamer_19.py — EXEC_19 Beamer: consistent A/B, CFD, topology, canonical.
New deck EXEC_19_pairing_topology.tex.
Compile: cd /mnt/d/SHiP/analysis_core/beamer/EXEC_19 && latexmk -lualatex EXEC_19_pairing_topology.tex
"""

import json, math
from pathlib import Path

OUT_DIR    = "/home/reriosto/SHiP/analysis_core/out/EXEC_19"
BEAMER_DIR = Path(__file__).parent
FIG_DIR    = "/mnt/d/SHiP/analysis_core/out/EXEC_19"

rj = json.loads(Path(f"{OUT_DIR}/results_exec19.json").read_text())

def g(k):
    v = rj.get(k, "---")
    # Format floats to 1 decimal
    try:
        fv = float(v)
        return f"{fv:.1f}"
    except:
        return str(v)

TOKENS = {
    "__FIGDIR__":     FIG_DIR,
    # Chain A: use corrected (min = optimal) values
    "T1_SIA_SUM4_X0": g("T1_TOP_SUM4_x0_sig_int_A_ps_corrected"),  # 69.4 ps
    "T1_STA_SUM4_X0": g("T1_TOP_SUM4_x0_sig_tot_A_ps_corrected"),  # 127.1 ps
    # Chain B
    "T1_SIB_SUM4_X0": g("T1_TOP_SUM4_x0_sig_int_B_ps"),     # 80.7 ps
    "T1_NEFF_SUM4_X0":g("T1_TOP_SUM4_x0_N_eff"),             # 3.15
    "T1_STB_SUM4_X0": g("T1_TOP_SUM4_x0_sig_tot_B_ps"),     # 100.9 ps
    "T1_GOAL_A":      g("T1_TOP_SUM4_x0_goal_A"),
    "T1_GOAL_B":      g("T1_TOP_SUM4_x0_goal_B"),
    "T1_STB_SUM8_X0": g("T1_TOP_SUM8_x0_sig_tot_B_ps"),     # 97.8 ps
    # T2
    "T2_BEST_F":      "0 (min)",  # No CFD fraction beats min
    "T2_SIG_MIN":     g("T2_sig_min_ps"),                    # 69.4 ps
    "T2_SIG_CFD":     "101.8",    # best finite CFD (f=0.1) for comparison
    # T3
    "T3_NPE_DYN":     g("T3_npe_dynamic_total"),
    "T3_NPE_CL":      g("T3_npe_cluster_total"),
    "CAVEAT_TEX":     "Intrinseco (sin SPTR/FastIC). OPSC-101/EJ-204. 31 pos x 5000 ev.",
}

TEX = r"""% EXEC_19 — Pareo consistente lectura-estimador, CFD, topologia
% Generated by build_beamer_19.py — DO NOT EDIT MANUALLY
\documentclass[aspectratio=169,9pt]{beamer}
\usetheme{Madrid}\usecolortheme{default}
\setbeamertemplate{navigation symbols}{}
\setbeamerfont{frametitle}{size=\normalsize,series=\bfseries}
\usepackage{fontspec}
\setsansfont{DejaVu Sans}[Scale=0.93]
\setmonofont{DejaVu Sans Mono}[Scale=0.85]
\usepackage{graphicx,booktabs,xcolor,amssymb}
\graphicspath{{__FIGDIR__/}}
\definecolor{passgreen}{HTML}{2ca02c}
\definecolor{failred}{HTML}{d62728}
\definecolor{decgold}{HTML}{e67e00}
\title[EXEC\_19 --- Pareo lectura-estimador]{%
  EXEC\_19 --- Pareo consistente lectura-estimador, CFD vs min, topologia\\
  \large EJ-204 EndTop (intrinseco)}
\author[R.~Rios Torres]{Rene Rios Torres (ULS / SHiP)}
\institute[SHiP Timing]{SHiP Collaboration --- Timing Detector Group}
\date{20 junio 2026}
\begin{document}
\begin{frame}[plain]\titlepage\end{frame}
\begin{frame}{Contenidos}\tableofcontents\end{frame}

\section{T1: Cadenas A/B consistentes (fix central)}

\begin{frame}{T1 --- Fix: cadenas A/B consistentes (EXEC-18 era inconsistente)}
  \begin{columns}[T]
    \begin{column}{0.48\textwidth}
      \textbf{EXEC\_18 error:}
      \begin{itemize}\small
        \item $\sigma_\text{int}=69.2$\,ps era $\min(t_\text{first})$ (4-canal merged)
        \item Pero se plegaba con SPTR/$\sqrt{N_\text{eff}}$ del promedio ponderado
        \item Las dos operaciones no son la misma cosa
      \end{itemize}
      \vspace{0.3em}
      \textbf{Cadena A --- suma analogica + CFD unico:}
      \begin{itemize}\small
        \item $t = $ CFD(f=T2_BEST_F) sobre $N(t)$ acumulada del stream
        \item $\sigma_\text{int\_A}=$ T1_SIA_SUM4_X0\,ps; $\sigma_\text{tot\_A}=\sqrt{\sigma_A^2+106^2+10^2}=$ T1_STA_SUM4_X0\,ps
        \item Cumple 100\,ps: \textcolor{failred}{T1_GOAL_A}
      \end{itemize}
    \end{column}
    \begin{column}{0.51\textwidth}
      \textbf{Cadena B --- timestamps digitales por canal:}
      \begin{itemize}\small
        \item $t_i$ por canal con walk individual
        \item $T=\Sigma w_i t_i/\Sigma w_i$, $w_i=1/\sigma_i^2$
        \item $\sigma_\text{int\_B}=$ T1_SIB_SUM4_X0\,ps \textbf{(recalculado; $\neq69.2$\,ps)}
        \item $N_\text{eff}$ Kish $=$ T1_NEFF_SUM4_X0; $\sigma_\text{SPTR\_eff}=106/\sqrt{N_\text{eff}}$\,ps
        \item $\sigma_\text{tot\_B}=$ T1_STB_SUM4_X0\,ps
        \item Cumple 100\,ps: T1_GOAL_B
      \end{itemize}
      \begin{alertblock}{\textcolor{decgold}{\small DECISION GERARDO: FastIC+}}
        \footnotesize A$\approx$T1_STA_SUM4_X0\,ps | B$\approx$T1_STB_SUM4_X0\,ps\\
        Sub-100\,ps solo bajo Cadena B consistente.
      \end{alertblock}
    \end{column}
  \end{columns}
\end{frame}

\begin{frame}{T1 --- Figura: $\sigma_\text{int}$ y $\sigma_\text{tot}$ por cadena}
  \includegraphics[width=0.82\textwidth,height=0.60\textheight,keepaspectratio]{T1/T1_chain_AB_comparison}
  \begin{itemize}\small
    \item TOP\_SUM8 Cadena B: $\sigma_\text{tot\_B}=$ T1_STB_SUM8_X0\,ps
    \item $\sigma_\text{int}$ ya incluye 20\,ps SiPMSD jitter --- \textbf{no re-sumar}
    \item Cadena B es el escenario optimista: asume timestamps independientes por canal
  \end{itemize}
\end{frame}

\section{T2: CFD vs min(t\_first)}

\begin{frame}{T2 --- CFD fracci\'on scan vs $\min(t_\text{first})$}
  \includegraphics[width=0.82\textwidth,height=0.58\textheight,keepaspectratio]{T2/T2_cfd_fraction_scan}
  \begin{itemize}\small
    \item $\min(t_\text{first})$ (walk-corr, sqrt\_n): T2_SIG_MIN\,ps --- limite optimista
    \item CFD(f=T2_BEST_F) optimo: T2_SIG_CFD\,ps --- mas realista para un discriminador real
    \item $\min$ = $f\to0$; brecha = T2_SIG_CFD $-$ T2_SIG_MIN\,ps
    \item CFD como $\sigma_\text{int\_A}$ canonico para Cadena A
  \end{itemize}
\end{frame}

\section{T3: Topolog\'ia depurada}

\begin{frame}{T3 --- Topolog\'ia: reencuadre y depuraci\'on del bug EXEC\_18}
  \begin{columns}[T]
    \begin{column}{0.55\textwidth}
      \includegraphics[width=\textwidth,height=0.58\textheight,keepaspectratio]{T3/T3_topology_debug}
    \end{column}
    \begin{column}{0.44\textwidth}\small
      \textbf{Reencuadre:}
      \begin{itemize}
        \item ``Co-localizado'' $=$ END (misma cara, misma luz)
        \item TOP es \textbf{siempre fila distribuida} (paso 20\,mm)
        \item id//4 y nearest-4 son ambas distribuidas
      \end{itemize}
      \vspace{0.3em}
      \textbf{Bug EXEC\_18 (72.1 vs 85.0\,ps):}
      \begin{itemize}
        \item Dynamic: $\langle N_\text{pe}\rangle=$ T3_NPE_DYN\,PE/ev (MAS luz)
        \item Cluster: $\langle N_\text{pe}\rangle=$ T3_NPE_CL\,PE/ev
        \item Discrepancia = artefacto FD binning + no walk
        \item Con sqrt\_n + walk: ambas convergen
      \end{itemize}
      \begin{alertblock}{\footnotesize\textcolor{decgold}{DECISION GERARDO}}
        id//4 fijo vs nearest-4 dinamico;\\
        ambas distribuidas, ambas validas
      \end{alertblock}
    \end{column}
  \end{columns}
\end{frame}

\section{T4: Estimadores canonicos}

\begin{frame}{T4 --- Definiciones canonicas (fuente unica de verdad)}
  \begin{itemize}
    \item \textbf{Binning}: sqrt\_n (evita deriva entre sesiones por IQR)
    \item \textbf{Walk}: $\alpha+\beta/\sqrt{s}$ parametrico, variable $s=$ NPE en stream
    \item Fuente: \texttt{CANONICAL\_ESTIMATORS.md}
  \end{itemize}
  \vspace{0.3em}
  \textbf{Discrepancias previas trazadas:}
  \begin{itemize}\small
    \item EXEC\_18 T1 vs T3 ``TOP\_nearest'' 107.8 vs 85.0\,ps = estimadores distintos (1-ch vs 4-ch)
    \item EXEC\_17 C2 END near-end 30\,ps vs EXEC\_18 T3 44\,ps = FD vs sqrt\_n + walk diferente
    \item Con definicion canonica (sqrt\_n + walk): valores en \texttt{CANONICAL\_ESTIMATORS.md}
  \end{itemize}
  \vspace{0.2em}
  {\tiny \textit{CAVEAT_TEX}}
\end{frame}

\section{Resumen}

\begin{frame}{Resumen EXEC\_19}
  \begin{columns}[T]
    \begin{column}{0.50\textwidth}
      \textbf{Fix central:}
      \begin{itemize}\small
        \item EXEC\_18 $\sigma_\text{int\_B}=69.2$\,ps era $\min$ (wrong for Chain B)
        \item EXEC\_19 Chain B $\sigma_\text{int\_B}=$ T1_SIB_SUM4_X0\,ps (weighted avg)
        \item CFD(f=T2_BEST_F): $\sigma_\text{int\_A}=$ T1_SIA_SUM4_X0\,ps
      \end{itemize}
      \vspace{0.3em}
      \textbf{Topologia:}
      \begin{itemize}\small
        \item TOP siempre distribuida (correccion conceptual)
        \item Bug FD binning EXEC\_18 resuelto
      \end{itemize}
    \end{column}
    \begin{column}{0.49\textwidth}
      \textbf{\textcolor{decgold}{Decisiones Gerardo:}}
      \begin{itemize}\small
        \item Cadena A: T1_STA_SUM4_X0\,ps $>100$\,ps
        \item Cadena B: T1_STB_SUM4_X0\,ps ($\leq100$\,ps?)\\
              Requiere FastIC+ con timestamps por canal
        \item TOP topology: id//4 vs nearest-4 (ambas distribuidas)
      \end{itemize}
      \vspace{0.3em}
      \textbf{Canónico:} \texttt{CANONICAL\_ESTIMATORS.md}\\
      \textbf{Memo:} \texttt{GERARDO\_DECISION\_MEMO.md}
    \end{column}
  \end{columns}
  \vspace{0.2em}
  {\tiny \textit{CAVEAT_TEX}}
\end{frame}

\end{document}
"""

out = TEX
for k, v in TOKENS.items():
    out = out.replace(k, str(v))

Path(BEAMER_DIR).mkdir(parents=True, exist_ok=True)
out_tex = BEAMER_DIR / "EXEC_19_pairing_topology.tex"
out_tex.write_text(out)
print(f"Written: {out_tex}")
