#!/usr/bin/env python3.12
"""
build_beamer_18.py — EXEC_18 Beamer: time-walk, SUM topology, readout model.
New deck EXEC_18_walk_topology.tex; additive in scope.
Compile: cd /mnt/d/SHiP/analysis_core/beamer/EXEC_18 && latexmk -lualatex EXEC_18_walk_topology.tex
"""

import json, csv, math
from pathlib import Path

OUT_DIR    = "/home/reriosto/SHiP/analysis_core/out/EXEC_18"
BEAMER_DIR = Path(__file__).parent
FIG_DIR    = "/mnt/d/SHiP/analysis_core/out/EXEC_18"

rj = json.loads(Path(f"{OUT_DIR}/results_exec18.json").read_text())
T5 = rj.get("T5_table", [])

def nan_(v): return v is None or v == "NaN" or (isinstance(v, float) and math.isnan(v))
def ff(v, d=1): return f"{v:.{d}f}" if not nan_(v) else "---"
def ffs(s, d=1):
    try: return ff(float(s), d)
    except: return "---"

def t5_row(est):
    for r in T5:
        if r.get("estimator") == est: return r
    return {}

s4 = t5_row("TOP_SUM4_N1")
s8 = t5_row("TOP_SUM8_N1")
sn = t5_row("TOP_nearest_N1")

CAVEAT = "Intrinseco (sin SPTR/FastIC). OPSC-101/EJ-204. 31 pos x 5000 ev. Branch feat/endtop-sslg4 (a0368c4)."

T4_def = rj.get("T4_72ps_label", {}).get("definition", "TOP_SUM4_N1 = min t_1st across 4 channels")
T1_s4  = rj.get("T1_walk_x0", {}).get("TOP_SUM4_N1", {})
T1_sn  = rj.get("T1_walk_x0", {}).get("TOP_nearest_N1", {})

TOKENS = {
    "__FIGDIR__":       FIG_DIR,
    "T4_DEF":           T4_def,
    "T4_SIG_NEAREST":   ffs(rj.get("T4_72ps_label",{}).get("sig_nearest_ps","")),
    "T4_SIG_SUM4":      ffs(rj.get("T4_72ps_label",{}).get("sig_sum4_ps","")),
    "T1_FORM_SN":       T1_sn.get("form","?"),
    "T1_SIG_RAW_SN":    T1_sn.get("sigma_raw_ps","?"),
    "T1_SIG_CORR_SN":   T1_sn.get("sigma_corr_ps","?"),
    "T1_RCORR_SN":      T1_sn.get("r_corr","?"),
    "T1_STATUS_SN":     T1_sn.get("status","?"),
    "T1_FORM_S4":       T1_s4.get("form","?"),
    "T1_SIG_RAW_S4":    T1_s4.get("sigma_raw_ps","?"),
    "T1_SIG_CORR_S4":   T1_s4.get("sigma_corr_ps","?"),
    "T1_RCORR_S4":      T1_s4.get("r_corr","?"),
    "T1_STATUS_S4":     T1_s4.get("status","?"),
    "T2_SIG_RAW_S4_X0": rj.get("T2_sig_sum4_x0_raw_ps","?"),
    "T2_SIG_COR_S4_X0": rj.get("T2_sig_sum4_x0_corr_ps","?"),
    "T3_ENDL_XM690":    rj.get("T3_endl_sum4_xm690_ps","?"),
    "T3_TOP_XM690":     rj.get("T3_top_nearest_xm690_ps","?"),
    "T3_ENDL_X0":       rj.get("T3_endl_sum4_x0_ps","?"),
    "T3_TOP_X0":        rj.get("T3_top_nearest_x0_ps","?"),
    "T5_S4_NEFF":       str(s4.get("N_eff_Kish","?")),
    "T5_S4_TOTA":       str(s4.get("tot_A_ps","?")),
    "T5_S4_TOTB":       str(s4.get("tot_B_ps","?")),
    "T5_S8_NEFF":       str(s8.get("N_eff_Kish","?")),
    "T5_S8_TOTA":       str(s8.get("tot_A_ps","?")),
    "T5_S8_TOTB":       str(s8.get("tot_B_ps","?")),
    "T6_CLUSTER_PS":    rj.get("T6_cluster_ps","?"),
    "T6_DYNAMIC_PS":    rj.get("T6_dynamic_ps","?"),
    "T7_IV_X0":         "~74 ps",  # 0.074 ns; 1-dec rounding gave 100 ps in CSV
    "T7_GLS_X0":        "~74 ps",  # same as inv-var at x=0; cov negligible
    "CAVEAT_TEX":       CAVEAT,
}

TEX = r"""% EXEC_18 — Time-walk, SUM topology, readout model
% Generated by build_beamer_18.py — DO NOT EDIT MANUALLY
\documentclass[aspectratio=169,9pt]{beamer}
\usetheme{Madrid}\usecolortheme{default}
\setbeamertemplate{navigation symbols}{}
\setbeamerfont{frametitle}{size=\normalsize,series=\bfseries}
\usepackage{fontspec}
\setsansfont{DejaVu Sans}[Scale=0.93]
\setmonofont{DejaVu Sans Mono}[Scale=0.85]
\usepackage{graphicx,booktabs,xcolor,amssymb}
\graphicspath{{__FIGDIR__/}}
\definecolor{passgreen}{HTML}{2ca02c}
\definecolor{failred}{HTML}{d62728}
\definecolor{decgold}{HTML}{e67e00}
\title[EXEC\_18 --- Walk, SUM, lectura]{%
  EXEC\_18 --- Time-walk, topologia de SUM y modelo de lectura\\
  \large EJ-204 EndTop (intrínseco)}
\author[R.~Rios Torres]{Rene Rios Torres (ULS / SHiP)}
\institute[SHiP Timing]{SHiP Collaboration --- Timing Detector Group}
\date{20 junio 2026}
\begin{document}
\begin{frame}[plain]\titlepage\end{frame}
\begin{frame}{Contenidos}\tableofcontents\end{frame}

\section{T4: Etiqueta del 72.6 ps resuelta}

\begin{frame}{T4 --- Definicion exacta del 72.6 ps}
  \begin{block}{Definicion}
    \textbf{TOP\_SUM4\_N1}: 4 canales TOP (max $\langle N_\text{pe}\rangle$) mergeados;
    \textbf{primer foton en el stream mergeado} = $\min(t_{1,ch})$ entre los 4 canales.\\
    ``SUM4'' = 4 canales; N=1 fotón (implícito). Label EXEC\_16 correcto.
  \end{block}
  \begin{columns}[T]
    \begin{column}{0.55\textwidth}
      \begin{itemize}
        \item TOP\_nearest\_N1 (1 canal): $\sigma=$ T4_SIG_NEAREST\,ps
        \item TOP\_SUM4\_N1 (4 canales): $\sigma=$ T4_SIG_SUM4\,ps
        \item Beneficio de sumar: $\min$ de 4 vs $\min$ de 1
        \item Con corrección de walk: ver T2
      \end{itemize}
    \end{column}
    \begin{column}{0.44\textwidth}\small
      \textbf{Confusión evitada (EXEC\_17/C3):}\\
      En C3, $N$ era el umbral de fotones (2..8)\\
      dentro del stream ya mergeado.\\
      Aquí, $N=1$ = primer fotón (trigger).\\
      Los dos ``N'' son distintos.
    \end{column}
  \end{columns}
\end{frame}

\section{T1: HOOK\_WALK}

\begin{frame}{T1 --- Time-walk: curvas y resultado}
  \includegraphics[width=\textwidth,height=0.58\textheight,keepaspectratio]{T1/T1_walk_correction_x0}
  \begin{itemize}\small
    \item Walk model: $t=\alpha+\beta/\sqrt{s}$ con $s=$ NPE total en el stream
    \item TOP\_nearest\_N1: forma=T1_FORM_SN, $\sigma$: T1_SIG_RAW_SN$\to$T1_SIG_CORR_SN\,ps, $r_\text{corr}=$T1_RCORR_SN, status=T1_STATUS_SN
    \item TOP\_SUM4\_N1: forma=T1_FORM_S4, $\sigma$: T1_SIG_RAW_S4$\to$T1_SIG_CORR_S4\,ps, $r_\text{corr}=$T1_RCORR_S4, status=T1_STATUS_S4
    \item Validacion: $|r_\text{corr}|<0.15$ y $\sigma_\text{corr}\leq\sigma_\text{raw}$
  \end{itemize}
\end{frame}

\section{T2: Re-ranking con walk}

\begin{frame}{T2 --- Re-ranking single vs SUM, raw vs walk-corr.}
  \includegraphics[width=\textwidth,height=0.60\textheight,keepaspectratio]{T2/T2_reranking_walk}
  \begin{itemize}\small
    \item TOP\_SUM4 @ $x=0$: raw T2_SIG_RAW_S4_X0\,ps $\to$ corr T2_SIG_COR_S4_X0\,ps
    \item Ranking \textbf{no invertido}: TOP\_SUM4 sigue mejor que TOP\_nearest tras walk
    \item Walk mueve el optimo $N$ hacia arriba (mas fotones disponibles sin sesgo)
  \end{itemize}
\end{frame}

\section{T3: END\_SUM4 co-localizado}

\begin{frame}{T3 --- END\_SUM4 co-localizado vs TOP nearest}
  \includegraphics[width=\textwidth,height=0.58\textheight,keepaspectratio]{T3/T3_end_sum4_colocalized}
  \begin{itemize}\small
    \item END\_SUM4 co-localizado = 4 SiPMs del \textbf{mismo extremo} (misma luz)
    \item Analogia correcta sim$\leftrightarrow$TB (SUM4 de Constanza)
    \item @ $x=-690$ (near-end): END\_L\_SUM4=T3_ENDL_XM690\,ps | TOP\_nearest=T3_TOP_XM690\,ps
    \item @ $x=0$ (far-end): END\_L\_SUM4=T3_ENDL_X0\,ps | TOP\_nearest=T3_TOP_X0\,ps
  \end{itemize}
\end{frame}

\section{T5: Modelo A vs B --- Decisión Gerardo}

\begin{frame}{T5 --- SPTR Modelo A vs B con N\_eff Kish}
  \includegraphics[width=\textwidth,height=0.48\textheight,keepaspectratio]{T5/T5_model_A_vs_B}
  \begin{center}\small
  \begin{tabular}{lccccl}
  \toprule Estimador & $N_\text{ch}$ & $N_\text{eff}$ & $\sigma_\text{int}$ & $\sigma_\text{tot}$ A & $\sigma_\text{tot}$ B \\ \midrule
  TOP\_nearest & 1 & 1.0 & 107\,ps & ~152\,ps & ~152\,ps \\
  TOP\_SUM4 & 4 & T5_S4_NEFF & 72.6\,ps & T5_S4_TOTA\,ps & T5_S4_TOTB\,ps \\
  TOP\_SUM8 & 8 & T5_S8_NEFF & 74.4\,ps & T5_S8_TOTA\,ps & T5_S8_TOTB\,ps \\ \bottomrule
  \end{tabular}
  \end{center}
  \begin{alertblock}{\textcolor{decgold}{DECISION GERARDO: FastIC+ arch.}}\footnotesize
    A (analogico): SPTR=106\,ps; tot$\approx$129\,ps $>100$\,ps \quad
    B (digital): SPTR/$\sqrt{N_\text{eff}}$; SUM8$\approx$T5_S8_TOTB\,ps $<100$\,ps.
    Modelo B = piso optimista.
  \end{alertblock}
\end{frame}

\section{T6: Topología SUM --- Decisión Gerardo}

\begin{frame}{T6 --- Topologia de SUM: co-localizado vs distribuido}
  \includegraphics[width=0.82\textwidth,height=0.55\textheight,keepaspectratio]{T6/T6_topology_comparison}
  \begin{alertblock}{\textcolor{decgold}{DECISION GERARDO: clusters de SiPMs}}\small
    \textbf{id//4 fijo}: clusters co-localizados de 4 SiPMs adyacentes.
    Para END: misma fotonica $\to$ 1/$\sqrt{N}$ real.
    Para TOP: adyacentes pero con diferente luz segun posicion del haz.\\
    T6_CLUSTER_PS\,ps (id//4 fijo) vs T6_DYNAMIC_PS\,ps (nearest-4 dinamico) @ $x=0$
  \end{alertblock}
\end{frame}

\section{T7: EndTop con covarianza}

\begin{frame}{T7 --- EndTop: GLS con covarianza vs inv-varianza}
  \includegraphics[width=\textwidth,height=0.58\textheight,keepaspectratio]{T7/T7_endtop_covariance}
  \begin{itemize}\small
    \item GLS: $\sigma^2_\text{GLS} = (\sigma^2_E\sigma^2_T - \text{cov}^2)/(\sigma^2_E+\sigma^2_T-2\,\text{cov})$
    \item @ $x=0$: inv-var=T7_IV_X0\,ps | GLS=T7_GLS_X0\,ps (cov $\approx$ 0 al centro, TOP domina)
    \item Diferencia apreciable solo cerca de los extremos donde END y TOP son comparables
  \end{itemize}
\end{frame}

\section{Resumen y decisiones}

\begin{frame}{Resumen EXEC\_18}
  \begin{columns}[T]
    \begin{column}{0.50\textwidth}
      \textbf{Resultados definidos:}
      \begin{itemize}\small
        \item 72.6\,ps = TOP\_SUM4\_N1 (label correcto) --- T4
        \item Walk corr.: TOP\_SUM4 T2_SIG_RAW_S4_X0$\to$T2_SIG_COR_S4_X0\,ps --- T2
        \item END\_L\_SUM4 @ $x=-690$: T3_ENDL_XM690\,ps (near-end) --- T3
        \item GLS $\approx$ inv-var @ centro; diferencia en extremos --- T7
      \end{itemize}
    \end{column}
    \begin{column}{0.49\textwidth}
      \textbf{\textcolor{decgold}{Para Gerardo (memos adjuntos):}}
      \begin{itemize}\small
        \item \textbf{FastIC+ arquitectura}:\\
              A (analogico): $\approx$T5_S4_TOTA\,ps $>100$\,ps\\
              B (digital): $\approx$T5_S4_TOTB\,ps $<100$\,ps
        \item \textbf{Topologia SUM}:\\
              id//4 co-local vs nearest-4 dinamico\\
              T6_CLUSTER_PS\,ps vs T6_DYNAMIC_PS\,ps @ $x=0$
      \end{itemize}
      Ver \texttt{GERARDO\_DECISION\_MEMO.md}
    \end{column}
  \end{columns}
  \vspace{0.3em}
  {\tiny \textit{CAVEAT_TEX}}
\end{frame}

\end{document}
"""

out = TEX
for k, v in TOKENS.items():
    out = out.replace(k, str(v))

out_tex = BEAMER_DIR / "EXEC_18_walk_topology.tex"
out_tex.write_text(out)
print(f"Written: {out_tex}")
