#!/usr/bin/env python3.12
"""
build_beamer.py — Generate EXEC_16 Beamer .tex from results.json + CSV.
Numbers injected via simple token substitution (no f-string LaTeX mixing).
Compile: cd /mnt/d/SHiP/analysis_core/beamer/EXEC_16 && latexmk -lualatex EXEC_16_endtop_ej204.tex
"""

import json, csv, math
from pathlib import Path

OUT_DIR    = "/home/reriosto/SHiP/analysis_core/out/EXEC_16"
BEAMER_DIR = Path(__file__).parent
FIG_DIR    = "/mnt/d/SHiP/analysis_core/out/EXEC_16"

rj = json.loads(Path(f"{OUT_DIR}/results.json").read_text())

def nan_(v): return v is None or (isinstance(v, float) and math.isnan(v))
def ff(v, d=1): return f"{v:.{d}f}" if not nan_(v) else "---"
def ps_val(v): return f"${ff(v)}$\\,ps" if not nan_(v) else "---"
def ps_pm(v, b): return f"${ff(v)}$ $\\pm$ ${ff(b)}$\\,ps" if not nan_(v) else "---"
def cmns(v): return f"${ff(v, 2)}$\\,cm\\,ns$^{{-1}}$" if not nan_(v) else "---"

def get_sigma(est, x_mm, fpath):
    for r in csv.DictReader(open(fpath)):
        if r["estimator"] == est and int(float(r["x_mm"])) == x_mm:
            s, b = r["sigma_fit_ps"], r["bootstrap_err_ps"]
            return (float(s) if s not in ("NaN","") else math.nan,
                    float(b) if b not in ("NaN","") else math.nan)
    return math.nan, math.nan

csv2 = f"{OUT_DIR}/L2/sigma_t_all_estimators.csv"

top_s4,   top_s4_b  = rj["TOP_SUM4"]["x0_sigma_ps"],  rj["TOP_SUM4"]["x0_boot_ps"]
top_s8,   top_s8_b  = rj["TOP_SUM8"]["x0_sigma_ps"],  rj["TOP_SUM8"]["x0_boot_ps"]
end_c_s8             = rj["END_COMBINED_SUM8"]["x0_sigma_ps"]
v_eff                = abs(rj["v_eff_cm_per_ns"])
ratio_x0             = rj["endtop_ratio_x0"]
nearest_gid          = rj["top_nearest_gid_x0"]
nearest_npe          = rj["top_nearest_npe_x0"]
endl_x690, _         = get_sigma("END_L_SUM4", -690, csv2)
top_x690,  _         = get_sigma("TOP_SUM4",   -690, csv2)

SPTR_PS, FAST_PS = 106.0, 10.0
tot = math.sqrt(top_s4**2 + SPTR_PS**2 + FAST_PS**2) if not nan_(top_s4) else math.nan
benefit = round((1 - ratio_x0) * 100) if not nan_(ratio_x0) else 0

caveat_raw = rj["caveat"]
caveat_tex = (caveat_raw
              .replace("_", r"\_")
              .replace("≈", r"$\approx$")
              .replace("≤", r"$\leq$"))

TOKENS = {
    "FIGDIR":        FIG_DIR,
    "TOP_S4_BOOT":   ps_pm(top_s4, top_s4_b),
    "TOP_S4_VAL":    ps_val(top_s4),
    "TOP_S8_BOOT":   ps_pm(top_s8, top_s8_b),
    "TOP_S8_VAL":    ps_val(top_s8),
    "END_C_S8_VAL":  ps_val(end_c_s8),
    "VEFF":          cmns(v_eff),
    "RATIO_X0":      ff(ratio_x0, 3),
    "BENEFIT_PCT":   str(benefit),
    "NEAREST_GID":   str(nearest_gid),
    "NEAREST_NPE":   f"{nearest_npe:.2f}",
    "ENDL_X690":     ff(endl_x690),
    "TOP_X690":      ff(top_x690),
    "TOT_SIG":       ff(tot),
    "TOP_S4_NUM":    ff(top_s4),
    "CAVEAT_TEX":    caveat_tex,
}

TEX_TEMPLATE = r"""% EXEC_16 — EJ-204 EndTop: caracterizacion intrinseca
% Generated by build_beamer.py from results.json — DO NOT EDIT MANUALLY
% Compile: latexmk -lualatex EXEC_16_endtop_ej204.tex
\documentclass[aspectratio=169,9pt]{beamer}

\usetheme{Madrid}
\usecolortheme{default}
\setbeamertemplate{navigation symbols}{}
\setbeamerfont{frametitle}{size=\normalsize,series=\bfseries}
\setbeamerfont{framesubtitle}{size=\small}

\usepackage{fontspec}
\setsansfont{DejaVu Sans}[Scale=0.93]
\setmonofont{DejaVu Sans Mono}[Scale=0.85]

\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{xcolor}
\usepackage{tikz}

\graphicspath{{FIGDIR/}}

\definecolor{shipgoal}{HTML}{d62728}
\definecolor{topcolor}{HTML}{2ca02c}
\definecolor{endcolor}{HTML}{1f77b4}
\definecolor{flagcol}{HTML}{e6550d}

\title[EXEC\_16 --- EJ-204 EndTop]{%
  EXEC\_16 --- Caracterizacion intrinseca del EndTop scan EJ-204 (Mylar)\\
  \large fotones y resolucion temporal}
\author[R.~Rios Torres]{Rene Rios Torres (ULS / SHiP)}
\institute[SHiP Timing]{SHiP Collaboration --- Timing Detector Group}
\date{20 junio 2026}

\begin{document}

\begin{frame}[plain]\titlepage\end{frame}
\begin{frame}{Contenidos}\tableofcontents\end{frame}

%% Disclaimer
\section{Metodologia y disclaimers}

\begin{frame}{Metodologia y caveats}
  \begin{block}{Resolucion INTRINSECA}
    Sin SPTR$\approx$106\,ps ni jitter FastIC$\approx$10\,ps; sin gate temporal.\\
    Wrapping: \textit{reflector skin surface on BarLV} (equivalente Mylar).\\
    TB DESY abr-2026 uso Top+Tyvek --- \textbf{no comparacion directa}.
  \end{block}
  \begin{columns}[T]
    \begin{column}{0.55\textwidth}
      \textbf{Estimador temporal autoritativo:}
      \begin{itemize}
        \item TF1 gaussiano sembrado en el \textbf{pico}
        \item $\sigma_{\rm seed} = 1.4826 \times {\rm MAD}$
        \item Ventana pico $\pm 2\,\sigma_{\rm MAD}$
        \item Bootstrap $N=200$ re-muestras
        \item \textbf{np.std no se reporta como metrica}
      \end{itemize}
    \end{column}
    \begin{column}{0.44\textwidth}
      \textbf{Geometria (leida del header):}
      \begin{itemize}
        \item $K_{\rm END}=8$ SiPMs/extremo
        \item $N_{\rm TOP}=70$ SiPMs (gid 16--85)
        \item Bar: $\pm700$\,mm, $\lambda_{\rm abs}=160$\,cm
        \item $\tau_d=1.8$\,ns, $\tau_r=0.7$\,ns
      \end{itemize}
    \end{column}
  \end{columns}
  \vspace{0.3em}
  \begin{alertblock}{Provenance}
    DATA\_DIR: \texttt{t0minidaq\_endtop\_scan\_20260618\_204959}\\
    31 posiciones $\times$ 5\,000 eventos; branch \texttt{feat/endtop-sslg4} (\texttt{a0368c4})
  \end{alertblock}
\end{frame}

%% Dataset
\section{Dataset y cordura}

\begin{frame}{Dataset y QA-0}
  \begin{columns}[T]
    \begin{column}{0.50\textwidth}
      \includegraphics[width=\textwidth]{L0/L0_events_per_position}
    \end{column}
    \begin{column}{0.49\textwidth}
      \includegraphics[width=\textwidth]{L0/L0_occupancy_channels}
    \end{column}
  \end{columns}
  \begin{itemize}
    \item \textbf{31 posiciones}: $x\in[-690,+690]$\,mm, paso medio 46\,mm
    \item \textbf{5\,000 eventos/posicion} (uniforme, verificado via \texttt{gun\_x\_mm})
    \item \textbf{QA-0 PASSED}: cero posiciones vacias, 86 canales en rango [0,85]
    \item \texttt{face\_type}\,\{0,1,2\} $\to$ END\_L / END\_R / TOP (de DetectorConstruction.cc:52--54)
  \end{itemize}
\end{frame}

\begin{frame}{Espectros crudos de tiempo de llegada}
  \includegraphics[width=\textwidth]{L0/L0_raw_toa_spectra}
  \begin{itemize}\small
    \item Cola consistente con $\tau_d=1.8$\,ns (sanidad de material)
    \item TOP recibe $\gg$ fotones que END en todas las posiciones
  \end{itemize}
\end{frame}

%% Fotones
\section{Fotones}

\begin{frame}{$\langle N_{\rm pe}\rangle(x)$ por face}
  \begin{columns}[T]
    \begin{column}{0.55\textwidth}
      \includegraphics[width=\textwidth]{L1/L1_npe_vs_x}
    \end{column}
    \begin{column}{0.44\textwidth}
      \includegraphics[width=\textwidth]{L1/L1_npe_distributions}
    \end{column}
  \end{columns}
  \begin{itemize}\small
    \item TOP (70 SiPMs): $\langle N_{\rm pe}\rangle \gg$ END en todo el scan
    \item Canal \textbf{TOP nearest} en $x=0$: \texttt{gid=NEAREST_GID}, $\langle N_{\rm pe}\rangle=NEAREST_NPE$
    \item END\_L aumenta al acercarse al extremo izquierdo (atenuacion + geometria)
  \end{itemize}
\end{frame}

\begin{frame}{Perfil de atenuacion TOP $N_{\rm pe}(x)$}
  \includegraphics[width=0.70\textwidth,height=0.52\textheight,keepaspectratio]{L1/L1_npe_profile_top}
  \begin{alertblock}{Nota (doble-exp = DESCRIPTIVO)}\footnotesize
    $\lambda_{\rm eff}$ de mono-exponencial \textbf{no representa} $\lambda_{\rm abs}=160$\,cm:
    el perfil incluye componente directa + cola recirculada.
  \end{alertblock}
\end{frame}

%% Resolucion temporal
\section{Resolucion temporal}

\begin{frame}{$\sigma_t(x)$ --- estimadores TOP (intrinseco)}
  \includegraphics[width=\textwidth,height=0.55\textheight,keepaspectratio]{L2/L2_sigma_t_vs_x}
  \begin{itemize}\small
    \item \textcolor{topcolor}{TOP\_SUM4} y TOP\_SUM8: $\sigma_t \approx 67$--$82$\,ps en todo el scan
    \item Valor en $x=0$: TOP\_SUM4 = TOP_S4_BOOT
    \item \textbf{Por debajo del objetivo SHiP 100\,ps en todas las posiciones}
    \item END\_COMBINED: curvas abortadas ($>$30\,\% $\sigma$-outlier); ver diapositiva siguiente
  \end{itemize}
\end{frame}

\begin{frame}{Panel comparativo en $x=0$}
  \includegraphics[width=0.82\textwidth]{L2/L2_sigma_panel_x0}
  \begin{itemize}\small
    \item TOP\_SUM4 $=$ TOP_S4_VAL, TOP\_SUM8 $=$ TOP_S8_VAL
    \item Umbral (time-walk no corregido): THR1 $=$ $107$\,ps, THR2 $=$ $133$\,ps, THR5 $=$ $209$\,ps
    \item END\_COMBINED\_SUM8 @ $x=0$: $\approx$ END_C_S8_VAL (amplio --- haz a 700\,mm del extremo)
  \end{itemize}
\end{frame}

\begin{frame}{Nota sobre curvas END abortadas}
  \begin{columns}[T]
    \begin{column}{0.55\textwidth}
      \textbf{Comportamiento fisico (END\_L\_SUM4):}
      \begin{itemize}
        \item $x=-690$\,mm (haz junto a END\_L): $\sigma \approx ENDL_X690$\,ps
        \item $x=0$ (700\,mm del extremo): $\sigma \approx 909$\,ps
        \item $x=+690$\,mm: $\sigma \approx 1{,}395$\,ps
      \end{itemize}
      \vspace{0.3em}
      \textcolor{flagcol}{\textbf{Curvas END abortadas}} porque $>$30\,\% de puntos
      tienen $\sigma > 400$\,ps (\texttt{SIGMA\_BAND\_PS}).\\[0.3em]
      \textbf{No es fallo de ajuste}: distribuciones fisicamente anchas
      cuando el haz esta lejos del extremo.
    \end{column}
    \begin{column}{0.44\textwidth}
      \begin{block}{END\_L cerca de su extremo}
        $\sigma_{\rm END\_L} \approx ENDL_X690$\,ps @ $x=-690$\,mm\\
        (haz directo $\to$ pocas ns de tiempo de vuelo)
      \end{block}
      \begin{block}{TOP en el mismo punto}
        $\sigma_{\rm TOP\_SUM4} \approx TOP_X690$\,ps @ $x=-690$\,mm
      \end{block}
      \begin{alertblock}{Para Rene}
        Ajustar \texttt{SIGMA\_BAND\_PS} para curva END\_L vs $x$ completa (rango 30--2\,000\,ps).
      \end{alertblock}
    \end{column}
  \end{columns}
\end{frame}

%% END vs EndTop
\section{END-only vs EndTop y resolucion espacial}

\begin{frame}{END-only vs EndTop: $\sigma_t$ y ratio}
  \includegraphics[width=\textwidth,height=0.60\textheight,keepaspectratio]{L3/L3_endonly_vs_endtop}
  \begin{itemize}\small
    \item Ratio $\sigma_{\rm EndTop}/\sigma_{\rm END\text{-}only}$ @ $x=0$: $RATIO_X0$ --- TOP \textbf{reduce} la incertidumbre en BENEFIT_PCT\,\%
    \item Ratio $<1$ en \textbf{todas} las posiciones: TOP siempre ayuda en EJ-204
    \item Contraste con EJ-230: inversion dependiente de posicion (OPSC-106/EXEC series)
  \end{itemize}
\end{frame}

\begin{frame}{Resolucion espacial $\sigma_x(x)$ y $v_{\rm eff}$}
  \includegraphics[width=\textwidth]{L3/L3_spatial_resolution}
  \begin{itemize}\small
    \item $v_{\rm eff} =$ VEFF (slope de $\langle\Delta t\rangle(x)$, metodo lineal)
    \item Referencia prototipo: $\approx 15.5$\,cm/ns --- consistente
    \item $\sigma_x(x) = \sigma(\Delta t)\cdot v_{\rm eff}/2$
  \end{itemize}
\end{frame}

%% Mapas 2D
\section{Mapas 2D}

\begin{frame}{Mapa 2D 1: tiempo $\times$ evento (identidad preservada)}
  \begin{columns}[T]
    \begin{column}{0.68\textwidth}
      \includegraphics[width=\textwidth]{L4/L4_map1_time_vs_event}
    \end{column}
    \begin{column}{0.31\textwidth}\small
      Canal: TOP \texttt{gid=NEAREST_GID} (nearest @ $x=0$)\\
      $\langle N_{\rm pe}\rangle=NEAREST_NPE$\\[0.5em]
      \textbf{Eje Y = indice de evento} (coordenada);\\
      Z = PE/casilla.\\[0.5em]
      Identifica eventos anomalos y la cola.\\[0.5em]
      \textit{Grafico 1: evento como eje, no como peso.}
    \end{column}
  \end{columns}
\end{frame}

\begin{frame}{Mapa 2D 2: tiempo $\times$ $N_{\rm pe}$ acumulados}
  \begin{columns}[T]
    \begin{column}{0.68\textwidth}
      \includegraphics[width=\textwidth]{L4/L4_map2_time_vs_nacc}
    \end{column}
    \begin{column}{0.31\textwidth}\small
      Canal: TOP \texttt{gid=NEAREST_GID} @ $x=0$\\[0.5em]
      Z = \textbf{no.\ de eventos} que pasan por $(t, N_{\rm acum})$.\\[0.5em]
      Si se agregan los 5\,000 eventos.\\
      Cada curva $N(t)$ se superpone como densidad.\\[0.5em]
      \textit{Grafico 2: evento como peso, no como eje.}
    \end{column}
  \end{columns}
\end{frame}

%% Conclusiones
\section{Conclusiones}

\begin{frame}{Conclusiones --- EXEC\_16 (intrinseco, EJ-204)}
  \begin{columns}[T]
    \begin{column}{0.54\textwidth}
      \textbf{Resolucion temporal intrinseca:}
      \begin{itemize}
        \item TOP\_SUM4 @ $x=0$: \textcolor{topcolor}{\textbf{TOP_S4_BOOT}}
        \item TOP\_SUM8 @ $x=0$: \textcolor{topcolor}{TOP_S8_BOOT}
        \item \textbf{Ambos $<$ 100\,ps en todo el scan}
        \item Con SPTR $\oplus$ FastIC: $\approx TOT_SIG$\,ps (estimado)
      \end{itemize}
      \vspace{0.3em}
      \textbf{Beneficio EndTop:}
      \begin{itemize}
        \item TOP reduce $\sigma_t$ en BENEFIT_PCT\,\% @ $x=0$ (ratio $=$ $RATIO_X0$)
        \item TOP ayuda en \textbf{todas} las posiciones (ratio $<1$ uniforme)
      \end{itemize}
    \end{column}
    \begin{column}{0.45\textwidth}
      \textbf{Resolucion espacial:}
      \begin{itemize}
        \item $v_{\rm eff} =$ VEFF (consistente con $\approx 15.5$\,cm/ns)
      \end{itemize}
      \vspace{0.3em}
      \textbf{END SiPMs:}
      \begin{itemize}
        \item Near-end ($x=-690$): $\sigma_{\rm END\_L}\approx ENDL_X690$\,ps
        \item Far-end ($x=0$): $\sigma\approx 900$\,ps (fisico)
        \item Curvas END abortadas (banda $\sigma>400$\,ps; ajustar en proximo analisis)
      \end{itemize}
      \vspace{0.2em}
      \begin{alertblock}{\small Objetivo SHiP: 100\,ps (pref.\ 50\,ps)}
        \small Intrinseco: \textcolor{topcolor}{$\checkmark$} (TOP\_SUM4/SUM8)\\
        Con SPTR+FastIC: $\approx TOT_SIG$\,ps (estimado)
      \end{alertblock}
    \end{column}
  \end{columns}
  \vspace{0.1em}
  {\tiny \textit{CAVEAT_TEX}}
\end{frame}

\begin{frame}{Proximos pasos}
  \begin{enumerate}
    \item \textbf{EXEC\_02b}: reintroducir SPTR $\approx 106$\,ps + jitter FastIC $\approx 10$\,ps en cuadratura (hooks listos)
    \item \textbf{HOOK\_WALK}: correccion time-walk leading-edge (stub reservado en codigo)
    \item \textbf{Curva END completa}: ajustar \texttt{SIGMA\_BAND\_PS} para incluir $\sigma > 400$\,ps
    \item \textbf{Clustering}: \texttt{id//4} fijo vs ventana movil --- decision de Gerardo
    \item \textbf{Cierre 2$\times$2}: EJ-230 EndTop pendiente
    \item \textbf{Dataset listo}: 5\,000 evt/posicion disponible para analisis adicionales
  \end{enumerate}
  \vspace{0.3em}
  {\tiny \textit{CAVEAT_TEX}}
\end{frame}

\end{document}
"""

# Inject tokens
out = TEX_TEMPLATE
for token, value in TOKENS.items():
    out = out.replace(token, str(value))

out_tex = BEAMER_DIR / "EXEC_16_endtop_ej204.tex"
out_tex.write_text(out)
print(f"Written: {out_tex}")
