#!/usr/bin/env python3
"""EXEC_08 Step 3 — generate one Geant4 macro per scan position.

Reads pair_scan_config.json (produced by analyze_geometry.py) and writes
macros to macros/pairscan/ (one .mac per position).

Usage:
    python3 scripts/gen_pair_scan_macros.py [--config pair_scan_config.json]
                                             [--macro-dir macros/pairscan]
                                             [--result-dir results/pairscan_2026-06-11]
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

# Seed offsets chosen to be distinct from EXEC_07 seeds
# (EXEC_07: seed1=710000+1009*i max=740270, seed2=910000+2017*i max=970510)
SEED1_BASE = 820000
SEED1_STEP = 1009
SEED2_BASE = 1020000
SEED2_STEP = 2017

TEMPLATE = """\
# pair_scan_macros/{name}.mac — auto-generated by scripts/gen_pair_scan_macros.py
# EXEC_08 fine scan between top SiPMs {id_a} (x={x_a:+.1f} mm) and {id_b} (x={x_b:+.1f} mm)
# Position: x_true = {x_true:+.1f} mm  index={idx}  seed1={seed1}  seed2={seed2}
# Jitter: INTRINSIC (no SPTR hook in feat/endtop-sslg4)
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/run/numberOfThreads 16
/det/readout Top
/det/scintillator OPSC-101
/sipm/model AFBR-S4N66P024M
/run/initialize
/sipm/jitterSigma 0 ns
/gun/particle mu-
/gun/energy 1 GeV
/muon/angle 0
/random/setSeeds {seed1} {seed2}
/muon/gunX {x_true:.1f} mm
/run/beamOn {events}
"""


def mac_name(x_mm: float) -> str:
    """Canonical macro filename without extension: pairscan_x{+ddd.d}mm."""
    sign = "+" if x_mm >= 0 else ""
    return f"pairscan_x{sign}{x_mm:.1f}mm"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default="pair_scan_config.json",
                        type=pathlib.Path)
    parser.add_argument("--macro-dir", default="macros/pairscan",
                        type=pathlib.Path)
    parser.add_argument("--result-dir", default="results/pairscan_2026-06-11",
                        type=pathlib.Path)
    args = parser.parse_args(argv)

    cfg_path = pathlib.Path(args.config)
    if not cfg_path.exists():
        print(f"ERROR: config {cfg_path} not found. Run analyze_geometry.py first.",
              file=sys.stderr)
        return 1

    with open(cfg_path) as f:
        cfg = json.load(f)

    pair = cfg["pair"]
    positions = cfg["scan_positions_mm"]
    events = cfg["events_per_position"]

    macro_dir = pathlib.Path(args.macro_dir)
    macro_dir.mkdir(parents=True, exist_ok=True)

    result_dir = pathlib.Path(args.result_dir)

    generated = []
    for idx, x in enumerate(positions):
        name = mac_name(x)
        seed1 = SEED1_BASE + SEED1_STEP * idx
        seed2 = SEED2_BASE + SEED2_STEP * idx
        # Output path expected by run_pair_scan.sh (relative to build dir)
        outfile = f"../{result_dir}/{name}.root"
        body = TEMPLATE.format(
            name=name,
            id_a=pair["id_a"],
            id_b=pair["id_b"],
            x_a=pair["x_a_mm"],
            x_b=pair["x_b_mm"],
            x_true=x,
            idx=idx,
            seed1=seed1,
            seed2=seed2,
            events=events,
        )
        mac_path = macro_dir / f"{name}.mac"
        mac_path.write_text(body)
        generated.append(str(mac_path))

    print(f"Generated {len(generated)} macros in {macro_dir}/")
    print(f"  Positions: {positions[0]:+.1f} to {positions[-1]:+.1f} mm, "
          f"step={positions[1]-positions[0]:.1f} mm")
    print(f"  Pair: IDs ({pair['id_a']}, {pair['id_b']}), "
          f"x_mid={pair['x_mid_mm']:+.1f} mm, pitch={pair['pitch_mm']:.0f} mm")
    print(f"  Events per position: {events}")
    print(f"  Expected output: {result_dir}/pairscan_x*.root")
    return 0


if __name__ == "__main__":
    sys.exit(main())
