#!/usr/bin/env python3
"""Generate every empirical Beamer table/fragment from EJ-230 CSV products."""

from __future__ import annotations

import argparse
import hashlib
import math
import subprocess
from datetime import datetime
from pathlib import Path

import pandas as pd


REPO = Path(__file__).resolve().parents[1]
RESULTS = REPO / "results_ej230_analysis"
TABLES = RESULTS / "tables"
KEY_POSITIONS = (-690, -650, -400, 0, 400, 650, 690)
N_EVENTS = 2000


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def source_header(paths: list[Path]) -> str:
    lines = ["% AUTO-GENERATED by scripts/generate_exec14b_tables.py; do not edit."]
    for path in paths:
        lines.append(f"% source-sha256: {path.relative_to(REPO)} {digest(path)}")
    return "\n".join(lines) + "\n"


def write(name: str, body: str, sources: list[Path]) -> None:
    path = TABLES / name
    path.write_text(source_header(sources) + body.rstrip() + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(REPO)}")


def row(summary: pd.DataFrame, x_mm: int, group: str) -> pd.Series:
    selected = summary[(summary.x_beam_mm == x_mm) & (summary.grupo == group)]
    if len(selected) != 1:
        raise RuntimeError(f"expected one summary row for x={x_mm}, group={group}; got {len(selected)}")
    return selected.iloc[0]


def pm(value: float, error: float, digits: int) -> str:
    return rf"${value:.{digits}f}\pm{error:.{digits}f}$"


def macro_number(value: float, digits: int) -> str:
    if not math.isfinite(value):
        return r"\text{--}"
    return f"{value:.{digits}f}"


def macro_x(x_mm: int) -> str:
    return f"neg{abs(x_mm)}" if x_mm < 0 else f"pos{x_mm}"


def only(frame: pd.DataFrame, column: str) -> object:
    values = frame[column].dropna().unique()
    if len(values) != 1:
        raise RuntimeError(f"expected one {column} value, got {values.tolist()}")
    return values[0]


def tex_text(value: object) -> str:
    return str(value).replace("_", r"\_")


def position_table(
    x_mm: int, summary: pd.DataFrame, positions: pd.DataFrame, localization: pd.DataFrame
) -> str:
    left = row(summary, x_mm, "end_left_all")
    right = row(summary, x_mm, "end_right_all")
    top = row(summary, x_mm, "nearest_top")
    pos = positions.loc[x_mm]
    gate = localization.loc[x_mm]
    status = {
        "strict maximum at nearest": "exact geometry",
        "known window-track dip <=15%": "window-track exception",
        "strict statistical tie <=1 sigma": "statistical tie: two nearest",
    }[gate.reason]
    t_error = top.t_rms_ns / math.sqrt(top.npe_mean * N_EVENTS)
    fpt_error = top.fpt_rms_ns / math.sqrt(N_EVENTS)
    return rf"""\begin{{tabular}}{{lr}}
\toprule Quantity & Value \\ \midrule
End L $N_{{pe}}$ & {pm(left.npe_mean, left.npe_rms / math.sqrt(N_EVENTS), 1)} \\
End R $N_{{pe}}$ & {pm(right.npe_mean, right.npe_rms / math.sqrt(N_EVENTS), 1)} \\
Nearest Top ID & {int(pos.nearest_top_id)} ({status}) \\
Nearest Top $N_{{pe}}$ & {pm(top.npe_mean, top.npe_rms / math.sqrt(N_EVENTS), 1)} \\
Nearest Top $\langle t\rangle$ & {pm(top.t_mean_ns, t_error, 4)} ns \\
Nearest Top FPT & {pm(top.fpt_mean_ns, fpt_error, 5)} ns \\
\bottomrule
\end{{tabular}}"""


def window_contrasts(profiles: pd.DataFrame) -> pd.DataFrame:
    definitions = [
        ("existing_x-650", "Existing -650", 19, 18),
        ("run_A_x-652", "A -652 center", 19, 18),
        ("run_B_x-642", "B -642 midpoint", 19, 18),
        ("run_C1_x-648", "C1 -648 (+4 mm)", 19, 18),
        ("run_C2_x-654_exact_mirror", "C2 -654 mirror", 17, 18),
    ]
    rows = []
    for run, label, high_id, low_id in definitions:
        selected = profiles[profiles.run == run].set_index("channel")
        high, low = selected.loc[high_id], selected.loc[low_id]
        contrast = high.npe_mean - low.npe_mean
        error = math.hypot(high.npe_sem, low.npe_sem)
        rows.append({
            "run": run,
            "label": label,
            "contrast": contrast,
            "error": error,
            "significance": contrast / error,
            "ratio_excess_percent": 100.0 * (high.npe_mean / low.npe_mean - 1.0),
        })
    return pd.DataFrame(rows)


def main() -> int:
    global TABLES
    parser = argparse.ArgumentParser()
    parser.add_argument("--tables-dir", type=Path, default=TABLES)
    args = parser.parse_args()
    TABLES = args.tables_dir.resolve()
    TABLES.mkdir(parents=True, exist_ok=True)

    summary_path = RESULTS / "summary_exec07.csv"
    position_path = RESULTS / "per_position_exec07.csv"
    localization_path = RESULTS / "top_localization_gate.csv"
    fit_path = RESULTS / "fit_results_exec07.csv"
    fano_path = RESULTS / "exec10_fano_fit.csv"
    landau_path = RESULTS / "exec10_landau_mpv.csv"
    velocity_path = RESULTS / "exec10_velocity_fits.csv"
    tn_path = RESULTS / "csv/exec13_tN_summary.csv"
    window_path = RESULTS / "csv/exec08b_window_dip_profiles.csv"
    timing_path = RESULTS / "csv/exec08b_timing_gate.csv"
    tails_path = RESULTS / "csv/exec09_tail_comparison.csv"
    root_validation_path = RESULTS / "root_validation_exec14b.csv"

    required = [
        summary_path, position_path, localization_path, fit_path, fano_path,
        landau_path, velocity_path, tn_path, window_path, timing_path, tails_path,
        root_validation_path,
    ]
    missing = [path for path in required if not path.is_file()]
    if missing:
        raise SystemExit("missing CSV inputs:\n" + "\n".join(str(path) for path in missing))

    summary = pd.read_csv(summary_path)
    positions = pd.read_csv(position_path).set_index("x_beam_mm")
    localization = pd.read_csv(localization_path).set_index("x_beam_mm")
    fits = pd.read_csv(fit_path).set_index("side")
    fano = pd.read_csv(fano_path).iloc[0]
    landau = pd.read_csv(landau_path)
    velocity = pd.read_csv(velocity_path)
    tn = pd.read_csv(tn_path)
    profiles = pd.read_csv(window_path)
    timing = pd.read_csv(timing_path)
    tails = pd.read_csv(tails_path)
    root_validation = pd.read_csv(root_validation_path)
    contrasts = window_contrasts(profiles)
    main_validation = root_validation[root_validation.configuration == "main_scan_EndTop"]
    window_validation = root_validation[root_validation.configuration == "window_dip_EndTop"]
    end_validation = root_validation[root_validation.configuration == "end_only_End"]

    position_sources = [summary_path, position_path, localization_path]
    for x_mm in positions.index.astype(int):
        filename = f"key_position_{x_mm}.tex" if x_mm in KEY_POSITIONS else f"position_{x_mm}.tex"
        write(filename, position_table(x_mm, summary, positions, localization), position_sources)

    head = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=REPO, text=True).strip()
    main_path = Path(main_validation.path.iloc[0]).parent
    visible_data_path = "/".join(main_path.parts[-2:])
    provenance = rf"""\begin{{columns}}[T]\column{{0.62\textwidth}}
\textbf{{Standalone EJ-230 report}}\\
\textbf{{Branch:}} \texttt{{feat/ej230-sslg4}}\\
\textbf{{Generation source commit:}} \texttt{{{head[:12]}}}\\
\textbf{{Data session:}} \texttt{{{tex_text(only(main_validation, "session"))}}}
on \texttt{{{only(main_validation, "machine")}}}\\
\textbf{{Data path:}} \texttt{{{tex_text(visible_data_path)}}};
generated {only(main_validation, "generation_date")}\\
\textbf{{Report generation:}} {datetime.now().astimezone().strftime("%Y-%m-%d %H:%M %Z")}
\begin{{itemize}}\small
  \item {len(main_validation)} positions $\times$ {int(only(main_validation, "expected_events"))}
        events; main scan produced on \texttt{{{only(main_validation, "machine")}}}
        with {int(only(main_validation, "threads"))} threads.
  \item Directed controls on \texttt{{{only(window_validation, "machine")}}} with
        {int(only(window_validation, "threads"))} threads:
        {len(window_validation)} EndTop $\times$ {int(only(window_validation, "expected_events"))}
        events and {len(end_validation)} End-only $\times$
        {int(only(end_validation, "expected_events"))} events.
  \item 16 End + 70 Top channels; jitter fixed to zero.
  \item EJ-230 via SSLG4 \texttt{{OPSC-106}}: yield 9700/MeV, $\tau_r=0.5$ ns,
        $\tau_d=1.5$ ns, ABSLENGTH=120 cm.
\end{{itemize}}
\column{{0.35\textwidth}}
\begin{{alertblock}}{{Scope}}
Top 70 SiPM is a simulation coverage study. Real hardware: 32 Top SiPMs.
All reported timing is intrinsic, without SPTR or electronics jitter.
\end{{alertblock}}
\end{{columns}}"""
    write("provenance.tex", provenance, [summary_path, root_validation_path])

    left, right = fits.loc["left"], fits.loc["right"]
    mean_lambda = 0.5 * (left.lambda_eff_cm + right.lambda_eff_cm)
    macro_lines = [
        rf"\newcommand{{\LambdaEffL}}{{{left.lambda_eff_cm:.2f}}}",
        rf"\newcommand{{\LambdaEffLerr}}{{{left.lambda_eff_error_cm:.2f}}}",
        rf"\newcommand{{\LambdaEffR}}{{{right.lambda_eff_cm:.2f}}}",
        rf"\newcommand{{\LambdaEffRerr}}{{{right.lambda_eff_error_cm:.2f}}}",
        rf"\newcommand{{\LambdaEffMean}}{{{mean_lambda:.1f}}}",
        rf"\newcommand{{\FanoC}}{{{fano.c:.6f}}}",
        rf"\newcommand{{\FanoCerr}}{{{fano.c_error:.6f}}}",
        rf"\newcommand{{\FanoChi}}{{{fano.chi2_ndf:.2f}}}",
        rf"\newcommand{{\FanoSqrtC}}{{{math.sqrt(fano.c):.3f}}}",
    ]
    n_words = {4: "Nfour", 20: "Ntwenty"}
    for item in tn.itertuples():
        stem = f"execXIII{item.group.replace('_', '')}x{macro_x(int(item.x_mm))}{n_words[int(item.N)]}"
        macro_lines.extend([
            rf"\newcommand{{\{stem}MeanPs}}{{{macro_number(item.mean_ns * 1000, 0)}}}",
            rf"\newcommand{{\{stem}RmsPs}}{{{macro_number(item.rms_ns * 1000, 0)}}}",
            rf"\newcommand{{\{stem}SigmaFitPs}}{{{macro_number(item.sigma_fit_ns * 1000, 0)}}}",
        ])
    write("exec14_macros.tex", "\n".join(macro_lines), [fit_path, fano_path, tn_path])

    write(
        "attenuation_fit.tex",
        rf"$\lambda_{{\mathrm{{eff}},L}}={left.lambda_eff_cm:.2f}\pm{left.lambda_eff_error_cm:.2f}$ cm, "
        rf"$\lambda_{{\mathrm{{eff}},R}}={right.lambda_eff_cm:.2f}\pm{right.lambda_eff_error_cm:.2f}$ cm; "
        r"the mean-time slope is tail-biased and is not a propagation velocity.",
        [fit_path],
    )

    write(
        "fano_fit.tex",
        rf"$F=1+c\langle N_{{pe}}\rangle$, $c={fano.c:.6f}\pm{fano.c_error:.6f}$, "
        rf"$\chi^2/\mathrm{{ndf}}={fano.chi2_ndf:.2f}$. "
        r"Poisson $F=1$ is approached only at low light.",
        [fano_path],
    )

    exceptions = localization[localization.window_track_exception]
    write(
        "top_localization_summary.tex",
        (
            rf"""\begin{{block}}{{\footnotesize CSV-derived localization gate}}
\scriptsize {int(localization.passed.sum())}/{len(localization)} positions pass. """
            rf"{len(exceptions)} positions use the documented window-track rule; the maximum "
            rf"nearest-channel deficit is {100.0 * exceptions.relative_difference.max():.2f}\%. "
            r"""All remaining positions have their strict maximum at the geometrically nearest channel.
\end{block}"""
        ),
        [localization_path],
    )

    landau_rows = []
    for x_mm in KEY_POSITIONS:
        channel = int(positions.loc[x_mm].nearest_top_id)
        item = landau[(landau.x_beam_mm == x_mm) & (landau.channel == channel)].iloc[0]
        landau_rows.append(
            rf"{x_mm:+d} & {channel} & {pm(item.mpv, item.mpv_error, 1)} & "
            rf"{pm(item.width, item.width_error, 1)} & {item.chi2_ndf:.2f} \\"
        )
    write(
        "landau_key_positions.tex",
        r"""\centering\small
\begin{tabular}{rrrrr}\toprule
$x$ [mm] & channel & MPV [Npe] & Landau width [Npe] & $\chi^2/ndf$ \\ \midrule
""" + "\n".join(landau_rows) + r"""
\bottomrule\end{tabular}
\begin{block}{Interpretation}
The right tail originates primarily from Landau-like energy-loss fluctuations; Poisson
counting dominates only in the few-PE limit.
\end{block}""",
        [landau_path, position_path],
    )

    velocity_labels = {
        "mean_ns": "all-photon mean",
        "t50_ns": r"all-photon $t_{50}$",
        "fpt_mean_ns": "mean FPT",
    }
    velocity_rows = []
    for estimator in ("mean_ns", "t50_ns", "fpt_mean_ns"):
        item = velocity[(velocity.scope == "combined") & (velocity.estimator == estimator)].iloc[0]
        velocity_rows.append(
            rf"{velocity_labels[estimator]} & {pm(item.velocity_cm_ns, item.velocity_error_cm_ns, 3)} "
            rf"& {item.chi2_ndf:.1f} \\"
        )
    write("velocity_estimators.tex", "\n".join(velocity_rows), [velocity_path])

    test_rows = []
    for item in contrasts.itertuples():
        test_rows.append(
            rf"{item.label} & {pm(item.contrast, item.error, 2)} & ${item.significance:.2f}$ \\"
        )
    write("window_dip_test.tex", "\n".join(test_rows), [window_path])
    mirror = contrasts[contrasts.run.isin(["existing_x-650", "run_C2_x-654_exact_mirror"])]
    centered = contrasts.loc[contrasts.run == "run_A_x-652"].iloc[0]
    midpoint = contrasts.loc[contrasts.run == "run_B_x-642"].iloc[0]
    write(
        "window_dip_mechanism.tex",
        rf"\item Empirically, a track at $\pm2$ mm from the window centre changes the "
        rf"local contrast by {mirror.ratio_excess_percent.mean():.1f}\% with minimum "
        rf"significance {mirror.significance.min():.1f}$\sigma$. The measured centered "
        rf"and midpoint contrast significances are {centered.significance:.2f}$\sigma$ "
        rf"and {midpoint.significance:.2f}$\sigma$, respectively.",
        [window_path],
    )
    write(
        "window_dip_summary.tex",
        rf"Local symmetric $\pm2$ mm effect: {mirror.ratio_excess_percent.mean():.1f}\% "
        rf"with significance {mirror.significance.min():.1f}--{mirror.significance.max():.1f}$\sigma$; "
        rf"centered/midpoint contrast significances: {centered.significance:.2f}$\sigma$/"
        rf"{midpoint.significance:.2f}$\sigma$.",
        [window_path],
    )

    ratio_rows = []
    for item in timing.itertuples():
        ratio_rows.append(
            rf"{int(item.x_beam_mm):+d} & {item.side[0].upper()} & "
            rf"{pm(item.sigma_endtop_ps, item.sigma_endtop_error_ps, 1)} & "
            rf"{pm(item.sigma_end_only_ps, item.sigma_end_only_error_ps, 1)} & "
            rf"{pm(item.observed_sigma_ratio, item.observed_sigma_ratio_error, 3)} \\"
        )
    write("endtop_endonly_ratio.tex", "\n".join(ratio_rows), [timing_path])
    aggregate = tails[tails.group == "all_end"]
    t99 = aggregate.t99_ns_difference
    late_sig = aggregate[["frac_gt10_difference_sigma", "frac_gt20_difference_sigma"]].abs().min().min()
    write(
        "endtop_endonly_tails.tex",
        rf"Across $x=0,\pm400$ mm, EndTop minus End-only $t_{{99}}$ ranges from "
        rf"{t99.min():.2f} to {t99.max():.2f} ns; the minimum absolute significance "
        rf"among the two late-fraction differences is {late_sig:.1f}$\sigma$.",
        [tails_path],
    )

    timing_rows = []
    for x_mm in KEY_POSITIONS:
        top = row(summary, x_mm, "nearest_top")
        npe_error = top.npe_rms / math.sqrt(N_EVENTS)
        sigma_error = 0.5 * top.sigma_est_ps * npe_error / top.npe_mean
        timing_rows.append(
            rf"{x_mm:+d} & {pm(top.npe_mean, npe_error, 1)} & {pm(top.sigma_est_ps, sigma_error, 2)} \\"
        )
    write("top_timing_estimates.tex", "\n".join(timing_rows), [summary_path])
    comparison_rows = []
    for x_mm in KEY_POSITIONS:
        top = row(summary, x_mm, "nearest_top")
        item = tn[(tn.x_mm == x_mm) & (tn.group == "top_nearest") & (tn.N == 4)].iloc[0]
        npe_error = top.npe_rms / math.sqrt(N_EVENTS)
        estimate_error = 0.5 * top.sigma_est_ps * npe_error / top.npe_mean
        fit_text = (
            pm(item.sigma_fit_ns * 1000, item.sigma_fit_err_ns * 1000, 1)
            if math.isfinite(item.sigma_fit_err_ns)
            else rf"${item.sigma_fit_ns * 1000:.1f}$"
        )
        comparison_rows.append(
            rf"{x_mm:+d} & {pm(top.sigma_est_ps, estimate_error, 2)} & {fit_text} \\"
        )
    write("top_timing_comparison.tex", "\n".join(comparison_rows), [summary_path, tn_path])

    sigma_rows = summary[summary.grupo.isin(["end_left_A_SUM4", "end_right_A_SUM4"])]
    sigma_values = sigma_rows.sigma_grupo_ps.dropna()
    center_sigma = sigma_rows[sigma_rows.x_beam_mm == 0].sigma_grupo_ps.mean()
    write(
        "sum4_timing.tex",
        rf"Intrinsic End $\sigma_{{group}}$ at $x=0$: {center_sigma:.1f} ps; "
        rf"full-scan mean {sigma_values.mean():.0f} ps and range "
        rf"{sigma_values.min():.0f}--{sigma_values.max():.0f} ps.",
        [summary_path],
    )

    tn4 = tn[tn.N == 4]
    near = tn4[tn4.group == "end_near"].rms_ns * 1000
    top4 = tn4[tn4.group == "top_nearest"].rms_ns * 1000
    write(
        "tN_summary.tex",
        rf"""\begin{{block}}{{\footnotesize CSV-derived synthesis}}
\scriptsize Near-End RMS$(t_4)$ spans {near.min():.0f}--{near.max():.0f} ps across key positions;
nearest-Top RMS$(t_4)$ spans {top4.min():.0f}--{top4.max():.0f} ps.
At $x=0$, the two End groups give {near.loc[tn4[(tn4.group == "end_near") & (tn4.x_mm == 0)].index[0]]:.0f} ps.
\end{{block}}""",
        [tn_path],
    )

    center_left = row(summary, 0, "end_left_all")
    center_right = row(summary, 0, "end_right_all")
    center_top = row(summary, 0, "nearest_top")
    edge_left = row(summary, -690, "end_left_all")
    edge_top = row(summary, -690, "nearest_top")
    ratio_min, ratio_max = timing.observed_sigma_ratio.min(), timing.observed_sigma_ratio.max()
    write(
        "numerical_conclusions.tex",
        rf"""\small\begin{{itemize}}
 \item At center: End sum {center_left.npe_mean + center_right.npe_mean:.1f}, nearest Top
       {center_top.npe_mean:.1f}; at $x=-690$ mm: End$_L$ {edge_left.npe_mean:.1f},
       nearest Top {edge_top.npe_mean:.1f}.
 \item $\lambda_{{eff}}$: L {left.lambda_eff_cm:.2f}$\pm${left.lambda_eff_error_cm:.2f} cm,
       R {right.lambda_eff_cm:.2f}$\pm${right.lambda_eff_error_cm:.2f} cm.
 \item Nearest-Top $F=1+({fano.c:.6f}\pm{fano.c_error:.6f})\langle N_{{pe}}\rangle$
       ($\chi^2/ndf={fano.chi2_ndf:.2f}$).
 \item \input{{../tables/sum4_timing.tex}}
 \item EndTop/End-only timing ratio: {ratio_min:.3f}--{ratio_max:.3f}; no time-acceptance window.
 \item Near-End RMS$(t_4)$: {near.min():.0f}--{near.max():.0f} ps; nearest-Top RMS$(t_4)$:
       {top4.min():.0f}--{top4.max():.0f} ps.
 \item Directed EJ-230 window and End-only controls replace all inherited special-control placeholders.
\end{{itemize}}""",
        [summary_path, fit_path, fano_path, timing_path, tn_path],
    )

    write(
        "threshold_rationale.tex",
        rf"Minimum signal in the scan is End R "
        rf"{pm(row(summary, -690, 'end_right_all').npe_mean, row(summary, -690, 'end_right_all').npe_rms / math.sqrt(N_EVENTS), 1)} "
        r"at $x=-690$ mm; the nominal 4 PE threshold remains far below that signal.",
        [summary_path],
    )
    tie = localization.loc[300]
    main_root_validation = root_validation[
        root_validation.path.str.contains("/results_ej230/data/photon_hits_x", regex=False)
    ]
    main_valid = int(main_root_validation.valid.sum())
    write(
        "validation_summary.tex",
        rf"""\begin{{itemize}}
 \item {main_valid}/{len(main_root_validation)} main ROOT files pass: event IDs 0--1999,
       matching beam x, aggregate IDs 0--85.
 \item Top localization passes all positions under the documented window-track/statistical-tie rules.
 \item At x=300 mm the two candidates differ by {tie.max_minus_nearest_npe / tie.difference_error_npe:.2f} sigma.
 \item MPT checks: RINDEX 1.58, yield 9700/MeV, decay 1.5 ns, rise 0.5 ns,
       ABSLENGTH 120 cm, emission peak $\approx391$ nm.
\end{{itemize}}""",
        [localization_path, root_validation_path],
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
