# ─────────────────────────────────────────────────────────────────────────────
# EJ-228 cylinder visualisation macro
# ─────────────────────────────────────────────────────────────────────────────

/vis/open OGL 1200x800

/run/initialize

/vis/drawVolume
/vis/viewer/set/viewpointVector 1 1 0.5
/vis/viewer/set/upVector 0 0 1
/vis/viewer/zoom 2.5

# Trajectories
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set mu- blue
/vis/modeling/trajectories/drawByParticleID-0/set mu+ cyan
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton yellow

/vis/scene/endOfEventAction accumulate 20

/vis/viewer/set/style wireframe
/vis/viewer/flush

/run/beamOn 5
