#include "SteppingAction.hh"

#include "G4OpticalPhoton.hh"
#include "G4Step.hh"
#include "G4SystemOfUnits.hh"
#include "G4Track.hh"
#include "G4VPhysicalVolume.hh"

// hc constant for wavelength calculation [eV·nm]
static constexpr G4double kHC_eVnm = 1239.84193;  // eV·nm

void SteppingAction::UserSteppingAction(const G4Step* step) {
    auto* track = step->GetTrack();

    if (track->GetDefinition() != G4OpticalPhoton::Definition()) return;

    // ── Wavelength filter ────────────────────────────────────────────────────
    // Kill photons outside the SiPM sensitivity window (300–900 nm).
    // EJ-200 emits in 380–500 nm so this filter has negligible effect on
    // scintillation photons, but efficiently removes any IR secondaries or
    // photons generated by Cherenkov outside the PDE range, avoiding
    // unnecessary tracking.
    const G4double energy = track->GetKineticEnergy();
    if (energy > 0.0) {
        // energy is in G4 internal units (MeV); eV = 1e-6, nm = 1 mm * 1e-6
        const G4double wl_nm = kHC_eVnm / (energy / eV);
        if (wl_nm < 300.0 || wl_nm > 900.0) {
            track->SetTrackStatus(fStopAndKill);
            return;
        }
    }

    // ── Geometry escape guard ────────────────────────────────────────────────
    auto* postVol = step->GetPostStepPoint()->GetPhysicalVolume();

    // Kill if outside the world entirely (safety net).
    if (postVol == nullptr) {
        track->SetTrackStatus(fStopAndKill);
        return;
    }

    // Kill photons that reach the air (world) volume.
    // Photons going bar→Mylar wrap→SiPM land in EndSiPMLV or TopSiPMLV, not
    // WorldLV, so this correctly spares detected photons.
    // Photons that escape through the Mylar without TIR are wasted and killed.
    if (postVol->GetLogicalVolume()->GetName() == "WorldLV") {
        track->SetTrackStatus(fStopAndKill);
    }
}
