#ifndef TSUM_VEFF_FIGURE_COMMON_C
#define TSUM_VEFF_FIGURE_COMMON_C
#include <TCanvas.h>
#include <TFile.h>
#include <TF1.h>
#include <TGraphErrors.h>
#include <TH1D.h>
#include <TH2D.h>
#include <TLatex.h>
#include <TLegend.h>
#include <TLine.h>
#include <TMatrixDSym.h>
#include <TMultiGraph.h>
#include <TNamed.h>
#include <TPaveText.h>
#include <TStyle.h>
#include <TTree.h>

#include <algorithm>
#include <cmath>
#include <fstream>
#include <map>
#include <numeric>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace tvfig {
struct Table{std::vector<std::string>h;std::vector<std::map<std::string,std::string>>r;};
std::vector<std::string>split(const std::string&s){std::stringstream ss(s);std::string x;std::vector<std::string>v;while(std::getline(ss,x,','))v.push_back(x);return v;}
Table read(const std::string&p){std::ifstream f(p);if(!f)throw std::runtime_error("cannot open "+p);Table t;std::string s;std::getline(f,s);t.h=split(s);while(std::getline(f,s)){if(s.empty())continue;auto v=split(s);std::map<std::string,std::string>r;for(size_t j=0;j<t.h.size()&&j<v.size();j++)r[t.h[j]]=v[j];t.r.push_back(r);}return t;}
double d(const std::map<std::string,std::string>&r,const std::string&k){return std::stod(r.at(k));}int i(const std::map<std::string,std::string>&r,const std::string&k){return std::stoi(r.at(k));}
std::string mat(const std::string&s){return s=="EJ200"?"EJ-200":s=="EJ204"?"EJ-204":"EJ-230";}std::string safe(const std::string&s){return s=="EJ-200"?"EJ_200":s=="EJ-204"?"EJ_204":"EJ_230";}
int color(const std::string&m){return m=="EJ-200"?kBlue+1:m=="EJ-204"?kGreen+2:kRed+1;}
void style(){gStyle->SetOptStat(0);gStyle->SetOptFit(0);gStyle->SetTextFont(42);gStyle->SetLabelFont(42,"XYZ");gStyle->SetTitleFont(42,"XYZ");gStyle->SetTitleSize(.05,"XYZ");gStyle->SetLabelSize(.043,"XYZ");gStyle->SetPadLeftMargin(.15);gStyle->SetPadBottomMargin(.14);gStyle->SetPadTopMargin(.07);gStyle->SetPadRightMargin(.04);}
void provenance(TFile&o,const std::string&method){o.cd();TNamed s("source","sources/tsum_veff.root; 21 current corrected-transport cells, N=10000 each; no new simulation");TNamed m("method",method.c_str());s.Write();m.Write();}
void meta(const std::string&name,const std::string&question,const std::string&method){std::ofstream f("figures/"+name+".meta.json");f<<"{\n  \"figure\": \""<<name<<"\",\n  \"created_utc\": \"2026-09-14\",\n  \"question\": \""<<question<<"\",\n  \"input\": \"current corrected-transport event data; N=10000/cell\",\n  \"method\": \""<<method<<"\",\n  \"generator\": \"CERN ROOT macro macros/"<<name<<".C\"\n}\n";}
TF1* cloneF(TFile&f,const std::string&p,const std::string&n){auto*x=(TF1*)f.Get(p.c_str());if(!x)throw std::runtime_error("missing "+p);return (TF1*)x->Clone(n.c_str());}

void position(const std::string&slug,bool tsum){style();std::string m=mat(slug),obs=tsum?"tsum":"t0",name=(tsum?"tsum_vs_x_":"mean_t0_vs_x_")+slug;TFile in("sources/tsum_veff.root","READ"),out(("figures/"+name+".root").c_str(),"RECREATE");auto*g0=(TGraphErrors*)in.Get(("position_graphs/"+obs+"_vs_x_"+safe(m)).c_str());if(!g0)throw std::runtime_error("missing position graph");auto*g=(TGraphErrors*)g0->Clone("measured");double center=0;for(int j=0;j<g->GetN();j++)if(std::abs(g->GetX()[j])<1e-9)center=g->GetY()[j];for(int j=0;j<g->GetN();j++){g->GetY()[j]=1000*(g->GetY()[j]-center);g->SetPointError(j,0,1000*g->GetErrorY(j));}auto*fc0=cloneF(in,"position_fits/"+obs+"_vs_x_"+safe(m)+"_constant","constant_fit");auto*fq0=cloneF(in,"position_fits/"+obs+"_vs_x_"+safe(m)+"_even_quadratic","even_quadratic_fit");auto*fc=new TF1("constant_relative","[0]",-.68,.68);fc->SetParameter(0,1000*(fc0->GetParameter(0)-center));auto*fq=new TF1("even_quadratic_relative","[0]+[1]*x*x",-.68,.68);fq->SetParameters(1000*(fq0->GetParameter(0)-center),1000*fq0->GetParameter(1));fc->SetLineColor(kGray+2);fc->SetLineStyle(2);fc->SetLineWidth(3);fq->SetLineColor(kRed+1);fq->SetLineWidth(3);g->SetMarkerStyle(20);g->SetMarkerSize(1.25);g->SetMarkerColor(color(m));g->SetLineColor(color(m));g->SetTitle("");g->GetXaxis()->SetTitle("Muon position x [m]");g->GetYaxis()->SetTitle(tsum?"<#it{T}_{sum}> - center [ps]":"<#it{T}_{0}> - center [ps]");double ymin=*std::min_element(g->GetY(),g->GetY()+g->GetN())-6,ymax=*std::max_element(g->GetY(),g->GetY()+g->GetN())+6;g->GetYaxis()->SetRangeUser(ymin,ymax);TCanvas c(name.c_str(),"",930,650);g->Draw("AP");fc->Draw("SAME");fq->Draw("SAME");TLegend leg(.17,.70,.49,.89);leg.SetBorderSize(0);leg.SetFillStyle(0);leg.AddEntry(g,"event mean #pm SEM","p");leg.AddEntry(fc,"constant","l");leg.AddEntry(fq,"even quadratic","l");leg.Draw();TLatex tx;tx.SetNDC();tx.SetTextSize(.043);tx.DrawLatex(.70,.86,m.c_str());tx.SetTextSize(.034);tx.DrawLatex(.49,.18,Form("a_{2}=%.2f #pm %.2f ps/m^{2}",1000*fq0->GetParameter(1),1000*fq0->GetParError(1)));c.SaveAs(("figures/"+name+".pdf").c_str());out.cd();g->Write();fc0->Write();fq0->Write();fc->Write();fq->Write();c.Write();provenance(out,"Seven physical x points; event mean and SEM; ROOT constant and even-quadratic fits; plotted relative to measured x=0 mean");out.Close();meta(name,"Is the mean timing estimator position independent?","Seven event means with SEM; constant and even-quadratic ROOT fits; x in metres");}

void propagation(const std::string&slug){style();std::string m=mat(slug),name="propagation_time_vs_distance_"+slug,gn="g_first_pe_"+safe(m);TFile in("sources/tsum_veff.root","READ"),out(("figures/"+name+".root").c_str(),"RECREATE");auto*tree=(TTree*)in.Get(("propagation_graphs/"+gn+"_points").c_str());if(!tree)throw std::runtime_error("missing points");double dd=0,y=0,e=0;int side=0,x=0;tree->SetBranchAddress("distance_m",&dd);tree->SetBranchAddress("mean_time_ns",&y);tree->SetBranchAddress("sem_ns",&e);tree->SetBranchAddress("side",&side);tree->SetBranchAddress("x_mm",&x);std::vector<double>dl,yl,el,dr,yr,er,z;for(Long64_t j=0;j<tree->GetEntries();j++){tree->GetEntry(j);(side==0?dl:dr).push_back(dd);(side==0?yl:yr).push_back(y);(side==0?el:er).push_back(e);}z.assign(dl.size(),0);TGraphErrors gl(dl.size(),dl.data(),yl.data(),z.data(),el.data()),gr(dr.size(),dr.data(),yr.data(),z.data(),er.data());gl.SetName("left_means");gr.SetName("right_means");gl.SetMarkerStyle(20);gr.SetMarkerStyle(24);gl.SetMarkerColor(kBlue+1);gr.SetMarkerColor(kRed+1);gl.SetLineColor(kBlue+1);gr.SetLineColor(kRed+1);for(auto*g:{&gl,&gr}){g->SetMarkerSize(1.25);}auto*fl=cloneF(in,"propagation_fits/"+gn+"_linear","linear_fit");auto*fq=cloneF(in,"propagation_fits/"+gn+"_quadratic","quadratic_fit");fl->SetLineColor(kGray+2);fl->SetLineStyle(2);fl->SetLineWidth(3);fq->SetLineColor(kGreen+2);fq->SetLineWidth(3);TCanvas c(name.c_str(),"",930,650);TMultiGraph mg;mg.Add(&gl,"P");mg.Add(&gr,"P");mg.SetTitle("");mg.Draw("A");mg.GetXaxis()->SetTitle("Propagation distance d [m]");mg.GetYaxis()->SetTitle("Mean first-PE time [ns]");fl->Draw("SAME");fq->Draw("SAME");TLegend leg(.16,.66,.49,.89);leg.SetBorderSize(0);leg.SetFillStyle(0);leg.AddEntry(&gl,"LEFT means","p");leg.AddEntry(&gr,"RIGHT means","p");leg.AddEntry(fl,"linear g_{1}(d)","l");leg.AddEntry(fq,"quadratic g_{2}(d)","l");leg.Draw();TLatex tx;tx.SetNDC();tx.SetTextSize(.043);tx.DrawLatex(.72,.86,m.c_str());c.SaveAs(("figures/"+name+".pdf").c_str());out.cd();gl.Write();gr.Write();fl->Write();fq->Write();c.Write();provenance(out,"Fourteen LEFT/RIGHT event means with SEM; dL=0.7+x and dR=0.7-x m; combined ROOT linear and quadratic fits");out.Close();meta(name,"Do LEFT and RIGHT collapse onto one propagation curve, and is it linear?","Fourteen side-tagged means; common linear and quadratic ROOT fits");}

void residuals(const std::string&slug){style();std::string m=mat(slug),name="propagation_residuals_"+slug,gn="g_first_pe_"+safe(m);TFile in("sources/tsum_veff.root","READ"),out(("figures/"+name+".root").c_str(),"RECREATE");auto*g=(TGraphErrors*)in.Get(("propagation_graphs/"+gn).c_str());auto*fl=cloneF(in,"propagation_fits/"+gn+"_linear","linear_fit");auto*fq=cloneF(in,"propagation_fits/"+gn+"_quadratic","quadratic_fit");if(!g)throw std::runtime_error("missing graph");TCanvas c(name.c_str(),"",1000,720);c.Divide(1,2,.001,.001);for(int k=0;k<2;k++){c.cd(k+1);gPad->SetLeftMargin(.13);gPad->SetBottomMargin(k? .18:.10);std::vector<double>x,y,ex,ey;TF1*f=k?fq:fl;for(int j=0;j<g->GetN();j++){x.push_back(g->GetX()[j]);y.push_back(1000*(g->GetY()[j]-f->Eval(g->GetX()[j])));ex.push_back(0);ey.push_back(1000*g->GetErrorY(j));}auto*r=new TGraphErrors(x.size(),x.data(),y.data(),ex.data(),ey.data());r->SetName(k?"quadratic_residuals":"linear_residuals");r->SetMarkerStyle(k?21:20);r->SetMarkerColor(k?kGreen+2:kBlue+1);r->SetTitle("");r->GetXaxis()->SetTitle("Propagation distance d [m]");r->GetYaxis()->SetTitle(k?"data - quadratic [ps]":"data - linear [ps]");double a=*std::min_element(y.begin(),y.end())-3,b=*std::max_element(y.begin(),y.end())+3;r->GetYaxis()->SetRangeUser(a,b);r->Draw("AP");TLine line(.04,0,1.36,0);line.SetLineStyle(2);line.Draw();TLatex tx;tx.SetNDC();tx.SetTextSize(.05);tx.DrawLatex(.75,.82,k?"quadratic":"linear");out.cd();r->Write();}c.SaveAs(("figures/"+name+".pdf").c_str());out.cd();c.Write();fl->Write();fq->Write();provenance(out,"Measured mean minus fitted mean; same fourteen points and SEM as propagation fit; residuals in ps");out.Close();meta(name,"Do linear or quadratic propagation fits leave systematic residuals?","Residuals of fourteen LEFT/RIGHT means around the two required propagation models");}

void veff(const std::string&slug){style();std::string m=mat(slug),name="veff_vs_distance_"+slug,gn="g_first_pe_"+safe(m);TFile in("sources/tsum_veff.root","READ"),out(("figures/"+name+".root").c_str(),"RECREATE");auto*f=cloneF(in,"propagation_fits/"+gn+"_quadratic","quadratic_fit");auto*cm=(TMatrixDSym*)in.Get(("propagation_fits/"+gn+"_quadratic_covariance").c_str());if(!cm)throw std::runtime_error("missing covariance");std::vector<double>x,y,ex,ey;for(int j=0;j<=130;j++){double q=.05+.01*j,s=f->GetParameter(1)+2*f->GetParameter(2)*q,v=1000/s,db1=-1000/(s*s),db2=-2000*q/(s*s),var=db1*db1*(*cm)(1,1)+db2*db2*(*cm)(2,2)+2*db1*db2*(*cm)(1,2);x.push_back(q);y.push_back(v);ex.push_back(0);ey.push_back(std::sqrt(std::max(0.,var)));}TGraphErrors g(x.size(),x.data(),y.data(),ex.data(),ey.data());g.SetName("quadratic_veff");g.SetTitle("");g.SetLineColor(color(m));g.SetFillColorAlpha(color(m),.25);g.SetLineWidth(3);g.GetXaxis()->SetTitle("Propagation distance d [m]");g.GetYaxis()->SetTitle("v_{eff}(d) [mm/ns]");TCanvas c(name.c_str(),"",930,650);g.Draw("A3L");TLatex tx;tx.SetNDC();tx.SetTextSize(.043);tx.DrawLatex(.70,.86,m.c_str());tx.SetTextSize(.033);tx.DrawLatex(.17,.18,"Quadratic derivative; global quadratic fit has poor #chi^{2}");c.SaveAs(("figures/"+name+".pdf").c_str());out.cd();g.Write();f->Write();cm->Write("fit_covariance");c.Write();provenance(out,"v=1000/(b1+2*b2*d) mm/ns with full b1-b2 covariance propagation; interpret only as the required quadratic diagnostic because fit adequacy is poor");out.Close();meta(name,"What distance dependence would the required quadratic model imply?","Derivative of quadratic propagation fit with covariance band; model inadequacy explicitly retained");}

void mirror(const std::string&slug){style();std::string m=mat(slug),name="mirror_t0_"+slug;auto t=read("sources/mirror_tests.csv");std::vector<double>x,y,ex,ey;for(auto&r:t.r)if(r.at("material")==m&&r.at("estimator")=="first_pe"){x.push_back(d(r,"abs_x_mm"));y.push_back(1000*d(r,"delta_T0_ns"));ex.push_back(0);ey.push_back(1000*d(r,"error_ns"));}TGraphErrors g(x.size(),x.data(),y.data(),ex.data(),ey.data());g.SetName("mirror_delta_T0");g.SetMarkerStyle(20);g.SetMarkerSize(1.35);g.SetMarkerColor(color(m));g.SetLineColor(color(m));g.SetTitle("");g.GetXaxis()->SetTitle("|x| [mm]");g.GetYaxis()->SetTitle("<#it{T}_{0}(+|x|)> - <#it{T}_{0}(-|x|)> [ps]");g.GetYaxis()->SetRangeUser(-5,5);TCanvas c(name.c_str(),"",930,650);g.Draw("AP");TLine line(150,0,700,0);line.SetLineStyle(2);line.Draw();TLatex tx;tx.SetNDC();tx.SetTextSize(.043);tx.DrawLatex(.72,.86,m.c_str());c.SaveAs(("figures/"+name+".pdf").c_str());TFile out(("figures/"+name+".root").c_str(),"RECREATE");g.Write();c.Write();provenance(out,"Mirrored event means; independent-cell SEM added in quadrature; difference is +|x| minus -|x|");out.Close();meta(name,"Is the timing mean left-right symmetric?","Mirrored differences of event-level T0 means with SEM errors");}

void mean5(){style();std::string name="t0_firstPE_vs_mean5";auto t=read("sources/means.csv");std::vector<double>x,y1,e1,y5,e5,z;double c1=0,c5=0;for(auto&r:t.r)if(r.at("material")=="EJ-230"&&i(r,"x_mm")==0){c1=d(r,"mean_T0_ns");c5=d(r,"mean_T0_m5_ns");}for(int xx:{-650,-500,-200,0,200,500,650})for(auto&r:t.r)if(r.at("material")=="EJ-230"&&i(r,"x_mm")==xx){x.push_back(xx);z.push_back(0);y1.push_back(1000*(d(r,"mean_T0_ns")-c1));e1.push_back(1000*d(r,"sem_T0_ns"));y5.push_back(1000*(d(r,"mean_T0_m5_ns")-c5));e5.push_back(1000*d(r,"sem_T0_m5_ns"));}TGraphErrors g1(x.size(),x.data(),y1.data(),z.data(),e1.data()),g5(x.size(),x.data(),y5.data(),z.data(),e5.data());g1.SetName("first_pe_mean_bias");g5.SetName("mean5_mean_bias");g1.SetMarkerStyle(20);g5.SetMarkerStyle(22);g1.SetMarkerColor(kRed+1);g5.SetMarkerColor(kBlue+1);g1.SetLineColor(kRed+1);g5.SetLineColor(kBlue+1);for(auto*g:{&g1,&g5}){g->SetLineWidth(3);g->SetMarkerSize(1.25);}g1.SetTitle("");g1.GetXaxis()->SetTitle("Muon position x [mm]");g1.GetYaxis()->SetTitle("<T_{0}(x)> - <T_{0}(0)> [ps]");g1.GetYaxis()->SetRangeUser(-5,23);TCanvas c(name.c_str(),"",930,650);g1.Draw("ALP");g5.Draw("LP SAME");TLegend leg(.16,.70,.46,.89);leg.SetBorderSize(0);leg.SetFillStyle(0);leg.AddEntry(&g1,"first PE","lp");leg.AddEntry(&g5,"mean first 5 PE","lp");leg.Draw();c.SaveAs(("figures/"+name+".pdf").c_str());TFile out(("figures/"+name+".root").c_str(),"RECREATE");g1.Write();g5.Write();c.Write();provenance(out,"EJ-230 event means and SEM, each estimator shown relative to its own x=0 mean");out.Close();meta(name,"Does mean-first-five reduce residual position dependence as well as width?","EJ-230 mean first-PE and mean-first-five T0 relative to their own centers");}

void distributions(const std::string&slug){style();std::string m=mat(slug),name="t0_distributions_"+slug;auto tab=read("sources/means.csv");std::map<int,std::map<std::string,std::string>>rr;for(auto&r:tab.r)if(r.at("material")==m)rr[i(r,"x_mm")]=r;TFile in("sources/tsum_veff.root","READ"),out(("figures/"+name+".root").c_str(),"RECREATE");TCanvas c(name.c_str(),"",1450,760);c.Divide(4,2,.003,.003);std::vector<int>xs={-650,-500,-200,0,200,500,650};for(size_t j=0;j<xs.size();j++){c.cd(j+1);gPad->SetLeftMargin(.15);std::string id=rr[xs[j]].at("cell_id");auto*h0=(TH1D*)in.Get(("distributions/T0_"+id).c_str());auto*h=(TH1D*)h0->Clone(("T0_"+id).c_str());h->SetDirectory(&out);h->Scale(1./h->Integral("width"));h->SetLineColor(color(m));h->GetXaxis()->SetTitle("T_{0} [ns]");h->GetYaxis()->SetTitle("density");h->Draw("HIST");auto*p=new TPaveText(.14,.64,.82,.91,"NDC");p->SetFillColor(kWhite);p->SetBorderSize(1);p->SetTextAlign(12);p->SetTextSize(.038);p->AddText(Form("x=%+d mm",xs[j]));p->AddText(Form("mean=%.5f #pm %.5f ns",d(rr[xs[j]],"mean_T0_ns"),d(rr[xs[j]],"sem_T0_ns")));p->AddText(Form("median=%.5f; RMS=%.2f ps",d(rr[xs[j]],"median_T0_ns"),1000*d(rr[xs[j]],"RMS_T0_ns")));p->Draw();}c.cd(8);gPad->Range(0,0,1,1);TLatex tx;tx.SetTextSize(.07);tx.DrawLatex(.12,.72,m.c_str());tx.SetTextSize(.05);tx.DrawLatex(.12,.55,"Means are direct event averages");tx.DrawLatex(.12,.43,"Gaussian fits are not used");c.SaveAs(("figures/"+name+".pdf").c_str());out.cd();c.Write();provenance(out,"All event T0 values; full histogram; direct mean, SEM, median and RMS annotations; no Gaussian mean");out.Close();meta(name,"What distributions determine the mean T0 points?","Seven complete T0 histograms annotated with direct event statistics");}

void lightCorr(const std::string&slug){style();std::string m=mat(slug),name="light_yield_correlations_"+slug;auto t=read("sources/light_correlations.csv");std::vector<double>x,a,b,c,z;for(int xx:{-650,-500,-200,0,200,500,650})for(auto&r:t.r)if(r.at("material")==m&&i(r,"x_mm")==xx){x.push_back(xx);z.push_back(0);a.push_back(d(r,"pearson_T0_NpeEND"));b.push_back(d(r,"pearson_tL_NpeL"));c.push_back(d(r,"pearson_tR_NpeR"));}TGraphErrors ga(x.size(),x.data(),a.data(),z.data(),z.data()),gb(x.size(),x.data(),b.data(),z.data(),z.data()),gc(x.size(),x.data(),c.data(),z.data(),z.data());ga.SetName("rho_T0_NpeEND");gb.SetName("rho_tL_NpeL");gc.SetName("rho_tR_NpeR");int co[3]={kBlack,kBlue+1,kRed+1},mk[3]={20,21,22},q=0;for(auto*g:{&ga,&gb,&gc}){g->SetMarkerStyle(mk[q]);g->SetMarkerColor(co[q]);g->SetLineColor(co[q]);g->SetLineWidth(3);q++;}ga.SetTitle("");ga.GetXaxis()->SetTitle("Muon position x [mm]");ga.GetYaxis()->SetTitle("Pearson correlation #rho");ga.GetYaxis()->SetRangeUser(-.55,.05);TCanvas cc(name.c_str(),"",930,650);ga.Draw("ALP");gb.Draw("LP SAME");gc.Draw("LP SAME");TLegend leg(.17,.69,.52,.89);leg.SetBorderSize(0);leg.SetFillStyle(0);leg.AddEntry(&ga,"T_{0} vs N_{pe,END}","lp");leg.AddEntry(&gb,"t_{L} vs N_{pe,L}","lp");leg.AddEntry(&gc,"t_{R} vs N_{pe,R}","lp");leg.Draw();TLatex tx;tx.SetNDC();tx.SetTextSize(.043);tx.DrawLatex(.72,.86,m.c_str());cc.SaveAs(("figures/"+name+".pdf").c_str());TFile out(("figures/"+name+".root").c_str(),"RECREATE");ga.Write();gb.Write();gc.Write();cc.Write();provenance(out,"Event-level Pearson coefficients by cell; corresponding full ROOT TProfiles are stored in sources/tsum_veff.root/light_profiles");out.Close();meta(name,"Is first-arrival timing correlated with detected light yield?","Descriptive event-level Pearson correlations; full per-cell TProfiles retained in source ROOT");}

void prediction(const std::string&slug){style();std::string m=mat(slug),name="t0_prediction_"+slug,gn="g_first_pe_"+safe(m);TFile in("sources/tsum_veff.root","READ"),out(("figures/"+name+".root").c_str(),"RECREATE");auto*g0=(TGraphErrors*)in.Get(("position_graphs/t0_vs_x_"+safe(m)).c_str());auto*fq=cloneF(in,"propagation_fits/"+gn+"_quadratic","propagation_quadratic");auto*g=(TGraphErrors*)g0->Clone("measured_T0");double b0=fq->GetParameter(0),b1=fq->GetParameter(1),b2=fq->GetParameter(2);auto*pred=new TF1("T0_prediction_from_g2","[0]+[1]*x*x",-.68,.68);pred->SetParameters(b0+.7*b1+.49*b2,b2);pred->SetLineColor(kRed+1);pred->SetLineWidth(3);g->SetMarkerStyle(20);g->SetMarkerColor(color(m));g->SetLineColor(color(m));g->SetTitle("");g->GetXaxis()->SetTitle("Muon position x [m]");g->GetYaxis()->SetTitle("Mean T_{0} [ns]");TCanvas c(name.c_str(),"",930,650);g->Draw("AP");pred->Draw("SAME");TLegend leg(.16,.73,.55,.89);leg.SetBorderSize(0);leg.SetFillStyle(0);leg.AddEntry(g,"direct event mean","p");leg.AddEntry(pred,"0.5[g_{2}(0.7+x)+g_{2}(0.7-x)]","l");leg.Draw();TLatex tx;tx.SetNDC();tx.SetTextSize(.034);tx.DrawLatex(.48,.18,"For quadratic g: T_{0}=b_{0}+0.7b_{1}+0.49b_{2}+b_{2}x^{2}");c.SaveAs(("figures/"+name+".pdf").c_str());out.cd();g->Write();fq->Write();pred->Write();c.Write();provenance(out,"Direct mean T0 and prediction from required combined quadratic g(d); mismatch retained because global quadratic g fit is inadequate");out.Close();meta(name,"Does the quadratic propagation fit predict the observed T0 position dependence?","Direct event means overlaid with algebraic prediction from g2(d)");}
}
#endif
