#ifndef TSUM_SPECTRAL_FIGURES_C
#define TSUM_SPECTRAL_FIGURES_C
#include "figure_common.C"

namespace tvspec {
void distance(const std::string&slug){tvfig::style();std::string m=tvfig::mat(slug),name="spectral_vs_distance_"+slug;auto t=tvfig::read("sources/spectral_summary.csv");std::vector<double>x,ma,mea,md,mf,mef,mfd,z;for(auto&r:t.r)if(r.at("material")==m){x.push_back(tvfig::d(r,"distance_mm"));z.push_back(0);ma.push_back(tvfig::d(r,"mean_wl_all_nm"));mea.push_back(tvfig::d(r,"sem_wl_all_nm"));md.push_back(tvfig::d(r,"median_wl_all_nm"));mf.push_back(tvfig::d(r,"mean_wl_first_nm"));mef.push_back(tvfig::d(r,"sem_wl_first_nm"));mfd.push_back(tvfig::d(r,"median_wl_first_nm"));}TCanvas c(name.c_str(),"",1000,720);c.Divide(1,2,.001,.001);TFile out(("figures/"+name+".root").c_str(),"RECREATE");auto draw=[&](int pad,std::vector<double>&a,std::vector<double>&ae,std::vector<double>&b,const char*title,const char*ga,const char*gb){c.cd(pad);gPad->SetLeftMargin(.13);gPad->SetBottomMargin(pad==2?.18:.10);auto*g1=new TGraphErrors(x.size(),x.data(),a.data(),z.data(),ae.data());auto*g2=new TGraphErrors(x.size(),x.data(),b.data(),z.data(),z.data());g1->SetName(ga);g2->SetName(gb);g1->SetMarkerStyle(20);g2->SetMarkerStyle(24);g1->SetMarkerColor(tvfig::color(m));g2->SetMarkerColor(kBlack);g1->SetLineColor(tvfig::color(m));g2->SetLineColor(kBlack);for(auto*g:{g1,g2}){g->SetLineWidth(2);g->SetMarkerSize(1.1);}g1->SetTitle("");g1->GetXaxis()->SetTitle("Propagation distance d [mm]");g1->GetYaxis()->SetTitle(title);double lo=std::min(*std::min_element(a.begin(),a.end()),*std::min_element(b.begin(),b.end())),hi=std::max(*std::max_element(a.begin(),a.end()),*std::max_element(b.begin(),b.end()));g1->GetYaxis()->SetRangeUser(lo-.15*(hi-lo+.2),hi+.18*(hi-lo+.2));g1->Draw("ALP");g2->Draw("LP SAME");auto*leg=new TLegend(.16,.67,.39,.88);leg->SetBorderSize(0);leg->SetFillStyle(0);leg->AddEntry(g1,"mean","lp");leg->AddEntry(g2,"median","lp");leg->Draw();auto*tx=new TLatex();tx->SetNDC();tx->SetTextSize(.05);tx->DrawLatex(.76,.82,pad==1?"all END hits":"first arrival");out.cd();g1->Write();g2->Write();};draw(1,ma,mea,md,"Detected wavelength [nm]","all_mean","all_median");draw(2,mf,mef,mfd,"First-arrival wavelength [nm]","first_mean","first_median");c.SaveAs(("figures/"+name+".pdf").c_str());out.cd();c.Write();tvfig::provenance(out,"Detected wl_nm by geometric propagation distance; all END hits and first-arriving END hit per event; duplicate side/distance samples combined");out.Close();tvfig::meta(name,"Does the detected spectrum evolve with propagation distance?","Mean and median detected wavelength for all END hits and first-arrival subsets");}

void compare(const std::string&slug){tvfig::style();std::string m=tvfig::mat(slug),name="short_long_spectra_"+slug;TFile in("sources/spectral_check.root","READ"),out(("figures/"+name+".root").c_str(),"RECREATE");TCanvas c(name.c_str(),"",1000,720);c.Divide(1,2,.001,.001);for(int p=1;p<=2;p++){std::string typ=p==1?"all_detected":"first_arrival";auto*a0=(TH1D*)in.Get((tvfig::safe(m)+"_d50_"+typ).c_str()),*b0=(TH1D*)in.Get((tvfig::safe(m)+"_d1350_"+typ).c_str());auto*a=(TH1D*)a0->Clone(("short_"+typ).c_str()),*b=(TH1D*)b0->Clone(("long_"+typ).c_str());a->SetDirectory(&out);b->SetDirectory(&out);a->Scale(1./a->Integral("width"));b->Scale(1./b->Integral("width"));a->SetLineColor(kBlue+1);b->SetLineColor(kRed+1);a->SetLineWidth(2);b->SetLineWidth(2);c.cd(p);gPad->SetLeftMargin(.13);gPad->SetBottomMargin(p==2?.18:.10);a->SetTitle("");a->GetXaxis()->SetTitle("Detected wavelength [nm]");a->GetYaxis()->SetTitle("normalized density");a->SetMaximum(1.12*std::max(a->GetMaximum(),b->GetMaximum()));a->Draw("HIST");b->Draw("HIST SAME");TLegend leg(.66,.67,.88,.88);leg.SetBorderSize(0);leg.SetFillStyle(0);leg.AddEntry(a,"d=50 mm","l");leg.AddEntry(b,"d=1350 mm","l");leg.Draw();TLatex tx;tx.SetNDC();tx.SetTextSize(.05);tx.DrawLatex(.16,.82,p==1?"all END hits":"first arrival");}c.SaveAs(("figures/"+name+".pdf").c_str());out.cd();c.Write();tvfig::provenance(out,"Normalized detected-wavelength spectra at d=50 and 1350 mm; all END hits and first-arriving hit per event");out.Close();tvfig::meta(name,"Do short- and long-distance detected spectra differ?","Normalized ROOT spectra at the shortest and longest sampled distances");}
}
#endif
